// Generated by test_case_gen_executor_cpp_code.py from test_cases_all.json
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <string>
#include <vector>

#include "FormatConstants.hpp"
#include "Test_Execute_FenceRoundTrip.hpp"
#include "Test_GeneratedFenceCaseData.hpp"
#include "Test_Utils.hpp"

namespace {

using peanutbutter::testing::FenceRoundTripOutcome;
using peanutbutter::testing::FenceRoundTripSpec;
using peanutbutter::testing::GeneratedFenceCaseData;
using peanutbutter::testing::GenericArchiveDataMutation;
using peanutbutter::testing::GenericArchiveByteMutation;

const std::vector<GeneratedFenceCaseData> kCases = {
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_000",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"g.cfg", "wxJsCuHbDAKpkjyI"}
      },
      {},
      {
        {"g.cfg", "wxJsCuHbDAKpkjyI"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(87u),
      static_cast<std::int64_t>(31),
      { 0x65 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_001",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"O.md", "YTDVhgXfCmUUE"},
        {"l.txt", "WHiyWsHACsE"}
      },
      {},
      {
        {"O.md", "YTDVhgXfCmUUE"},
        {"l.txt", "WHiyWsHACsE"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(123u),
      static_cast<std::int64_t>(51),
      { 0x37, 0x83, 0xb5, 0x5c, 0x3c, 0xea, 0xd8, 0x3c, 0x98, 0x21, 0xcb, 0x2a, 0xec },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_002",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"DUHB/Z.txt", "qnnNIhVGVy"},
        {"E/oRc/j.md", "M"},
        {"g/P.cfg", "WYBYyL"},
        {"k/S.dat", "TXEZDXqejzX"},
        {"q/Vqq/Y.bin", "qTvEqsmW"},
        {"x.md", "xejXfqejQdF"}
      },
      {},
      {
        {"DUHB/Z.txt", "qnnNIhVGVy"},
        {"E/oRc/j.md", "M"},
        {"g/P.cfg", "WYBYyL"},
        {"k/S.dat", "TXEZDXqejzX"},
        {"q/Vqq/Y.bin", "qTvEqsmW"},
        {"x.md", "xejXfqejQdF"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(266u),
      static_cast<std::int64_t>(146),
      { 0xf7, 0x5b, 0x11, 0x8a, 0x4b, 0xfc, 0x2e, 0x64, 0xf4, 0xb0, 0x92, 0x9a, 0x9c, 0x43 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_003",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"ag/v.bin", "rlaCqDfkbrlaWXIZ"}
      },
      {},
      {
        {"ag/v.bin", "rlaCqDfkbrlaWXIZ"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(106u),
      static_cast<std::int64_t>(34),
      { 0xb7, 0xa1, 0x23, 0x46, 0x9b, 0x3b, 0x73, 0x2b, 0xb8, 0x23, 0xf1, 0x2b, 0x93, 0xac, 0x4e, 0xd4, 0xf8, 0xd7, 0x23, 0xab, 0x9c, 0x24, 0xf5, 0x98, 0xa5, 0x55, 0x6f, 0xff, 0xb9, 0xcb },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_004",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"J.md", "qooBlTNmbIbp"},
        {"U.dat", "hVwBpVI"}
      },
      {},
      {
        {"J.md", "qooBlTNmbIbp"},
        {"U.dat", "hVwBpVI"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(118u),
      static_cast<std::int64_t>(46),
      { 0x32, 0xa2, 0x6f, 0x13, 0x1b, 0x4b, 0xd0, 0x71, 0x16, 0x9b, 0xd2, 0x28, 0xa5, 0x02, 0x61, 0x67, 0xc0, 0x99 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_005",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"C/LSs/d.txt", "lCkReW"},
        {"g.bin", "HYDGxaiOGBxkiKca"},
        {"n/Qyz/I.txt", "TOPxg"},
        {"z/oS/H.dat", "hpSKdXPIcIfEIuA"}
      },
      {},
      {
        {"C/LSs/d.txt", "lCkReW"},
        {"g.bin", "HYDGxaiOGBxkiKca"},
        {"n/Qyz/I.txt", "TOPxg"},
        {"z/oS/H.dat", "hpSKdXPIcIfEIuA"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(217u),
      static_cast<std::int64_t>(113),
      { 0x2d, 0x2e, 0x6c, 0x57, 0xcb, 0x8c, 0xfe, 0xf0, 0x24, 0x97, 0x58, 0xb2, 0x8d, 0x58, 0x58 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_006",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"C.cfg", "R"},
        {"N/VnL/R.bin", "BkRdvEpuRArC"},
        {"i.bin", "kUcT"},
        {"kbu/P.dat", "ZhXdUFxLLBGjBqW"},
        {"t.md", "VAWRGzmxYlqYS"}
      },
      {},
      {
        {"C.cfg", "R"},
        {"N/VnL/R.bin", "BkRdvEpuRArC"},
        {"i.bin", "kUcT"},
        {"kbu/P.dat", "ZhXdUFxLLBGjBqW"},
        {"t.md", "VAWRGzmxYlqYS"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(225u),
      static_cast<std::int64_t>(121),
      { 0x9a, 0x81, 0xad, 0xd3, 0x4d, 0x9a, 0x07 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_007",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"xg/zOm/W.txt", "DJEsHnMIdfpIJoKG"}
      },
      {},
      {
        {"xg/zOm/W.txt", "DJEsHnMIdfpIJoKG"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(110u),
      static_cast<std::int64_t>(38),
      { 0xec, 0xd4, 0x16, 0xf6, 0x74, 0xa0, 0xeb, 0x76, 0x3c, 0xdd, 0x9a, 0x44, 0x44, 0x72, 0x0a, 0xf9, 0x22, 0x8a, 0x86, 0xbc, 0xd6, 0x8d, 0x0a, 0x57, 0xd1, 0xd5 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_008",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"HT/AKG/X.txt", "UDRYFwKgTeVOyG"},
        {"gjpE/OAyn/i.dat", "UWdVPsrsB"}
      },
      {},
      {
        {"HT/AKG/X.txt", "UDRYFwKgTeVOyG"},
        {"gjpE/OAyn/i.dat", "UWdVPsrsB"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(156u),
      static_cast<std::int64_t>(68),
      { 0x74, 0x3b, 0x0b, 0x9e, 0xdd, 0xae, 0x68, 0x58, 0x64, 0x74, 0x41, 0xb9, 0xb4, 0xf4, 0x0e, 0x72, 0xd0, 0x54, 0x64, 0x4c, 0x9d, 0x7f, 0x9c, 0xce, 0x63, 0x87, 0x0f, 0x24 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_009",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"IroY/Tqn/m.txt", "ZKrktZcPGFTne"},
        {"Mm/P/Z.cfg", "PONr"},
        {"j.bin", "fCXjTSB"},
        {"sFP/L.dat", "gTPqygCqdGxDaAQ"},
        {"u/NQ/j.dat", "eX"}
      },
      {},
      {
        {"IroY/Tqn/m.txt", "ZKrktZcPGFTne"},
        {"Mm/P/Z.cfg", "PONr"},
        {"j.bin", "fCXjTSB"},
        {"sFP/L.dat", "gTPqygCqdGxDaAQ"},
        {"u/NQ/j.dat", "eX"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(251u),
      static_cast<std::int64_t>(131),
      { 0x8c, 0x3d, 0xfd, 0x5e, 0x10, 0x53, 0x4d, 0xf2, 0x3b, 0xa9, 0x7b, 0xcc, 0x41, 0x83, 0x48, 0x09, 0x70, 0x32, 0xee, 0x94, 0xb5, 0x70, 0x73, 0x44, 0x32, 0x0a, 0x24, 0x2d, 0x1f },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_010",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"L/ql/e.cfg", "VezgXgw"},
        {"dM/N.txt", "WJJZkrmKSgxshgyu"},
        {"e.bin", "m"},
        {"eFLg/G/U.cfg", "iubjaMpZDVd"},
        {"iQn/L.cfg", "RLIhVLlzGzS"}
      },
      {},
      {
        {"L/ql/e.cfg", "VezgXgw"},
        {"dM/N.txt", "WJJZkrmKSgxshgyu"},
        {"e.bin", "m"},
        {"eFLg/G/U.cfg", "iubjaMpZDVd"},
        {"iQn/L.cfg", "RLIhVLlzGzS"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(252u),
      static_cast<std::int64_t>(132),
      { 0x36, 0x4b, 0x78, 0x75, 0x1a, 0x7d, 0x8a, 0x6d, 0x85, 0x69, 0x7d, 0x7b, 0x8d, 0x3e, 0x6c, 0x73, 0x07, 0x29, 0x9a, 0x82, 0xef, 0xb8, 0xba, 0x3a, 0x75, 0x24, 0x36, 0xf3 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_011",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"XehW/y.md", "wTukMMSgQSibIsbj"}
      },
      {},
      {
        {"XehW/y.md", "wTukMMSgQSibIsbj"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(107u),
      static_cast<std::int64_t>(35),
      { 0x6e, 0x44, 0xd3, 0xb4, 0x2e, 0xdf, 0x38, 0xcc, 0xbd, 0xfc, 0xe6, 0xef, 0x47, 0xa4, 0xf5, 0x41, 0xe9, 0x51, 0x70, 0x57, 0xdf, 0xe3, 0xd3, 0x5c, 0xf9, 0xe6, 0x8f, 0xd6, 0x72 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_012",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"AUb/I/b.txt", "lERvrUNBhrjoUW"},
        {"Tsm/jePZ/o.txt", "G"}
      },
      {},
      {
        {"AUb/I/b.txt", "lERvrUNBhrjoUW"},
        {"Tsm/jePZ/o.txt", "G"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(130u),
      static_cast<std::int64_t>(58),
      { 0xc2, 0x95, 0xbb, 0x50, 0xfd, 0xf7 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_013",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"r.cfg", "UNPa"}
      },
      {},
      {
        {"r.cfg", "UNPa"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(75u),
      static_cast<std::int64_t>(19),
      { 0x9f, 0xe7, 0x61, 0x4c, 0xa1, 0x01, 0xd5, 0x0d, 0x4b, 0x1b, 0xa4, 0x38, 0x35 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_014",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"U.bin", "zhBFlsYf"},
        {"W.cfg", "RuDamXBWU"},
        {"iyrt/Ny/D.cfg", "aImYMOJrHckS"},
        {"li/L.md", "bPzvquliDSkoi"},
        {"wD/j/p.md", "XZGwgchgUnxn"}
      },
      {},
      {
        {"U.bin", "zhBFlsYf"},
        {"W.cfg", "RuDamXBWU"},
        {"iyrt/Ny/D.cfg", "aImYMOJrHckS"},
        {"li/L.md", "bPzvquliDSkoi"},
        {"wD/j/p.md", "XZGwgchgUnxn"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(255u),
      static_cast<std::int64_t>(135),
      { 0x3a, 0x04, 0x79, 0x08, 0x8a, 0xa5, 0x55, 0x24, 0xe9, 0x95, 0xdb, 0x7f, 0xed, 0xdf, 0x0e, 0x84, 0x58, 0x6a, 0xf4, 0x8b, 0x91, 0x60, 0x07, 0x81, 0x06 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_015",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"CjZL/c.cfg", "tCtNHqlLXxdPT"},
        {"L.bin", "DKZpHKLfPzhgRi"},
        {"Y.cfg", "plS"},
        {"Z.md", "kROvxOI"},
        {"c.bin", "tERUq"}
      },
      {},
      {
        {"CjZL/c.cfg", "tCtNHqlLXxdPT"},
        {"L.bin", "DKZpHKLfPzhgRi"},
        {"Y.cfg", "plS"},
        {"Z.md", "kROvxOI"},
        {"c.bin", "tERUq"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(217u),
      static_cast<std::int64_t>(113),
      { 0x92, 0x99, 0xbd, 0xda, 0xcd, 0xf4, 0xad, 0xf5, 0x1a, 0xa4, 0xfe, 0x28, 0xd0, 0xac, 0x10 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_016",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"htZU/x.bin", "jWQXanBzfakwYUoZ"},
        {"zwMb/FwO/P.md", "OZQXWaC"}
      },
      {},
      {
        {"htZU/x.bin", "jWQXanBzfakwYUoZ"},
        {"zwMb/FwO/P.md", "OZQXWaC"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(152u),
      static_cast<std::int64_t>(64),
      { 0x9b, 0x9a, 0x3c, 0xd5, 0x42, 0x3a, 0xfc, 0xeb, 0xca, 0x56, 0xc4, 0xd2, 0x9b, 0x19, 0xe8, 0xf8, 0x63, 0x0f, 0xca, 0xe6, 0x83, 0xa1, 0x20, 0xcd, 0xb9, 0x7c, 0xbf, 0x9d, 0xa2, 0x5d, 0x91, 0x38 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_017",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"C.cfg", "mPdPUW"},
        {"GSK/p.dat", "Gnd"},
        {"K.txt", "rvyr"},
        {"VwUD/M.cfg", "PVqxihwufTSLgWgf"},
        {"W.md", "oJlucJvnIcDCy"},
        {"u.md", "uCsFEIgdUbJDVBkv"}
      },
      {},
      {
        {"C.cfg", "mPdPUW"},
        {"GSK/p.dat", "Gnd"},
        {"K.txt", "rvyr"},
        {"VwUD/M.cfg", "PVqxihwufTSLgWgf"},
        {"W.md", "oJlucJvnIcDCy"},
        {"u.md", "uCsFEIgdUbJDVBkv"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(265u),
      static_cast<std::int64_t>(145),
      { 0xde, 0xc8, 0xd0, 0xd0, 0x9f, 0xd5, 0xd8, 0x70, 0x95, 0x5d, 0xf5, 0x49, 0xc0, 0x4e, 0xf5 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_018",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"a.md", "Pdwotan"}
      },
      {},
      {
        {"a.md", "Pdwotan"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(77u),
      static_cast<std::int64_t>(21),
      { 0x1d, 0xa9, 0x56, 0xa9, 0xf7, 0x0e, 0xac, 0xfe, 0xd3, 0xbf, 0x38 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_019",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"MJG/shD/O.cfg", "vdGYUWPenZ"}
      },
      {},
      {
        {"MJG/shD/O.cfg", "vdGYUWPenZ"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(105u),
      static_cast<std::int64_t>(33),
      { 0xba, 0xe6, 0x60, 0xb5, 0xc0, 0xcb, 0x70, 0x6f, 0xb2, 0x3d, 0x31, 0xeb, 0xe7, 0xc5, 0x1c, 0xa1, 0x6a, 0x92, 0x75, 0x28, 0x24, 0x74, 0x87, 0xa6, 0xe2, 0xdd, 0xcb, 0x43, 0xc7, 0x5b, 0x0f },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_020",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"iZw/c.txt", "NQViFVkflBt"}
      },
      {},
      {
        {"iZw/c.txt", "NQViFVkflBt"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(86u),
      static_cast<std::int64_t>(30),
      { 0x69, 0xc0 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_021",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"E.txt", "EKKSsfBWEJlsHbD"},
        {"a/Q/X.txt", "rcIJFhn"},
        {"h.cfg", "toADaONEdQiLOGLU"},
        {"rYYj/E.bin", "h"}
      },
      {},
      {
        {"E.txt", "EKKSsfBWEJlsHbD"},
        {"a/Q/X.txt", "rcIJFhn"},
        {"h.cfg", "toADaONEdQiLOGLU"},
        {"rYYj/E.bin", "h"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(206u),
      static_cast<std::int64_t>(102),
      { 0x21, 0xa1, 0x96, 0x0f, 0x6a, 0xdc, 0x59, 0x2d, 0x14, 0x6e, 0x7e, 0x45, 0x3b, 0x5d, 0xe4, 0x80, 0x69, 0xab, 0x20, 0x03, 0xec, 0xf2, 0xa1, 0x43, 0xbd, 0xa7 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_022",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"LO/D.bin", "OBKm"},
        {"VOHB/Q.bin", "hIPQCMb"},
        {"e.dat", "JR"},
        {"qH/E.md", "afAUbwuyQ"},
        {"w.dat", "HXDIgAFrISDd"},
        {"x/W.dat", "cqu"}
      },
      {},
      {
        {"LO/D.bin", "OBKm"},
        {"VOHB/Q.bin", "hIPQCMb"},
        {"e.dat", "JR"},
        {"qH/E.md", "afAUbwuyQ"},
        {"w.dat", "HXDIgAFrISDd"},
        {"x/W.dat", "cqu"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(249u),
      static_cast<std::int64_t>(129),
      { 0xc8, 0x7f, 0xcf, 0x9a, 0xc5, 0x7c, 0x57, 0xb5, 0x5a, 0x02, 0x12, 0xbc, 0x96, 0xf5, 0x1a, 0xd6, 0x03, 0x1b, 0xdb, 0xa9, 0xba, 0x99, 0x07, 0xe5, 0x3f, 0x68, 0x32, 0x9a, 0xb3, 0x25, 0xe4 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_023",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"oNl/f.cfg", "d"}
      },
      {},
      {
        {"oNl/f.cfg", "d"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(76u),
      static_cast<std::int64_t>(20),
      { 0x30, 0x0d, 0xa6, 0x26, 0x2d, 0x0b, 0x72, 0xe3, 0x78, 0xd3, 0x14, 0xdb },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_024",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"A.bin", "KelJGuTmJafg"}
      },
      {},
      {
        {"A.bin", "KelJGuTmJafg"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(83u),
      static_cast<std::int64_t>(27),
      { 0xf1, 0x09, 0xd5, 0x08, 0x0d },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_025",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"GSPu/lR/P.cfg", "YaYoRB"},
        {"K.bin", "pRhTtKeWXvC"},
        {"juOx/diIH/T.txt", "SA"}
      },
      {},
      {
        {"GSPu/lR/P.cfg", "YaYoRB"},
        {"K.bin", "pRhTtKeWXvC"},
        {"juOx/diIH/T.txt", "SA"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(166u),
      static_cast<std::int64_t>(78),
      { 0x48, 0x4b, 0x24, 0xf8, 0x6a, 0xaa, 0x67, 0x68, 0xac, 0x37, 0xd3, 0xc2, 0x4e, 0x79, 0x63, 0x22, 0x24, 0x7f },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_026",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"T/DmYt/L.cfg", "ZhZvZrDSUHMPeS"}
      },
      {},
      {
        {"T/DmYt/L.cfg", "ZhZvZrDSUHMPeS"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(108u),
      static_cast<std::int64_t>(36),
      { 0xe9, 0x9b, 0x94, 0x7b, 0xe7, 0xec, 0xf1, 0xd7, 0x64, 0x5e, 0x3a, 0x80, 0x8c, 0x2e, 0x55, 0x43, 0x5f, 0xad, 0xfd, 0x8f, 0xca, 0x28, 0x54, 0xc0, 0xc9, 0x46, 0xef, 0x6f },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_027",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"BjW/kzN/N.cfg", "dlYcKt"},
        {"juF/WwDW/d.md", "APHgANfFrephpl"}
      },
      {},
      {
        {"BjW/kzN/N.cfg", "dlYcKt"},
        {"juF/WwDW/d.md", "APHgANfFrephpl"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(152u),
      static_cast<std::int64_t>(64),
      { 0x2b, 0x8c, 0xcb, 0x85, 0xf3, 0x5e, 0xd9, 0xc5, 0x93, 0x36, 0x0b, 0x66, 0xaa, 0x78, 0x69, 0x7d, 0x97, 0xd0, 0xe6, 0x44, 0xc9, 0xfe, 0x19, 0xda, 0xd6, 0xca, 0x24, 0xb0, 0x24, 0x99, 0x07, 0x17 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_028",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"PO/DLlU/z.md", "WnMfhzhcgDj"},
        {"T/XLxJ/e.cfg", "MuYQkhDxF"},
        {"U.cfg", "fwZQGyM"},
        {"dE/LbG/N.cfg", "hOBggzJVMp"},
        {"ksNh/h.cfg", "dCkA"},
        {"wkl/I.cfg", "MUwxMeBCceyNX"}
      },
      {},
      {
        {"PO/DLlU/z.md", "WnMfhzhcgDj"},
        {"T/XLxJ/e.cfg", "MuYQkhDxF"},
        {"U.cfg", "fwZQGyM"},
        {"dE/LbG/N.cfg", "hOBggzJVMp"},
        {"ksNh/h.cfg", "dCkA"},
        {"wkl/I.cfg", "MUwxMeBCceyNX"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(300u),
      static_cast<std::int64_t>(164),
      { 0xef, 0xd1, 0x79, 0xe4, 0xd1, 0x16, 0x8f, 0xc3, 0x62, 0x57, 0x02, 0x2b, 0x96, 0x0f, 0xe7, 0x2a, 0xe1, 0x4b, 0xa8, 0x1a, 0x2e, 0x69, 0x99, 0xfc, 0xea, 0x8c, 0x17, 0xf0 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_029",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"N.txt", "abheuRapgzIFQkzV"}
      },
      {},
      {
        {"N.txt", "abheuRapgzIFQkzV"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(87u),
      static_cast<std::int64_t>(31),
      { 0x42 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_030",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"GBNZ/t/t.md", "CXEpoAIqx"},
        {"O.txt", "KIC"},
        {"PjE/N.bin", "upwsaObvDlng"},
        {"q/qYH/S.bin", "euLTwnNYJz"}
      },
      {},
      {
        {"GBNZ/t/t.md", "CXEpoAIqx"},
        {"O.txt", "KIC"},
        {"PjE/N.bin", "upwsaObvDlng"},
        {"q/qYH/S.bin", "euLTwnNYJz"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(208u),
      static_cast<std::int64_t>(104),
      { 0x7c, 0x2c, 0xb5, 0x97, 0x1d, 0x77, 0x0b, 0x51, 0xd7, 0x8f, 0x7c, 0x25, 0x11, 0xe3, 0x64, 0x82, 0x0b, 0x3f, 0x4e, 0x08, 0xe5, 0x13, 0x85, 0xc6 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_031",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"V/I.cfg", "EfpMEiStyCHdXO"},
        {"X.txt", "d"},
        {"Y/iLiT/w.txt", "MMQOkeqUm"},
        {"k.bin", "YhpTnsvPf"}
      },
      {},
      {
        {"V/I.cfg", "EfpMEiStyCHdXO"},
        {"X.txt", "d"},
        {"Y/iLiT/w.txt", "MMQOkeqUm"},
        {"k.bin", "YhpTnsvPf"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(200u),
      static_cast<std::int64_t>(96),
      { 0x15, 0xd9, 0x4c, 0xf0, 0x5c, 0x06, 0xfd, 0x9f, 0xfe, 0xc5, 0x38, 0x2f, 0x74, 0x2d, 0xa7, 0x51, 0x96, 0x95, 0x01, 0x15, 0xb4, 0xaa, 0x79, 0xbb, 0x19, 0xf9, 0x23, 0xab, 0xb1, 0x65, 0xa2, 0xa1 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_000",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"FHBdy/Moh.md", "RIFhXFfEUkRjdwMXjRbcQTfThpcvJNMNUCYvDXfFgtmkdYZNehkRDewIzBqGJhSrKnbElzMOc"},
        {"GOJJmmEIujNmasDQZwNJmbdHQX/qvnNvjMDEQYShDJbS/OWKgsdFymCJAkbQqFv.dat", "LbLpYaHMplEJZPipBHLrtx"},
        {"kELSVljNbkMmmBixpAMFSvHHdFBHy/Kf.bin", "zvFhVY"},
        {"oySKMJJMnZum/fijHxKRzTEBUrNJVSAlAf/SJgungkNflc.bin", "zLBiTdZUacEyaxxKgZAnOiViERxoAJDFqwglmynfaqNnycxJJtHysciIYriyzUNFmKEiSagRWRHJWFc"}
      },
      {},
      {
        {"FHBdy/Moh.md", "RIFhXFfEUkRjdwMXjRbcQTfThpcvJNMNUCYvDXfFgtmkdYZNehkRDewIzBqGJhSrKnbElzMOc"},
        {"GOJJmmEIujNmasDQZwNJmbdHQX/qvnNvjMDEQYShDJbS/OWKgsdFymCJAkbQqFv.dat", "LbLpYaHMplEJZPipBHLrtx"},
        {"kELSVljNbkMmmBixpAMFSvHHdFBHy/Kf.bin", "zvFhVY"},
        {"oySKMJJMnZum/fijHxKRzTEBUrNJVSAlAf/SJgungkNflc.bin", "zLBiTdZUacEyaxxKgZAnOiViERxoAJDFqwglmynfaqNnycxJJtHysciIYriyzUNFmKEiSagRWRHJWFc"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(611u),
      static_cast<std::int64_t>(379),
      { 0xe1, 0xc4, 0xdc, 0xc2, 0x23 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_001",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"A/dpMPSQprsEtKlGLJFfl/nKmMgYOpKVbtkaPDkdkTtafrcDoo.cfg", "fjzcbyZoycrWIXSytdgnAjldNmuwVONJQOxDBkJeObTy"},
        {"ArJS.txt", "BWyxcacIJVGOHQBiMiqWgJQwGmleXNKLTjvVbWrHWtUJzozMXuUZvKKHVWRnTvLAnqgcyTvREdudaDR"},
        {"EZEaryLuegRMZdKHVNWbt/bqwLEQXVLuTgxXorMrhmWSGYYzsvjr/KZAKtcgrtElVkUeKdLtyGY.dat", "aWnBfEYUkUDHytVtGXxKZynLqVUAMyDIktCMxhLiCjRioLkyYmQVSYI"},
        {"FFPU.dat", "LTjidkwzxthLeVmHmETfQiRcszqjVovsPwMspeFvmeleuLYHrxvbsRBspoaro"},
        {"HEgoQImIhtoQTgutAMaLaJxytFvrD.md", "X"},
        {"PunhnvPSksjvGjircvzi/sKGSFOcfrFgaAsZavDRSgeucstJPqiFZZk/VTbXQKnAHZrWYSNgOFX.bin", "nzaERKb"},
        {"TAsVDEjDa.cfg", "CWWgWdCFQUeCBapDfIdpdUUfVOUfjPPTxkBSUJNpksNSCpzPtQjbopEA"},
        {"TJDqzfpeiBMRsweTpGOWCrHiUG/wzAIGPygMRNErnRxKNfpWHLpzpaTWlCi.bin", "AKgDyxpBHQafk"},
        {"WSsajbtWZbQnDGpgAOiGgBiPkdKhbVd/tMCVaheZS/WehOwLvwo.txt", "PtyfSzrmKjCppagfvfi"},
        {"fiRUhLpgpVVZohGJWfCLRbiFqpO.cfg", "xWHSbkbBJZDizvPYCfZArtLIhpdpbMSUzREeykkhFKqUQdLQhoRHkgCIkIfdCLshYgpOOiipFIK"},
        {"gAt/OCNYcChvRjTrJXSKzHEYyBswZose.cfg", "JfslrkcceTakTiwZTuXtSXLKieBjShDVGki"},
        {"ibyhZpqXafBboGjcAUqoGJD.cfg", "VqPlzkNFkgsoemoOWRVHzGwp"},
        {"qvoLBzPVvvFioSWCLSwwibbwo/OYFEPqyCWZQvEsmAjKVUlmRbouPYGbF/jDXjI.cfg", "GpoKXhrQgIaEPjFhcgnTQYkfRVInItwiYElgPMTVJEukWfjCQFrkOHGCafGONxzniCY"},
        {"rYCVEUnEXWIXfKrKto/YdXkzGjiiezhKX.md", "KwFczGKpWPumZGrCUzqvvfgFcNdIRryPO"},
        {"uIXOIxQGBGAhuWgcf/DVGXHLlgYG/q.md", "zdCPMbWjEmvngSCXPcyfTJvVfNunhBplRtPBTTIrurVlsUCseHGyYNkv"},
        {"vtUNAMGSkXYCCGBIjyiqy/QpIfoiELIw.md", "TjjttIJroFxKEHZttjpsLPZOornoFDXzqtGjFwlBewrcbZJWMwbjMVOIBDCLIohzmYZHMryLVfStE"},
        {"ycpGbfUZ/grwtjSecdkGOzFWJFtlKxZu.dat", "WkLoCALZAsJGCoLvLWeqihJ"},
        {"zReEGmeHEMLdaOpjyGOVox.dat", "LwSSXdtxfbfoYmgJGEUleyfrgRHHSmZRmNWAXtwHjEUFQTWz"}
      },
      {},
      {
        {"A/dpMPSQprsEtKlGLJFfl/nKmMgYOpKVbtkaPDkdkTtafrcDoo.cfg", "fjzcbyZoycrWIXSytdgnAjldNmuwVONJQOxDBkJeObTy"},
        {"ArJS.txt", "BWyxcacIJVGOHQBiMiqWgJQwGmleXNKLTjvVbWrHWtUJzozMXuUZvKKHVWRnTvLAnqgcyTvREdudaDR"},
        {"EZEaryLuegRMZdKHVNWbt/bqwLEQXVLuTgxXorMrhmWSGYYzsvjr/KZAKtcgrtElVkUeKdLtyGY.dat", "aWnBfEYUkUDHytVtGXxKZynLqVUAMyDIktCMxhLiCjRioLkyYmQVSYI"},
        {"FFPU.dat", "LTjidkwzxthLeVmHmETfQiRcszqjVovsPwMspeFvmeleuLYHrxvbsRBspoaro"},
        {"HEgoQImIhtoQTgutAMaLaJxytFvrD.md", "X"},
        {"PunhnvPSksjvGjircvzi/sKGSFOcfrFgaAsZavDRSgeucstJPqiFZZk/VTbXQKnAHZrWYSNgOFX.bin", "nzaERKb"},
        {"TAsVDEjDa.cfg", "CWWgWdCFQUeCBapDfIdpdUUfVOUfjPPTxkBSUJNpksNSCpzPtQjbopEA"},
        {"TJDqzfpeiBMRsweTpGOWCrHiUG/wzAIGPygMRNErnRxKNfpWHLpzpaTWlCi.bin", "AKgDyxpBHQafk"},
        {"WSsajbtWZbQnDGpgAOiGgBiPkdKhbVd/tMCVaheZS/WehOwLvwo.txt", "PtyfSzrmKjCppagfvfi"},
        {"fiRUhLpgpVVZohGJWfCLRbiFqpO.cfg", "xWHSbkbBJZDizvPYCfZArtLIhpdpbMSUzREeykkhFKqUQdLQhoRHkgCIkIfdCLshYgpOOiipFIK"},
        {"gAt/OCNYcChvRjTrJXSKzHEYyBswZose.cfg", "JfslrkcceTakTiwZTuXtSXLKieBjShDVGki"},
        {"ibyhZpqXafBboGjcAUqoGJD.cfg", "VqPlzkNFkgsoemoOWRVHzGwp"},
        {"qvoLBzPVvvFioSWCLSwwibbwo/OYFEPqyCWZQvEsmAjKVUlmRbouPYGbF/jDXjI.cfg", "GpoKXhrQgIaEPjFhcgnTQYkfRVInItwiYElgPMTVJEukWfjCQFrkOHGCafGONxzniCY"},
        {"rYCVEUnEXWIXfKrKto/YdXkzGjiiezhKX.md", "KwFczGKpWPumZGrCUzqvvfgFcNdIRryPO"},
        {"uIXOIxQGBGAhuWgcf/DVGXHLlgYG/q.md", "zdCPMbWjEmvngSCXPcyfTJvVfNunhBplRtPBTTIrurVlsUCseHGyYNkv"},
        {"vtUNAMGSkXYCCGBIjyiqy/QpIfoiELIw.md", "TjjttIJroFxKEHZttjpsLPZOornoFDXzqtGjFwlBewrcbZJWMwbjMVOIBDCLIohzmYZHMryLVfStE"},
        {"ycpGbfUZ/grwtjSecdkGOzFWJFtlKxZu.dat", "WkLoCALZAsJGCoLvLWeqihJ"},
        {"zReEGmeHEMLdaOpjyGOVox.dat", "LwSSXdtxfbfoYmgJGEUleyfrgRHHSmZRmNWAXtwHjEUFQTWz"}
      },
      static_cast<std::uint32_t>(12u),
      static_cast<std::size_t>(205u),
      static_cast<std::int64_t>(101),
      { 0xdb, 0xf9, 0x1b, 0xca, 0x77, 0x8e, 0xfd, 0xfb, 0x06, 0xe8, 0xb6, 0xdb, 0x61, 0x68, 0x52, 0x5d, 0x10, 0x28, 0x88, 0x84, 0x33, 0x62, 0x62, 0x4e, 0x0c, 0xae, 0xfa },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_002",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"GcbIEOktKuxINtoBZczeBxH/ZPgUvzoEBItLIzud.dat", "iIZEPxVXxVyfYDRFlYcf"},
        {"HspIkNzJojBPoXKtDAEdWVhSWgUsI.dat", "wZvXKRSXsqbNHbEkgMIBqCkGrqZAtwiFlBWIOMNQEjUaACskqBuGubNYNrMW"},
        {"TQuvYbfdGCOVGzk/oIbJwtnuNJmJ/xcuoRzkomsiSv.cfg", "bEzyUXBacHmhrWhPadIHetjqKDFXKKAEYgrrXAzsLwBYpIFQNFIMHZV"}
      },
      {},
      {
        {"GcbIEOktKuxINtoBZczeBxH/ZPgUvzoEBItLIzud.dat", "iIZEPxVXxVyfYDRFlYcf"},
        {"HspIkNzJojBPoXKtDAEdWVhSWgUsI.dat", "wZvXKRSXsqbNHbEkgMIBqCkGrqZAtwiFlBWIOMNQEjUaACskqBuGubNYNrMW"},
        {"TQuvYbfdGCOVGzk/oIbJwtnuNJmJ/xcuoRzkomsiSv.cfg", "bEzyUXBacHmhrWhPadIHetjqKDFXKKAEYgrrXAzsLwBYpIFQNFIMHZV"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(468u),
      static_cast<std::int64_t>(284),
      { 0xc0, 0x8f, 0x93, 0x37 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_003",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"WXXBCgRLYbkELgxDkOOrb.dat", "sfYvPVmFGHWzHlSywxTPpnHwFlasClz"},
        {"crBBkJIqZLuUHKTxaTSoBYHZrAwWoarYNLWQ/SpLDYmSrkXhXZ/KeAcMhrKtyhsaSYc.txt", "VOGJRDJtjcAkLNQyARsNVSPErcyoZyxbXthI"}
      },
      {},
      {
        {"WXXBCgRLYbkELgxDkOOrb.dat", "sfYvPVmFGHWzHlSywxTPpnHwFlasClz"},
        {"crBBkJIqZLuUHKTxaTSoBYHZrAwWoarYNLWQ/SpLDYmSrkXhXZ/KeAcMhrKtyhsaSYc.txt", "VOGJRDJtjcAkLNQyARsNVSPErcyoZyxbXthI"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(317u),
      static_cast<std::int64_t>(181),
      { 0xa2, 0xa0, 0x91, 0x09, 0x7b, 0x0a, 0xde, 0x0d, 0xb5, 0x3b, 0x26 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_004",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"AcxWMHXWmpNDRtv/JUqvEVTrSRtsSxASBUgWudTq.bin", "syMyDEBoWAkk"},
        {"BCRtkPTUpTesbRVWfdKaJsEtCMaULHuzUq/TQiAsiWUAETWswaAsbkSBleeoX/nbKBcUQxXPkervHRw.bin", "FntsrNWZoNYCMAmBEmmHIsPNNuUKAOlUTviNrMrkezjXLKqjlWNJkWDXAWftAkJzlJrkyyYFxJhHX"},
        {"KelDCXwPEzBOKhMJamUFShttoE/nWWTAEPXW.bin", "WKvHYLTvcAPCxJxelYxRnqszRfthZHbmsgCzOlhWnQmZIBiiBeMMscvXcodeqNNRSkPty"},
        {"LTMalialna.txt", "jSMZngKxHoIAVMjQDrfvygeWnmslERIok"},
        {"UeZ.txt", "xuTsoIIUfVXwpgrnJTOHCWkDudCESUaqlwArQl"},
        {"WpJNbWQMYMbZ/cLHyHuzgxK.txt", "DxkUaINMPDtVWdcSFnz"},
        {"bXEKzVoamkGL/hnMYVoIXHKKQTMZTrSDHNejDFxoRjAMa.cfg", "FLKgoelnlaIaZXeYmRbIyGRZUyXTOjIhN"},
        {"cIigLWxfTnMSflbadIpoNSQ/eqCUGkthHCOUnYyLuIgTwEtEI/WnJoIMYHxDFNYEfALnzlRk.dat", "OXorGfeqtgWOdTS"},
        {"gTtufWBspRsE/ZaZTlglAWCIzhlCVQTWfRT.txt", "MgRaNONJIEIxikEgWZyRmkpsrCRkSbKazOfiRteUIPhLpKBrNf"},
        {"icsp/xIZ/SkEYFNIizUphimXR.md", "lSpPUggafBPQIIKCNAwKSBCkTuEHpUhbxFMHYFerGytqQTDqxhBYFLWW"},
        {"jCTGmaVwTwfnvksDQsjWUlHLpokyAMjivtLU/BgmmQFS/hztFYXUZuccFYVxzSRwzyNdvLyjEK.dat", "QKqPbwXNdiXheKQAgTFCgQGYCWdkwvxcSXNVBarYsnrTWbSVYZqASeChtAuTG"},
        {"ngjDkSlInSJjcPHfdsCFZKEg/OfAqlxqBCmEsbS.md", "ZUqQlcRJWMmCYDHZnFKRksYJhxugcLkViwUfgwCFKOqeqzzwZHeUCYLtJedQxqpP"},
        {"rgaFafDZksdvNNgQHMjVFfXrgUuzq/uJ/nZVoE.bin", "NqNJaIHrhbJOJNKGLBmodfrrESSmIcDzkaZSneWqrbiRQDFpCZiTbPPehBlFqOWiLqPjYosKbKkCBg"},
        {"vOQzHgfeuvXmCAHJNe/atRHNqYXhJiamdCx.txt", "wVzIpczZNgVYlupoA"},
        {"wNXUHwVHCHeTEtgQiNJliWkEbRsNEQvDVg/eQzKxpACe/pJRDkeedrzHshzhYbMyNGNtTghMRUnZY.md", "kzMDKzYdhkZdLpHRbgMsqzeLxoJyMSDKWNiNHzRuAocpofZRCcZWdqRTPQBQBUFLQToEFtieSBVkt"},
        {"wZiBWzpOrP.txt", "ujXMkWxdALsVoyZVCzGBatmUsJpQseFbPEYtQmDlssysrpTGVXjTMABTuWNEdXPoRrBTosPhcqvAj"},
        {"zzqmmRGoESWeIbqNPltjjqF.dat", "KWNfDpzqdwJDJzMXmKIFeNdGofyRZqHbLDZzqnKtVuXMytcYOx"}
      },
      {},
      {
        {"AcxWMHXWmpNDRtv/JUqvEVTrSRtsSxASBUgWudTq.bin", "syMyDEBoWAkk"},
        {"BCRtkPTUpTesbRVWfdKaJsEtCMaULHuzUq/TQiAsiWUAETWswaAsbkSBleeoX/nbKBcUQxXPkervHRw.bin", "FntsrNWZoNYCMAmBEmmHIsPNNuUKAOlUTviNrMrkezjXLKqjlWNJkWDXAWftAkJzlJrkyyYFxJhHX"},
        {"KelDCXwPEzBOKhMJamUFShttoE/nWWTAEPXW.bin", "WKvHYLTvcAPCxJxelYxRnqszRfthZHbmsgCzOlhWnQmZIBiiBeMMscvXcodeqNNRSkPty"},
        {"LTMalialna.txt", "jSMZngKxHoIAVMjQDrfvygeWnmslERIok"},
        {"UeZ.txt", "xuTsoIIUfVXwpgrnJTOHCWkDudCESUaqlwArQl"},
        {"WpJNbWQMYMbZ/cLHyHuzgxK.txt", "DxkUaINMPDtVWdcSFnz"},
        {"bXEKzVoamkGL/hnMYVoIXHKKQTMZTrSDHNejDFxoRjAMa.cfg", "FLKgoelnlaIaZXeYmRbIyGRZUyXTOjIhN"},
        {"cIigLWxfTnMSflbadIpoNSQ/eqCUGkthHCOUnYyLuIgTwEtEI/WnJoIMYHxDFNYEfALnzlRk.dat", "OXorGfeqtgWOdTS"},
        {"gTtufWBspRsE/ZaZTlglAWCIzhlCVQTWfRT.txt", "MgRaNONJIEIxikEgWZyRmkpsrCRkSbKazOfiRteUIPhLpKBrNf"},
        {"icsp/xIZ/SkEYFNIizUphimXR.md", "lSpPUggafBPQIIKCNAwKSBCkTuEHpUhbxFMHYFerGytqQTDqxhBYFLWW"},
        {"jCTGmaVwTwfnvksDQsjWUlHLpokyAMjivtLU/BgmmQFS/hztFYXUZuccFYVxzSRwzyNdvLyjEK.dat", "QKqPbwXNdiXheKQAgTFCgQGYCWdkwvxcSXNVBarYsnrTWbSVYZqASeChtAuTG"},
        {"ngjDkSlInSJjcPHfdsCFZKEg/OfAqlxqBCmEsbS.md", "ZUqQlcRJWMmCYDHZnFKRksYJhxugcLkViwUfgwCFKOqeqzzwZHeUCYLtJedQxqpP"},
        {"rgaFafDZksdvNNgQHMjVFfXrgUuzq/uJ/nZVoE.bin", "NqNJaIHrhbJOJNKGLBmodfrrESSmIcDzkaZSneWqrbiRQDFpCZiTbPPehBlFqOWiLqPjYosKbKkCBg"},
        {"vOQzHgfeuvXmCAHJNe/atRHNqYXhJiamdCx.txt", "wVzIpczZNgVYlupoA"},
        {"wNXUHwVHCHeTEtgQiNJliWkEbRsNEQvDVg/eQzKxpACe/pJRDkeedrzHshzhYbMyNGNtTghMRUnZY.md", "kzMDKzYdhkZdLpHRbgMsqzeLxoJyMSDKWNiNHzRuAocpofZRCcZWdqRTPQBQBUFLQToEFtieSBVkt"},
        {"wZiBWzpOrP.txt", "ujXMkWxdALsVoyZVCzGBatmUsJpQseFbPEYtQmDlssysrpTGVXjTMABTuWNEdXPoRrBTosPhcqvAj"},
        {"zzqmmRGoESWeIbqNPltjjqF.dat", "KWNfDpzqdwJDJzMXmKIFeNdGofyRZqHbLDZzqnKtVuXMytcYOx"}
      },
      static_cast<std::uint32_t>(13u),
      static_cast<std::size_t>(85u),
      static_cast<std::int64_t>(29),
      { 0xfd, 0xe7, 0x3d },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_005",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"COdBNStuqCqLxHzgxDPWbdm/f.txt", "wOaLWiUgbQZoPeMyZlgYCakoLglbEcxcnMOZKXGNAUexVQtFrqCshRRQSHtFsxeWKHSTpM"},
        {"FfNzPsclXSOiQnHLOfbPdcAvrnPBvd.md", "nEaiwxmMTyihOMFxyPWDLJKmsoLFQwbmdtgwRvdYFgOTSSZwGsZWyEI"},
        {"JqETeRVvjaYXuaLrujYkUiOAR.txt", "uJSxlcwMKEVeZMmJcWjKNxmdSOvJoYCbHgGgUZQKqaAC"},
        {"YbWODpwkGeFYsVuLxYryNkktlhcLnIm/NYcsHIdAUdWAW.dat", "IwN"},
        {"rT/QsaqISSrsNnrAKEcwVcEMbCGMdlEEWZJ/llUWs.txt", "XkDLCBNSBhGqisRdceTfWOenwcCCMbJKBTpAPdyPReSOjWbCmhnxVukRoXUSQzZYREEBAPdPvzzVUWvS"},
        {"uAVK.dat", "ACowlJXwDSCiVHjfLFHTDfglZhrTMlgLOvImOtpSaywQkzLkx"}
      },
      {},
      {
        {"COdBNStuqCqLxHzgxDPWbdm/f.txt", "wOaLWiUgbQZoPeMyZlgYCakoLglbEcxcnMOZKXGNAUexVQtFrqCshRRQSHtFsxeWKHSTpM"},
        {"FfNzPsclXSOiQnHLOfbPdcAvrnPBvd.md", "nEaiwxmMTyihOMFxyPWDLJKmsoLFQwbmdtgwRvdYFgOTSSZwGsZWyEI"},
        {"JqETeRVvjaYXuaLrujYkUiOAR.txt", "uJSxlcwMKEVeZMmJcWjKNxmdSOvJoYCbHgGgUZQKqaAC"},
        {"YbWODpwkGeFYsVuLxYryNkktlhcLnIm/NYcsHIdAUdWAW.dat", "IwN"},
        {"rT/QsaqISSrsNnrAKEcwVcEMbCGMdlEEWZJ/llUWs.txt", "XkDLCBNSBhGqisRdceTfWOenwcCCMbJKBTpAPdyPReSOjWbCmhnxVukRoXUSQzZYREEBAPdPvzzVUWvS"},
        {"uAVK.dat", "ACowlJXwDSCiVHjfLFHTDfglZhrTMlgLOvImOtpSaywQkzLkx"}
      },
      static_cast<std::uint32_t>(1u),
      static_cast<std::size_t>(104u),
      static_cast<std::int64_t>(32),
      { 0xfa, 0xf7, 0xa7, 0x5f, 0x89, 0x8a, 0xb9, 0xc8, 0x98, 0x20, 0xf7, 0x2f, 0xea, 0x9b, 0x56, 0xee, 0x91, 0x15, 0x59, 0xc8, 0x35, 0x81, 0x3e, 0xdf, 0xdb, 0xa6, 0xdf, 0x62, 0x53, 0xc0, 0x50, 0xf2 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_006",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"BtGMndbiIlXNinrc/OyiH.bin", "OBgYxSHZBweweMrLTRljTiDjCSlHvuVFnQIOWqwKNaQ"},
        {"GSphWB/ldaKNirxdOkqSdYTRc/ffkTiPBaQQtralLutoihRAYFVrT.txt", "As"},
        {"KLhmUpQrFlzuih.md", "ZqhOBQWKiWgqxXFQDNrjtlKZEgPStnqemhdutrLSFxo"},
        {"LKKAAiAgrBXqFLPjryDxyRsTeQ/owufZNFkCpwOi/urWQdqmmugabZoWAxTlAKUM.txt", "DmvRFtfOKYiOCwrEqxcZKbl"},
        {"LovkXPBbfxpTsjALZWQfHutlrOxumW/GkzMGTXKildfefCNOxDtFUqZcAHupKSCS/NqupsEZqaZEE.bin", "cbrMkqFqGXeomB"},
        {"NUTpeqcvpgm.dat", "gLntxipGakQDjCvwNuttvqVlpaTVqJuYLCJcevsoo"},
        {"RGMEupHDLveRTkozwCL/aSSEW.cfg", "XlVtxJFpAblxmrKIhXkrlGMmcFSJEkSlootThBZFpnqfnhAUTBbif"},
        {"TYQVeOoXwLRSrYXl/MwFysMbAIwTdUAGcUjfkbPtWCXgJjlAhs/iwndWJjlTRTHAsgFx.cfg", "m"},
        {"bnJljBxSGnvTwpyrwfCP.md", "llyQvIOCQAlzCmgOZHmwRbXXaBADvCCBOlzDidtBQdGVmdP"},
        {"iZMHmQQJD.cfg", "mzIQogPlA"},
        {"jWwzKyNTZ/kNCI/gaWnNNwvx.dat", "NUmYtlJM"},
        {"uwdrX.md", "BzioRDAiONfsWwsZsXwehRhmCsRZbYPWhXzueUEalfibiPiEDootFoeoveviBpaemhDlnnPczSJQEfW"}
      },
      {},
      {
        {"BtGMndbiIlXNinrc/OyiH.bin", "OBgYxSHZBweweMrLTRljTiDjCSlHvuVFnQIOWqwKNaQ"},
        {"GSphWB/ldaKNirxdOkqSdYTRc/ffkTiPBaQQtralLutoihRAYFVrT.txt", "As"},
        {"KLhmUpQrFlzuih.md", "ZqhOBQWKiWgqxXFQDNrjtlKZEgPStnqemhdutrLSFxo"},
        {"LKKAAiAgrBXqFLPjryDxyRsTeQ/owufZNFkCpwOi/urWQdqmmugabZoWAxTlAKUM.txt", "DmvRFtfOKYiOCwrEqxcZKbl"},
        {"LovkXPBbfxpTsjALZWQfHutlrOxumW/GkzMGTXKildfefCNOxDtFUqZcAHupKSCS/NqupsEZqaZEE.bin", "cbrMkqFqGXeomB"},
        {"NUTpeqcvpgm.dat", "gLntxipGakQDjCvwNuttvqVlpaTVqJuYLCJcevsoo"},
        {"RGMEupHDLveRTkozwCL/aSSEW.cfg", "XlVtxJFpAblxmrKIhXkrlGMmcFSJEkSlootThBZFpnqfnhAUTBbif"},
        {"TYQVeOoXwLRSrYXl/MwFysMbAIwTdUAGcUjfkbPtWCXgJjlAhs/iwndWJjlTRTHAsgFx.cfg", "m"},
        {"bnJljBxSGnvTwpyrwfCP.md", "llyQvIOCQAlzCmgOZHmwRbXXaBADvCCBOlzDidtBQdGVmdP"},
        {"iZMHmQQJD.cfg", "mzIQogPlA"},
        {"jWwzKyNTZ/kNCI/gaWnNNwvx.dat", "NUmYtlJM"},
        {"uwdrX.md", "BzioRDAiONfsWwsZsXwehRhmCsRZbYPWhXzueUEalfibiPiEDootFoeoveviBpaemhDlnnPczSJQEfW"}
      },
      static_cast<std::uint32_t>(3u),
      static_cast<std::size_t>(249u),
      static_cast<std::int64_t>(129),
      { 0xb9, 0xa3, 0xc9, 0xa3, 0x4f, 0x0e, 0xd8, 0x76, 0x10, 0xf4, 0x21, 0x44, 0xb3, 0x76, 0xea, 0xb9, 0x4c, 0x8f, 0x98, 0x17, 0x50, 0xd3, 0xf5, 0xd1, 0x49, 0xcc, 0xe8, 0x01, 0xf8, 0x0a, 0x2b },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_007",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"AiswHRxDBAQehdDLhAuHmKLsd/PoHfzWpjibZzRaBvpm/WxIU.md", "CbLC"},
        {"DkJFdzEjNvUrSiTdFUgAvEaVThjyysdudLhB/HdLqPWyxwARvnMGjGlseP/fBJAmVBZuT.md", "FcxQwVd"},
        {"HDjmyFhMfXeHpuEfScpdpukQHmI/Ha.bin", "wYxAyrVy"},
        {"NGYiSgshAQicUsWjQeFFoh.cfg", "fuhKebqwfTcwpxWeAGRSfTGkOFfDNbVfHVbMpiYYDHFjptrSIEuJIwwB"},
        {"ZtwsYjmLZRcxsBkxTIOoMJVeUiM/Myyftetk.dat", "UsidFxOFOXBLTMMhwI"},
        {"hPKfUutGTB.dat", "aiLGKxicliKhhGTdTxEFILflUcsTcuktfjkxYtnCaNMbFgXhzfaRbWsRxzSGoNGchgICf"},
        {"jnIZxaFmoB.cfg", "xYofUYHWaZfIRyCLU"},
        {"luBMKbrQgfuAUiCuDM.bin", "NJhFloSSPVHLQDvVuu"},
        {"rINsTHcRgWuPfRcMKavh.cfg", "CfLmJW"},
        {"sx.dat", "KoINLiaTBzlUHYRlMGDWDqpQOinWIsRmXZUxGlleuIvUirQBDcmfoXjDVTHuoKALxGXm"},
        {"yMyIQenBCTGvEZPJYLNVFXqParTEGFrRd/mFxGxrrGbWmwEYbWxizh/dpdXYeuCtftkmTiSsoH.txt", "AYIm"}
      },
      {},
      {
        {"AiswHRxDBAQehdDLhAuHmKLsd/PoHfzWpjibZzRaBvpm/WxIU.md", "CbLC"},
        {"DkJFdzEjNvUrSiTdFUgAvEaVThjyysdudLhB/HdLqPWyxwARvnMGjGlseP/fBJAmVBZuT.md", "FcxQwVd"},
        {"HDjmyFhMfXeHpuEfScpdpukQHmI/Ha.bin", "wYxAyrVy"},
        {"NGYiSgshAQicUsWjQeFFoh.cfg", "fuhKebqwfTcwpxWeAGRSfTGkOFfDNbVfHVbMpiYYDHFjptrSIEuJIwwB"},
        {"ZtwsYjmLZRcxsBkxTIOoMJVeUiM/Myyftetk.dat", "UsidFxOFOXBLTMMhwI"},
        {"hPKfUutGTB.dat", "aiLGKxicliKhhGTdTxEFILflUcsTcuktfjkxYtnCaNMbFgXhzfaRbWsRxzSGoNGchgICf"},
        {"jnIZxaFmoB.cfg", "xYofUYHWaZfIRyCLU"},
        {"luBMKbrQgfuAUiCuDM.bin", "NJhFloSSPVHLQDvVuu"},
        {"rINsTHcRgWuPfRcMKavh.cfg", "CfLmJW"},
        {"sx.dat", "KoINLiaTBzlUHYRlMGDWDqpQOinWIsRmXZUxGlleuIvUirQBDcmfoXjDVTHuoKALxGXm"},
        {"yMyIQenBCTGvEZPJYLNVFXqParTEGFrRd/mFxGxrrGbWmwEYbWxizh/dpdXYeuCtftkmTiSsoH.txt", "AYIm"}
      },
      static_cast<std::uint32_t>(1u),
      static_cast<std::size_t>(403u),
      static_cast<std::int64_t>(235),
      { 0x9d, 0x79, 0xfc, 0x4d, 0xe6, 0x9b, 0xaa, 0xdd, 0x62, 0xed, 0x10, 0x65, 0x9a, 0xb0, 0xdc, 0x45, 0x66, 0xff, 0x57, 0x5f, 0xf4 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_008",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"IAwg/PycVqTwiyBeaZImvJDhJbZaZPvqW.md", "rnvmtlijrhLVUXIYouuWUqFxKGzkALJeaINabaTvvNdhgANwcSjA"}
      },
      {},
      {
        {"IAwg/PycVqTwiyBeaZImvJDhJbZaZPvqW.md", "rnvmtlijrhLVUXIYouuWUqFxKGzkALJeaINabaTvvNdhgANwcSjA"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(202u),
      static_cast<std::int64_t>(98),
      { 0x8f, 0x23, 0x45, 0x42, 0x01, 0xd7, 0xf4, 0x42, 0x5f, 0xf4, 0x0d, 0x0a, 0x78, 0xdd, 0xfc, 0xa3, 0x60, 0xad, 0xdd, 0x10, 0xb5, 0x14, 0xab, 0xc7, 0xe6, 0x2b, 0x0e, 0xdc, 0x92, 0x01 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_009",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"SAEnJiVeRpRkWDkisgiAISnHpaUPuP.txt", "oaDbfVqrZskXKcukJrLDwkWQWVMVtupulaHAvYJsQHoTFdzgWoUdeaPCziqqVVbAIZDRlijQFvqP"},
        {"f/aG/LrbVZWwCTrapMxMdHofkQRcOurhvIR.cfg", "OwoLCxfUWOUEGIRAPqwXLUvfoxpnjCseyPaDhUwBglGCFxC"},
        {"mboRxPpStQQoGjVfk/ZEbCtQzvlAUnHAUAwWd.txt", "yzojOPpuOi"}
      },
      {},
      {
        {"SAEnJiVeRpRkWDkisgiAISnHpaUPuP.txt", "oaDbfVqrZskXKcukJrLDwkWQWVMVtupulaHAvYJsQHoTFdzgWoUdeaPCziqqVVbAIZDRlijQFvqP"},
        {"f/aG/LrbVZWwCTrapMxMdHofkQRcOurhvIR.cfg", "OwoLCxfUWOUEGIRAPqwXLUvfoxpnjCseyPaDhUwBglGCFxC"},
        {"mboRxPpStQQoGjVfk/ZEbCtQzvlAUnHAUAwWd.txt", "yzojOPpuOi"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(457u),
      static_cast<std::int64_t>(273),
      { 0x78, 0x84, 0x81, 0x44, 0xc8, 0x17, 0xc8, 0x77, 0x0c, 0x13, 0x54, 0x3d, 0x5b, 0x7f, 0xb3 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_010",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"JPFzahbLDFXUPuG/zTYeDDQcOeRKPatNOQJSDkDTDAzgFmWuL/TzdeOmtVvwZeRKtOFpRwk.dat", "oOpnGGqPDUfUdQwNaRLctOLMGrZqkmBJLRBHTRDNIdGXgKWnlMWVNJOYlncVwBQJYowFcJyeVgcYWOOY"},
        {"NQkINdLpVJyN.md", "mzGLsgBlUVbIpCMQFmJwcHaaLlxYeJmZsqyBShfztGHdNrePXZVthtxpODmizf"},
        {"OcQgoOYOkDvUXTqNRh/mcaJFf.bin", "NaMdOItdWoZNaVHtQmkNHVZyakGoHCiOikappZSSWAMqhwomOcGCUWMZddgrQA"},
        {"OqARVGVOQMi/cUHXpOJfh/mOXRjEYXFsxUz.txt", "hlRDvYopnBFtyTVRUvwXHUvbgwvZSfUjZfgDgxHBakwxJvXzuZYEdYZdEnP"},
        {"WebDWWUwrZeVAnDuhCnVXNHrzQGDJNlrPOHP/PeZYGhtJ/FgMZNTIuONSPdwpgbwHRyfsym.bin", "ySlRAmxvXkJgdquXVfA"},
        {"frBBBFkayrsUtQkqOqiDfmVD/xyUG.dat", "UUPIODJgDaCBJydRfyV"},
        {"mzHOPRzrFRGwNbqJFoV/hkICJXlIPxseyJXUmbGVS.txt", "RIRO"},
        {"nVpUznyHAqybL.dat", "RiHAdCltsAtfRexAqkxsqiZWzn"}
      },
      {},
      {
        {"JPFzahbLDFXUPuG/zTYeDDQcOeRKPatNOQJSDkDTDAzgFmWuL/TzdeOmtVvwZeRKtOFpRwk.dat", "oOpnGGqPDUfUdQwNaRLctOLMGrZqkmBJLRBHTRDNIdGXgKWnlMWVNJOYlncVwBQJYowFcJyeVgcYWOOY"},
        {"NQkINdLpVJyN.md", "mzGLsgBlUVbIpCMQFmJwcHaaLlxYeJmZsqyBShfztGHdNrePXZVthtxpODmizf"},
        {"OcQgoOYOkDvUXTqNRh/mcaJFf.bin", "NaMdOItdWoZNaVHtQmkNHVZyakGoHCiOikappZSSWAMqhwomOcGCUWMZddgrQA"},
        {"OqARVGVOQMi/cUHXpOJfh/mOXRjEYXFsxUz.txt", "hlRDvYopnBFtyTVRUvwXHUvbgwvZSfUjZfgDgxHBakwxJvXzuZYEdYZdEnP"},
        {"WebDWWUwrZeVAnDuhCnVXNHrzQGDJNlrPOHP/PeZYGhtJ/FgMZNTIuONSPdwpgbwHRyfsym.bin", "ySlRAmxvXkJgdquXVfA"},
        {"frBBBFkayrsUtQkqOqiDfmVD/xyUG.dat", "UUPIODJgDaCBJydRfyV"},
        {"mzHOPRzrFRGwNbqJFoV/hkICJXlIPxseyJXUmbGVS.txt", "RIRO"},
        {"nVpUznyHAqybL.dat", "RiHAdCltsAtfRexAqkxsqiZWzn"}
      },
      static_cast<std::uint32_t>(2u),
      static_cast<std::size_t>(365u),
      static_cast<std::int64_t>(213),
      { 0x3b, 0xf8, 0x44, 0x2c, 0xfa, 0x45, 0x40, 0x51, 0x95, 0xc2, 0xe2 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_011",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"BGgwhuCEApQziDGDnpWdJPcztmUfrV/spYDNjiCxuHFRbHFWCT/iNDpspsvMGpjPnvNidOeaCRs.dat", "kRaLzufWVcmhZzCzxXIwLBWmhUOdnTPKiNIzzAWkdIt"},
        {"Bq.bin", "FvRTkwWtWShWLvgxoLKLYmJNuPLOrhNJNbivEgnCBpYCROzJYLNB"},
        {"FiRvlkBFpPQiFHChislOj.dat", "uYeFLnQcYZirUZXBCLTNf"},
        {"JDqUXEXLvvugqTlrRXRckTYIQzQhzD/xczXLwtRJBOOeDQDeSXXiLe/DTAUhlHQ.bin", "oMoI"},
        {"KIrrbRVeWxDJoOQbdPvsJqb.bin", "UAViOmzqUMEiguEtmWKucfPXMOWEpBqlAdOGzrY"},
        {"KiOYTweTjYlxR/sQhkXRIXrtgVXLoJsXtzzFtDlBGUR/KCxYdbKJ.bin", "WeJZQfxkbGCqatLItkOpmBiMeAKPJxCtTzAQZaIesHiinQFBeUrgInWIKxGbqybqvfWhANj"},
        {"OvUj/tZRpMoTvypxf.cfg", "vQYAnUhwJUlhThUCDXVOjAFppeFiJScUtoKJmkyPeiDOJBDDsuUrQZCZEYeDAtR"},
        {"ZHTvUunDQYUFM/mYVmtfmTdu/sfOZAAf.cfg", "tNnaKLazzeSwTzAclzKYayXgRguSwVGqKuIrPGkiBbKnQMsCyFcfwZySDLiTee"},
        {"gKifPWqAf/SKGGKtVvrcvaKpInUC.txt", "HwSKeBQJUCndBcnWnywAfysjLOkbGuMf"},
        {"hvKjscGsxGi/lgRzXgejccbwQcFgZhWsekrLgbwf/W.md", "uPBNRLVHSjpcZzLDKAGGrOpqnVkygCV"},
        {"plVVVzQCdSsWpBoELajz/aglhCPkRDGElWniNJjAvZToyooQVypwiLFo/sHRVgagIeGRQLYTFSepZMzr.cfg", "mARAUcQJjGgrDUfvdGELiMxJdKcjCKRzlTEMFUGUoakSOiTZwczIsTdckWRIfimIuqqqGtyQADcih"},
        {"tPeOzsVkfTjqe/RUaTMrMOhsqpjTFCkgjjMVlbnqP/EZzfjEHXcugOFXEphrSzmoE.txt", "bDVEqIswdPHXoUVOCpBUdoCeJzzeWXTDrdwSPBmZhfMzTZhWlexIsqsKlg"},
        {"vcZKjPhNGnUrmAiBtfPghXBaLE/NAZVUkjEfznyfFhSIXkkLSkzEUMIU.md", "IWlBsVXMdXAvDRovQqjrJekkPIANHYNMgGfutLcGpefGfyHOJYbndaNaJB"},
        {"yNxgSPQfaauuBUm.bin", "IerVjlcHWWYlOEdnNbOsGaLsXhQZXAIvLDbUekjKdBCTmewc"},
        {"ygxUFefCbxhp.cfg", "oDzMsasjWDzMzAMYtjKHaADaayUWDjkQvoMTyLSHYqJVzsQnhOlQQmd"}
      },
      {},
      {
        {"BGgwhuCEApQziDGDnpWdJPcztmUfrV/spYDNjiCxuHFRbHFWCT/iNDpspsvMGpjPnvNidOeaCRs.dat", "kRaLzufWVcmhZzCzxXIwLBWmhUOdnTPKiNIzzAWkdIt"},
        {"Bq.bin", "FvRTkwWtWShWLvgxoLKLYmJNuPLOrhNJNbivEgnCBpYCROzJYLNB"},
        {"FiRvlkBFpPQiFHChislOj.dat", "uYeFLnQcYZirUZXBCLTNf"},
        {"JDqUXEXLvvugqTlrRXRckTYIQzQhzD/xczXLwtRJBOOeDQDeSXXiLe/DTAUhlHQ.bin", "oMoI"},
        {"KIrrbRVeWxDJoOQbdPvsJqb.bin", "UAViOmzqUMEiguEtmWKucfPXMOWEpBqlAdOGzrY"},
        {"KiOYTweTjYlxR/sQhkXRIXrtgVXLoJsXtzzFtDlBGUR/KCxYdbKJ.bin", "WeJZQfxkbGCqatLItkOpmBiMeAKPJxCtTzAQZaIesHiinQFBeUrgInWIKxGbqybqvfWhANj"},
        {"OvUj/tZRpMoTvypxf.cfg", "vQYAnUhwJUlhThUCDXVOjAFppeFiJScUtoKJmkyPeiDOJBDDsuUrQZCZEYeDAtR"},
        {"ZHTvUunDQYUFM/mYVmtfmTdu/sfOZAAf.cfg", "tNnaKLazzeSwTzAclzKYayXgRguSwVGqKuIrPGkiBbKnQMsCyFcfwZySDLiTee"},
        {"gKifPWqAf/SKGGKtVvrcvaKpInUC.txt", "HwSKeBQJUCndBcnWnywAfysjLOkbGuMf"},
        {"hvKjscGsxGi/lgRzXgejccbwQcFgZhWsekrLgbwf/W.md", "uPBNRLVHSjpcZzLDKAGGrOpqnVkygCV"},
        {"plVVVzQCdSsWpBoELajz/aglhCPkRDGElWniNJjAvZToyooQVypwiLFo/sHRVgagIeGRQLYTFSepZMzr.cfg", "mARAUcQJjGgrDUfvdGELiMxJdKcjCKRzlTEMFUGUoakSOiTZwczIsTdckWRIfimIuqqqGtyQADcih"},
        {"tPeOzsVkfTjqe/RUaTMrMOhsqpjTFCkgjjMVlbnqP/EZzfjEHXcugOFXEphrSzmoE.txt", "bDVEqIswdPHXoUVOCpBUdoCeJzzeWXTDrdwSPBmZhfMzTZhWlexIsqsKlg"},
        {"vcZKjPhNGnUrmAiBtfPghXBaLE/NAZVUkjEfznyfFhSIXkkLSkzEUMIU.md", "IWlBsVXMdXAvDRovQqjrJekkPIANHYNMgGfutLcGpefGfyHOJYbndaNaJB"},
        {"yNxgSPQfaauuBUm.bin", "IerVjlcHWWYlOEdnNbOsGaLsXhQZXAIvLDbUekjKdBCTmewc"},
        {"ygxUFefCbxhp.cfg", "oDzMsasjWDzMzAMYtjKHaADaayUWDjkQvoMTyLSHYqJVzsQnhOlQQmd"}
      },
      static_cast<std::uint32_t>(11u),
      static_cast<std::size_t>(157u),
      static_cast<std::int64_t>(69),
      { 0x97, 0xf7, 0x2b, 0x48, 0x9c, 0x4e, 0xf0, 0x0a, 0xd6, 0xb4, 0xed, 0x52, 0x5e, 0x61, 0xb3, 0xa8, 0x03, 0x46, 0x06, 0x58, 0xc7, 0xc3, 0x8a, 0xdd, 0x9a, 0x95, 0x3a },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_012",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"BOmO/eYoJtRVCPgwmSeUifx/WghbAXbR.dat", "BNClVXaMEbwQHMHRCVPoVKvLaJBBUcPWBOJWgxFHWFGyVUOMRxpCtIRfsTNsVuO"},
        {"FiuKtzFOlYrSJrliwpIkJFNAXFE.md", "RAvfEVpWuLXTvgfygOhWsXDLCSZPnRyYwTPjUscJMjUjstlkXvcuRiYeHKMdKIFv"},
        {"OLq/BdeMLfNkgGNQivhGu/mcQbzGesmLelSwZpSNGZUimLyQRXXLW.md", "CNgLbAwXysUeuXGvXqUUWuUdsiIvkHyptYLolcQHsZtSDsfQUZMitdbShJEKctJnssDb"},
        {"Pe.bin", "NFMzLvoklQGvsxuZxkovbfxMpNNdgWRwBuFwxXGYjjgeldhTpaTZzobSLnjGJFXJAlZ"},
        {"WUnNHNlsxYm/yYlmsuX/pLF.dat", "TkzUqZKUOCsYgnpJgljnGIiFjOdKVYlagQEBybNCyFjenkylEgTOpSEZnvnIjbAxcayDhfvmVEmYdWTQ"},
        {"WVYWhFY.bin", "zAoWrRPtRWiDPpQJKpxJEolEt"},
        {"YX/lOlMhDyMrOeCROusyqCMpyx/bLdWewRxb.bin", "zGGzzmrQcmWohEdzsjKYgDKUrwgzape"},
        {"ZuTnpnqQVa/LhPwKWmSFAueHIeFlLSefoMcIBHpwY.cfg", "KOxIfnrSjs"},
        {"ckuUtVyKYSoaJpdmUigNzswRcKIzGUmUo/vceyvegoEpwABhwkfR/WQEGHteUeimaoPdP.dat", "NwIAnBWxJMcjtjPCnmRmrHdpdFokkyTIrHpYfgWntgqgNsgzqcX"},
        {"hZZKIZgasaSuoKNqhFhWt/lshUbqUQjyYpWIjQvSVlfMZx/CRbbKnhRkOwNXxxLOYgr.md", "pfOMnkAGnP"},
        {"iEaUgeXse/UERKhJGkefKWj.cfg", "abbirbJdEWAaBkReyvZSBIpjTwiqWydKoVHQ"},
        {"mKEiuDCTMxEvMWYubDZqXiyMKmNh/LLugjzHRu.dat", "btmAKBkwGQKsaTncDjjOjjMoJFOYxnweUUbDrgGUmgHajchNr"},
        {"pkTHKtbqKCj/MeEvxxlfHPTPIZgbNqGj.md", "sUwTBuilqhASVUNoMVoYNuPEouSsTYfckJDVrMKhlZt"},
        {"uJGzCwDTrdRHneLNCZTd/OFYrsjoaLjNAghBWZyLbzracEzt/IhkCumlZsoSCcPZsuUJvavVgYYwppvWb.bin", "qxtsgyYliiGsDEdxGTBbCLJJtFZIlAGJkHxPizAd"},
        {"wxqRtQsTiBUxodlRtGOMwvUtfVIDCoT.txt", "D"}
      },
      {},
      {
        {"BOmO/eYoJtRVCPgwmSeUifx/WghbAXbR.dat", "BNClVXaMEbwQHMHRCVPoVKvLaJBBUcPWBOJWgxFHWFGyVUOMRxpCtIRfsTNsVuO"},
        {"FiuKtzFOlYrSJrliwpIkJFNAXFE.md", "RAvfEVpWuLXTvgfygOhWsXDLCSZPnRyYwTPjUscJMjUjstlkXvcuRiYeHKMdKIFv"},
        {"OLq/BdeMLfNkgGNQivhGu/mcQbzGesmLelSwZpSNGZUimLyQRXXLW.md", "CNgLbAwXysUeuXGvXqUUWuUdsiIvkHyptYLolcQHsZtSDsfQUZMitdbShJEKctJnssDb"},
        {"Pe.bin", "NFMzLvoklQGvsxuZxkovbfxMpNNdgWRwBuFwxXGYjjgeldhTpaTZzobSLnjGJFXJAlZ"},
        {"WUnNHNlsxYm/yYlmsuX/pLF.dat", "TkzUqZKUOCsYgnpJgljnGIiFjOdKVYlagQEBybNCyFjenkylEgTOpSEZnvnIjbAxcayDhfvmVEmYdWTQ"},
        {"WVYWhFY.bin", "zAoWrRPtRWiDPpQJKpxJEolEt"},
        {"YX/lOlMhDyMrOeCROusyqCMpyx/bLdWewRxb.bin", "zGGzzmrQcmWohEdzsjKYgDKUrwgzape"},
        {"ZuTnpnqQVa/LhPwKWmSFAueHIeFlLSefoMcIBHpwY.cfg", "KOxIfnrSjs"},
        {"ckuUtVyKYSoaJpdmUigNzswRcKIzGUmUo/vceyvegoEpwABhwkfR/WQEGHteUeimaoPdP.dat", "NwIAnBWxJMcjtjPCnmRmrHdpdFokkyTIrHpYfgWntgqgNsgzqcX"},
        {"hZZKIZgasaSuoKNqhFhWt/lshUbqUQjyYpWIjQvSVlfMZx/CRbbKnhRkOwNXxxLOYgr.md", "pfOMnkAGnP"},
        {"iEaUgeXse/UERKhJGkefKWj.cfg", "abbirbJdEWAaBkReyvZSBIpjTwiqWydKoVHQ"},
        {"mKEiuDCTMxEvMWYubDZqXiyMKmNh/LLugjzHRu.dat", "btmAKBkwGQKsaTncDjjOjjMoJFOYxnweUUbDrgGUmgHajchNr"},
        {"pkTHKtbqKCj/MeEvxxlfHPTPIZgbNqGj.md", "sUwTBuilqhASVUNoMVoYNuPEouSsTYfckJDVrMKhlZt"},
        {"uJGzCwDTrdRHneLNCZTd/OFYrsjoaLjNAghBWZyLbzracEzt/IhkCumlZsoSCcPZsuUJvavVgYYwppvWb.bin", "qxtsgyYliiGsDEdxGTBbCLJJtFZIlAGJkHxPizAd"},
        {"wxqRtQsTiBUxodlRtGOMwvUtfVIDCoT.txt", "D"}
      },
      static_cast<std::uint32_t>(5u),
      static_cast<std::size_t>(202u),
      static_cast<std::int64_t>(98),
      { 0x74, 0x75, 0x1d, 0xed, 0x18, 0x55, 0x8c, 0x9e, 0x4a, 0xb2, 0xef, 0xa0, 0x6e, 0x33, 0xd2, 0x86, 0xb7, 0x09, 0xb2, 0x8d, 0xa2, 0x3b, 0xb8, 0x39, 0x60, 0x2b, 0xc1, 0xa9, 0x56, 0x04 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_013",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"GFegiJEyf/C.bin", "YzErhnXiEwIwkErQvIyMWbVO"},
        {"IszFbivXm.cfg", "uEmgTkBHfocVHsiRzwWDnIGIngqeOgAphMoLpbpTyKXJf"},
        {"MXdBnfsXUhkHwSNkJaqM/eYSdjsLuSJfdANalfmRjD.md", "MaSQxNvUoGjhVjbtLVWHbLIyFAwXnhGcguesJPscObUnRKNPUYcpUJbrKiFadFYNzedaSJdDljMl"},
        {"sqSBXTKMlgfpOkOkIxyVHP.md", "SYRcyLmQVQdgyFGoPIvaegIFzXIyiDlhgATafgEDiKNApDqKpJdMrKxMicypmPTZjyYBVqwjCoyDXYa"}
      },
      {},
      {
        {"GFegiJEyf/C.bin", "YzErhnXiEwIwkErQvIyMWbVO"},
        {"IszFbivXm.cfg", "uEmgTkBHfocVHsiRzwWDnIGIngqeOgAphMoLpbpTyKXJf"},
        {"MXdBnfsXUhkHwSNkJaqM/eYSdjsLuSJfdANalfmRjD.md", "MaSQxNvUoGjhVjbtLVWHbLIyFAwXnhGcguesJPscObUnRKNPUYcpUJbrKiFadFYNzedaSJdDljMl"},
        {"sqSBXTKMlgfpOkOkIxyVHP.md", "SYRcyLmQVQdgyFGoPIvaegIFzXIyiDlhgATafgEDiKNApDqKpJdMrKxMicypmPTZjyYBVqwjCoyDXYa"}
      },
      static_cast<std::uint32_t>(2u),
      static_cast<std::size_t>(204u),
      static_cast<std::int64_t>(100),
      { 0x63, 0xc0, 0x07, 0xea, 0x45, 0x86, 0x80, 0x50, 0x1e, 0x4f, 0x29, 0xa6, 0x79, 0x41, 0x48, 0x21, 0x42, 0x38, 0xbe, 0x12, 0xec, 0x61, 0x04, 0x1f, 0xec, 0x67, 0xe0, 0x64 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_014",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"BBGarUFOrnvlHubRqLAoQSMQ/zxBblPoRbI.bin", "NXmvwkfNAAKOGNHgzDXBOIdOnvhRbGdhNxZucizzS"},
        {"HgVwLUtg.dat", "DNidrNlDIoONujBdIEmgwcldlkml"},
        {"JaTbGPdicFTPJgMlLdNijqZgnKavi/tZAqpZ.txt", "oVbnbhAbdHgnXNLeaylVpkVnFYkLEdQajOMzMaOWqxQBbeOaNNmvpc"},
        {"LxsDH.cfg", "mTsDglbdBnJebbZJLGySfkMtyuYSfnPAKeeOypXKzKLdMPhrZSqlEJffgwBXFrZP"},
        {"NkEexEE.bin", "kcFIJVEHmrkEkyamqaFLDGgrgjuEfEtw"},
        {"RJultCEIoEbfGZcZWWvJyplvHSkpXEe/Y/qDUOZaXKvwduzKsHmDVIv.txt", "TCyhDBiPQZdZRspMCOmPEGqTfgPiPqwsCTTOIvvQzzq"},
        {"TmvaMBASDlQP.cfg", "OCJQtwHlYVDdPdCeIUPQxWmQghuapCVeuXBiNPUagTMuMiskyVJWyyZvYDVFtFq"},
        {"ViBpTmTVOafVTuupCxERGgSejX/ErgHdlnkpvmpAgqFNJCdRtHGnmOIscjRZ/GCIkji.md", "ZshqfQlxPGYlptmbUodpZfQzCLokcehGoxSHKxjMYOCkt"},
        {"YAGsSFGrLKduWjTUaoW/OFVtM.txt", "VgSNWHYOYLoIbalQkkLJVrftXuMTYpgqYlthFHVTfqYnGcztUQKcAxSZUZMMhNmSNjWjuwxC"},
        {"igPGlvdRAjoLKFxPGrjXOmGIneR.txt", "YtARjQOMYlPid"},
        {"lWzOaYORriBAknttoodg/OZGxVO.md", "xAyAgDOAWHymsYOEyjwEasWxsUuLoufxLKVerorvMgVM"},
        {"mPhOTplVhFVwsd/vtDKeJ.md", "iCknihvRGejEzyLEUkwtujxPqBDVRKfClfhrnsVkugjDhLdwYllDXdYGWfAoRprTNIGbgrYmAMW"},
        {"nRGxvheXhpocDCXsnjiHjVQcNKHbtjmXf/BUnHSJjDeGIheKADDJtD.bin", "lcXGSHsSXSfGvTDzyYVlBPyFalkNaaYnHOBIaZFjamTQEhPle"},
        {"nbffrnTdyvDLXzaBHobGJkjkK/Hrv/dHtUREzrHBQhakAQuKLgJEOF.md", "BKPVFgfDRi"},
        {"ndLBIcnnNBYpeUxQepyQoBgSWBUqsQX.md", "iSeEaIVfhisazqrdwbVQmUkhhfvAfHaevTTfFhTmfSq"},
        {"oYVdbTozwYLGnAqU.bin", "bycPHEmApUEFlSsixiyqQMYoZuWFvKGoTJnxquCoybhKdtlvQZLhGAcfnhTVs"},
        {"p/SKwSUiQYHP/obwEOPvsXnSoTdD.dat", "WAuGRBbIsi"},
        {"toZLTAWLEsJss.dat", "kDbNbPtnPDzTdfgHeUTiPgEJnGhGcvMzLbZ"}
      },
      {},
      {
        {"BBGarUFOrnvlHubRqLAoQSMQ/zxBblPoRbI.bin", "NXmvwkfNAAKOGNHgzDXBOIdOnvhRbGdhNxZucizzS"},
        {"HgVwLUtg.dat", "DNidrNlDIoONujBdIEmgwcldlkml"},
        {"JaTbGPdicFTPJgMlLdNijqZgnKavi/tZAqpZ.txt", "oVbnbhAbdHgnXNLeaylVpkVnFYkLEdQajOMzMaOWqxQBbeOaNNmvpc"},
        {"LxsDH.cfg", "mTsDglbdBnJebbZJLGySfkMtyuYSfnPAKeeOypXKzKLdMPhrZSqlEJffgwBXFrZP"},
        {"NkEexEE.bin", "kcFIJVEHmrkEkyamqaFLDGgrgjuEfEtw"},
        {"RJultCEIoEbfGZcZWWvJyplvHSkpXEe/Y/qDUOZaXKvwduzKsHmDVIv.txt", "TCyhDBiPQZdZRspMCOmPEGqTfgPiPqwsCTTOIvvQzzq"},
        {"TmvaMBASDlQP.cfg", "OCJQtwHlYVDdPdCeIUPQxWmQghuapCVeuXBiNPUagTMuMiskyVJWyyZvYDVFtFq"},
        {"ViBpTmTVOafVTuupCxERGgSejX/ErgHdlnkpvmpAgqFNJCdRtHGnmOIscjRZ/GCIkji.md", "ZshqfQlxPGYlptmbUodpZfQzCLokcehGoxSHKxjMYOCkt"},
        {"YAGsSFGrLKduWjTUaoW/OFVtM.txt", "VgSNWHYOYLoIbalQkkLJVrftXuMTYpgqYlthFHVTfqYnGcztUQKcAxSZUZMMhNmSNjWjuwxC"},
        {"igPGlvdRAjoLKFxPGrjXOmGIneR.txt", "YtARjQOMYlPid"},
        {"lWzOaYORriBAknttoodg/OZGxVO.md", "xAyAgDOAWHymsYOEyjwEasWxsUuLoufxLKVerorvMgVM"},
        {"mPhOTplVhFVwsd/vtDKeJ.md", "iCknihvRGejEzyLEUkwtujxPqBDVRKfClfhrnsVkugjDhLdwYllDXdYGWfAoRprTNIGbgrYmAMW"},
        {"nRGxvheXhpocDCXsnjiHjVQcNKHbtjmXf/BUnHSJjDeGIheKADDJtD.bin", "lcXGSHsSXSfGvTDzyYVlBPyFalkNaaYnHOBIaZFjamTQEhPle"},
        {"nbffrnTdyvDLXzaBHobGJkjkK/Hrv/dHtUREzrHBQhakAQuKLgJEOF.md", "BKPVFgfDRi"},
        {"ndLBIcnnNBYpeUxQepyQoBgSWBUqsQX.md", "iSeEaIVfhisazqrdwbVQmUkhhfvAfHaevTTfFhTmfSq"},
        {"oYVdbTozwYLGnAqU.bin", "bycPHEmApUEFlSsixiyqQMYoZuWFvKGoTJnxquCoybhKdtlvQZLhGAcfnhTVs"},
        {"p/SKwSUiQYHP/obwEOPvsXnSoTdD.dat", "WAuGRBbIsi"},
        {"toZLTAWLEsJss.dat", "kDbNbPtnPDzTdfgHeUTiPgEJnGhGcvMzLbZ"}
      },
      static_cast<std::uint32_t>(2u),
      static_cast<std::size_t>(788u),
      static_cast<std::int64_t>(492),
      { 0x0e, 0x2d, 0x0e, 0xe9, 0xb9, 0x0e, 0x52, 0xea, 0xea, 0x2b, 0x0f, 0x06, 0xaa, 0xcc, 0xd1, 0xc4, 0x54, 0x16, 0x72, 0x66 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_015",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"IPNWTQwvnteXXaxgjgIreqbvFNdWuzimb/ppObkLTTyZSIlFuaQdXWmjDcpTOpzuV/sQXBqeACFF.txt", "H"},
        {"PdMeeIsqnXZoUFTmGqoRLwyeozDZboq/sHcWDSSMFrwwrgzbpJsAlUJmPZGaDirkuYcp/hXJDdhnbDRIHVqyt.txt", "jfyGFjSdTDJWOckxKcNUxqYfdVZkRuaLCgqqdcalYuDHyXCWCwNwgmEOr"},
        {"lopLbjSoftoIeYLXX.dat", "LxEIFyFLOBWlCpWoutnfYVZVvUjVPKHHdHZVLBfTnoyYMOigJIiTCoajDUkXotOaWiYbhhjED"},
        {"mTAFrTbAhirRGooBEIUAfw/yFPDpHuCdZXJKhjLK.md", "tqnDDPQFCkaqYvxLfSNgotrbeYOXymlPojATGwjGmADMITooAwFcmotufEQ"},
        {"oATFnP/rwPz.cfg", "SjWdabXtzQwGTSQusKsGuXgZKDjmzABGMAPHBDwXPAje"},
        {"ylJmdFQlJlHjesUusHR/BHxKdGnZfmgHMrLBWttwmxz.txt", "XiQUxnYyzILeAyaVtKyIEUTAzGBhhMBzybmDhpfgTfsypMnrCgyKwhPFguw"}
      },
      {},
      {
        {"IPNWTQwvnteXXaxgjgIreqbvFNdWuzimb/ppObkLTTyZSIlFuaQdXWmjDcpTOpzuV/sQXBqeACFF.txt", "H"},
        {"PdMeeIsqnXZoUFTmGqoRLwyeozDZboq/sHcWDSSMFrwwrgzbpJsAlUJmPZGaDirkuYcp/hXJDdhnbDRIHVqyt.txt", "jfyGFjSdTDJWOckxKcNUxqYfdVZkRuaLCgqqdcalYuDHyXCWCwNwgmEOr"},
        {"lopLbjSoftoIeYLXX.dat", "LxEIFyFLOBWlCpWoutnfYVZVvUjVPKHHdHZVLBfTnoyYMOigJIiTCoajDUkXotOaWiYbhhjED"},
        {"mTAFrTbAhirRGooBEIUAfw/yFPDpHuCdZXJKhjLK.md", "tqnDDPQFCkaqYvxLfSNgotrbeYOXymlPojATGwjGmADMITooAwFcmotufEQ"},
        {"oATFnP/rwPz.cfg", "SjWdabXtzQwGTSQusKsGuXgZKDjmzABGMAPHBDwXPAje"},
        {"ylJmdFQlJlHjesUusHR/BHxKdGnZfmgHMrLBWttwmxz.txt", "XiQUxnYyzILeAyaVtKyIEUTAzGBhhMBzybmDhpfgTfsypMnrCgyKwhPFguw"}
      },
      static_cast<std::uint32_t>(2u),
      static_cast<std::size_t>(230u),
      static_cast<std::int64_t>(126),
      { 0xa8, 0xb4 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    }
};

bool ValidateCaseOutcome(const GeneratedFenceCaseData& pCase,
                         const FenceRoundTripOutcome& pOutcome,
                         std::string& pError) {
  if (!pOutcome.mSucceeded) {
    pError = pOutcome.mFailureMessage;
    return false;
  }

  if (!pCase.mExpectedErrorCode.empty()) {
    const bool aHasExpectedError =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, pCase.mExpectedErrorCode) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, pCase.mExpectedErrorCode) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, pCase.mExpectedErrorCode);
    if (!aHasExpectedError) {
      pError = "missing expected error code: " + pCase.mExpectedErrorCode;
      return false;
    }
  }

  if (!pCase.mExpectedFenceFlag.empty()) {
    const bool aHasFenceFlag =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, pCase.mExpectedFenceFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, pCase.mExpectedFenceFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, pCase.mExpectedFenceFlag);
    if (!aHasFenceFlag) {
      pError = "missing expected fence flag: " + pCase.mExpectedFenceFlag;
      return false;
    }
  }

  for (const std::string& aForbiddenFlag : pCase.mForbiddenFenceFlags) {
    const bool aHasForbiddenFlag =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, aForbiddenFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, aForbiddenFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, aForbiddenFlag);
    if (aHasForbiddenFlag) {
      pError = "encountered forbidden fence flag: " + aForbiddenFlag;
      return false;
    }
  }

  return true;
}

}  // namespace

int main() {
  if (peanutbutter::SB_PAYLOAD_SIZE <= (peanutbutter::SB_RECOVERY_HEADER_LENGTH + 1)) {
    std::cout << "[WARN] generated fence suite invalid L1 block size for " << kCases.size() << " case(s).\n";
    return 0;
  }

  for (const GeneratedFenceCaseData& aCase : kCases) {
    FenceRoundTripSpec aSpec;
    aSpec.mCaseName = aCase.mCaseId;
    aSpec.mOriginalFiles = aCase.mInputFiles;
    aSpec.mOriginalEmptyDirectories = aCase.mInputEmptyDirs;
    aSpec.mRecoverableFiles = aCase.mRecoverableFiles;
    aSpec.mArchiveBlockCount = aCase.mArchiveBlockCount;
    aSpec.mExpectMutatedUnbundleFailure = (aCase.mFlow == "unbundle");
    aSpec.mExpectedUnbundleErrorCode = (aCase.mFlow == "unbundle") ? aCase.mExpectedErrorCode : "";
    aSpec.mRunRecoverAfterMutation = (aCase.mFlow == "recover");
    aSpec.mRequireRecoverTreeMatch = false;

    const bool aSupportsPayloadMutation =
        (aCase.mFieldKind == "file_name_length") ||
        (aCase.mFieldKind == "file_content_length") ||
        (aCase.mFieldKind == "directory_name_length") ||
        (aCase.mFieldKind == "eof_gar");
    if (aSupportsPayloadMutation && aCase.mMutationPayloadLogicalOffset >= 0) {
      GenericArchiveDataMutation aMutation;
      aMutation.mArchiveIndex = aCase.mArchiveIndex;
      aMutation.mPayloadLogicalOffset = static_cast<std::size_t>(aCase.mMutationPayloadLogicalOffset);
      aMutation.mBytes = aCase.mMutationBytes;
      aSpec.mMutation.mArchiveDataMutations.push_back(aMutation);
    } else {
      GenericArchiveByteMutation aMutation;
      aMutation.mArchiveIndex = aCase.mArchiveIndex;
      aMutation.mFileOffset = aCase.mMutationFileOffset;
      aMutation.mBytes = aCase.mMutationBytes;
      aSpec.mMutation.mArchiveByteMutations.push_back(aMutation);
    }
    aSpec.mMutation.mArchiveSetMutation.mCreateArchiveIndices = aCase.mCreateArchiveIndices;
    aSpec.mMutation.mArchiveSetMutation.mRemoveArchiveIndices = aCase.mRemoveArchiveIndices;

    const FenceRoundTripOutcome aOutcome = peanutbutter::testing::ExecuteFenceTestRoundTrip(aSpec);
    std::string aError;
    if (!ValidateCaseOutcome(aCase, aOutcome, aError)) {
      std::cerr << "[FAIL] " << aCase.mCaseId << " failed: " << aError << "\n";
      if (!aCase.mFailurePointComment.empty()) {
        std::cerr << "[INFO] " << aCase.mFailurePointComment << "\n";
      }
      std::cerr << aOutcome.mCollectedLogs;
      return 1;
    }
  }

  std::cout << "[PASS] generated fence suite passed for " << kCases.size() << " case(s).\n";
  return 0;
}
