// Generated by test_case_gen_executor_cpp_code.py from test_cases_all.json
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <string>
#include <vector>

#include "FormatConstants.hpp"
#include "Test_Execute_FenceRoundTrip.hpp"
#include "Test_GeneratedFenceCaseData.hpp"
#include "Test_Utils.hpp"

namespace {

using peanutbutter::testing::FenceRoundTripOutcome;
using peanutbutter::testing::FenceRoundTripSpec;
using peanutbutter::testing::GeneratedFenceCaseData;
using peanutbutter::testing::GenericArchiveDataMutation;
using peanutbutter::testing::GenericArchiveByteMutation;

const std::vector<GeneratedFenceCaseData> kCases = {
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_000",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"To/Gf/x.txt", "Y"},
        {"a.dat", "mCGQZGLgwVTfHqo"}
      },
      {},
      {
        {"To/Gf/x.txt", "Y"},
        {"a.dat", "mCGQZGLgwVTfHqo"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(76u),
      static_cast<std::int64_t>(20),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_001",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"X/Q.cfg", "GVvNSoaUBUoBfMeX"},
        {"dM/S.txt", "UWadf"}
      },
      {},
      {
        {"X/Q.cfg", "GVvNSoaUBUoBfMeX"},
        {"dM/S.txt", "UWadf"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_002",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"H.txt", "ahKhcrUsQsCa"},
        {"fM/hVaD/o.cfg", "TTHNZ"}
      },
      {},
      {
        {"H.txt", "ahKhcrUsQsCa"},
        {"fM/hVaD/o.cfg", "TTHNZ"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(81u),
      static_cast<std::int64_t>(25),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_003",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"bWIn/q.bin", "HMTInCzVb"},
        {"nxTz/Y.bin", "Gn"},
        {"oit/w.md", "xMQjdVZeCd"},
        {"v.txt", "dAGEAiLiwRywUOqp"}
      },
      {},
      {
        {"bWIn/q.bin", "HMTInCzVb"},
        {"nxTz/Y.bin", "Gn"},
        {"oit/w.md", "xMQjdVZeCd"},
        {"v.txt", "dAGEAiLiwRywUOqp"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(161u),
      static_cast<std::int64_t>(73),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_004",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"A.dat", "DyScxylRzL"},
        {"IRSB/hSx/V.txt", "NFLUkgmXYvT"},
        {"QU/LIV/l.cfg", "wZuRqKiMozF"},
        {"sfMM/BCi/q.dat", "s"}
      },
      {},
      {
        {"A.dat", "DyScxylRzL"},
        {"IRSB/hSx/V.txt", "NFLUkgmXYvT"},
        {"QU/LIV/l.cfg", "wZuRqKiMozF"},
        {"sfMM/BCi/q.dat", "s"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(175u),
      static_cast<std::int64_t>(87),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_005",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"pKV/XqH/p.dat", "MhTI"},
        {"u/Oxn/K.md", "JEqOiliyGi"},
        {"x.cfg", "szC"}
      },
      {},
      {
        {"pKV/XqH/p.dat", "MhTI"},
        {"u/Oxn/K.md", "JEqOiliyGi"},
        {"x.cfg", "szC"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(125u),
      static_cast<std::int64_t>(53),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_006",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"krm/VW/Q.bin", "ndTvfyHXkSv"}
      },
      {},
      {
        {"krm/VW/Q.bin", "ndTvfyHXkSv"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_007",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"Huu/i.cfg", "IVpVlTgI"},
        {"K/h.cfg", "SxXyjTVOqwZ"},
        {"d.md", "uzUoWWgkIgqYzfv"},
        {"z.bin", "VBnXxdgeWEPXpB"}
      },
      {},
      {
        {"Huu/i.cfg", "IVpVlTgI"},
        {"K/h.cfg", "SxXyjTVOqwZ"},
        {"d.md", "uzUoWWgkIgqYzfv"},
        {"z.bin", "VBnXxdgeWEPXpB"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(166u),
      static_cast<std::int64_t>(78),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_008",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"cPO/o.txt", "jkfCbTSTiBvqO"}
      },
      {},
      {
        {"cPO/o.txt", "jkfCbTSTiBvqO"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_009",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"N.md", "LqZU"},
        {"cLu/IQy/A.bin", "iNPS"},
        {"h.bin", "yfbQVlNOT"},
        {"iJcy/wzwq/f.txt", "Nb"},
        {"ul/q.txt", "OzCDMv"}
      },
      {},
      {
        {"N.md", "LqZU"},
        {"cLu/IQy/A.bin", "iNPS"},
        {"h.bin", "yfbQVlNOT"},
        {"iJcy/wzwq/f.txt", "Nb"},
        {"ul/q.txt", "OzCDMv"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(176u),
      static_cast<std::int64_t>(88),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_010",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"IZGg/mrQd/L.md", "HeT"},
        {"L.dat", "EJcrSP"},
        {"XQ/M.md", "FKMGMiwC"},
        {"Y/Y.dat", "bv"}
      },
      {},
      {
        {"IZGg/mrQd/L.md", "HeT"},
        {"L.dat", "EJcrSP"},
        {"XQ/M.md", "FKMGMiwC"},
        {"Y/Y.dat", "bv"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(155u),
      static_cast<std::int64_t>(67),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_011",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"NIi/a.md", "jPBHwm"},
        {"P/Y/H.txt", "BzIE"},
        {"j.dat", "pmwAonKoGKLbe"},
        {"mpI/G.dat", "CI"},
        {"uj/F.txt", "cTyJlVtDnB"}
      },
      {},
      {
        {"NIi/a.md", "jPBHwm"},
        {"P/Y/H.txt", "BzIE"},
        {"j.dat", "pmwAonKoGKLbe"},
        {"mpI/G.dat", "CI"},
        {"uj/F.txt", "cTyJlVtDnB"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(176u),
      static_cast<std::int64_t>(88),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_012",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"P.cfg", "HZlksoKGAEKoG"}
      },
      {},
      {
        {"P.cfg", "HZlksoKGAEKoG"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_013",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"C.md", "xpCWUHkXJpypIsh"},
        {"z/e.md", "LUCq"}
      },
      {},
      {
        {"C.md", "xpCWUHkXJpypIsh"},
        {"z/e.md", "LUCq"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(83u),
      static_cast<std::int64_t>(27),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_014",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"I.dat", "uqlT"}
      },
      {},
      {
        {"I.dat", "uqlT"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_015",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"o/H.bin", "BPthwnIIEBCXlI"}
      },
      {},
      {
        {"o/H.bin", "BPthwnIIEBCXlI"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_016",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"MLyK/CRSC/q.txt", "mLMji"},
        {"y.bin", "OpddOSMrnyowsm"}
      },
      {},
      {
        {"MLyK/CRSC/q.txt", "mLMji"},
        {"y.bin", "OpddOSMrnyowsm"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(84u),
      static_cast<std::int64_t>(28),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_017",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"J.md", "hBcg"},
        {"Rd/rh/V.bin", "n"},
        {"T/hiRM/c.md", "CLBsdVf"},
        {"l.bin", "jPaAySkjk"},
        {"p.dat", "M"}
      },
      {},
      {
        {"J.md", "hBcg"},
        {"Rd/rh/V.bin", "n"},
        {"T/hiRM/c.md", "CLBsdVf"},
        {"l.bin", "jPaAySkjk"},
        {"p.dat", "M"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(172u),
      static_cast<std::int64_t>(84),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_018",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"nnhz/Z.txt", "A"}
      },
      {},
      {
        {"nnhz/Z.txt", "A"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_019",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"isP/Etqw/z.md", "IkunG"}
      },
      {},
      {
        {"isP/Etqw/z.md", "IkunG"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_020",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"A.cfg", "vVUnWjSCfGRjrNo"},
        {"A.md", "W"},
        {"JVl/m/y.cfg", "jbINwHohuuDj"},
        {"NfV/f.dat", "CBbgtrLrENNHnG"},
        {"R.dat", "uxTUfROis"},
        {"l.md", "kOMtVmpRRXeWWVJ"}
      },
      {},
      {
        {"A.cfg", "vVUnWjSCfGRjrNo"},
        {"A.md", "W"},
        {"JVl/m/y.cfg", "jbINwHohuuDj"},
        {"NfV/f.dat", "CBbgtrLrENNHnG"},
        {"R.dat", "uxTUfROis"},
        {"l.md", "kOMtVmpRRXeWWVJ"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(229u),
      static_cast<std::int64_t>(125),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_021",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"BHt/g.cfg", "dRc"},
        {"a.bin", "ho"},
        {"y.txt", "ATXJmkel"},
        {"z.dat", "sgSibrFgHdRSTy"}
      },
      {},
      {
        {"BHt/g.cfg", "dRc"},
        {"a.bin", "ho"},
        {"y.txt", "ATXJmkel"},
        {"z.dat", "sgSibrFgHdRSTy"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(128u),
      static_cast<std::int64_t>(56),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_022",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"CJB/a.bin", "EOIOwhXpUoo"},
        {"FQ/S/Q.cfg", "mNPANcPPqId"},
        {"dO/R/u.md", "HZLqZQaj"}
      },
      {},
      {
        {"CJB/a.bin", "EOIOwhXpUoo"},
        {"FQ/S/Q.cfg", "mNPANcPPqId"},
        {"dO/R/u.md", "HZLqZQaj"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(129u),
      static_cast<std::int64_t>(57),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_023",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"H.bin", "c"},
        {"N.md", "XthiVkcs"},
        {"V.md", "AUVaqZRS"},
        {"beFo/g.txt", "WZ"},
        {"k.md", "HwttGmUlVkDCETde"},
        {"vifh/vgB/j.bin", "odNqYeplwZVpKrir"}
      },
      {},
      {
        {"H.bin", "c"},
        {"N.md", "XthiVkcs"},
        {"V.md", "AUVaqZRS"},
        {"beFo/g.txt", "WZ"},
        {"k.md", "HwttGmUlVkDCETde"},
        {"vifh/vgB/j.bin", "odNqYeplwZVpKrir"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(206u),
      static_cast<std::int64_t>(102),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_000",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"a.txt", "a"},
        {"b.txt", "b"}
      },
      {},
      {
        {"a.txt", "a"},
        {"b.txt", "b"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(70u),
      static_cast<std::int64_t>(14),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_001",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"AMcPpiDnZFLnj.bin", "UkmyfeGgEi"},
        {"InRKeXwuuOJDz/dmvJsdeBNpWrBaqOmQpZUnviisYtGVuq.cfg", "bKYbxhHLKvoxODQEqXonvlNk"},
        {"PZIL/uokfDMhUIDfkWULaXVGwPwEzvMFnECA/tWrZwLcdaFxjXhAcztHNSLvuQVrBsykO.dat", "lkqjYIsZSRInVPJaDzCqCXgFibk"}
      },
      {},
      {
        {"AMcPpiDnZFLnj.bin", "UkmyfeGgEi"},
        {"InRKeXwuuOJDz/dmvJsdeBNpWrBaqOmQpZUnviisYtGVuq.cfg", "bKYbxhHLKvoxODQEqXonvlNk"},
        {"PZIL/uokfDMhUIDfkWULaXVGwPwEzvMFnECA/tWrZwLcdaFxjXhAcztHNSLvuQVrBsykO.dat", "lkqjYIsZSRInVPJaDzCqCXgFibk"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(221u),
      static_cast<std::int64_t>(117),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_002",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"AYvTdRRScHRAYEmtGuKRfRBxYA.txt", "bOlaaOaFcuSkwhSIQUpXlIbmCaksphhYqNWjgtLUQ"},
        {"EX.bin", "ucVRYiAjDTW"},
        {"EbSpTSFySHquRArLRi.dat", "HNwNzbRHcLefgDfTuasPLihyGtllGKLQOypqWXBdg"}
      },
      {},
      {
        {"AYvTdRRScHRAYEmtGuKRfRBxYA.txt", "bOlaaOaFcuSkwhSIQUpXlIbmCaksphhYqNWjgtLUQ"},
        {"EX.bin", "ucVRYiAjDTW"},
        {"EbSpTSFySHquRArLRi.dat", "HNwNzbRHcLefgDfTuasPLihyGtllGKLQOypqWXBdg"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(208u),
      static_cast<std::int64_t>(104),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_003",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"FivOVUegdeWzrIpepVorozRdopefMtohr/SaZEgSaIoehEYHwyXScbWwPKRZu/yigXWGYAyX.md", "dhVefCpoyZYPRGprKUBKzLUvfAUbHwiWrBcKemQlYVCkIKSYDaEDNaiukcPPg"}
      },
      {},
      {
        {"FivOVUegdeWzrIpepVorozRdopefMtohr/SaZEgSaIoehEYHwyXScbWwPKRZu/yigXWGYAyX.md", "dhVefCpoyZYPRGprKUBKzLUvfAUbHwiWrBcKemQlYVCkIKSYDaEDNaiukcPPg"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_004",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"BxDTrHcVbNqhiMMxAiAnmqB/ijeuthQCbAZMvnbwbWbhVuHjOlq/HUhy.txt", "aiEYuWOsDWCCkifyIVgEkkTgQGIhynacxhYUhlfPFYBMROKAYogyTJVkoGTQnA"},
        {"DDcDaUZhdaNBvFeKd/RkuZUvKGkmiQdUYBQsOyFSPdNdR.cfg", "aqRLPmIkSreTmwGAQgJGzqaIveIIVUeFjqpkOcK"},
        {"EA/jpyLhbgpyRUtIgl.bin", "ybwYKcVEaGvpscZpUdvcXjmSYBMNd"}
      },
      {},
      {
        {"BxDTrHcVbNqhiMMxAiAnmqB/ijeuthQCbAZMvnbwbWbhVuHjOlq/HUhy.txt", "aiEYuWOsDWCCkifyIVgEkkTgQGIhynacxhYUhlfPFYBMROKAYogyTJVkoGTQnA"},
        {"DDcDaUZhdaNBvFeKd/RkuZUvKGkmiQdUYBQsOyFSPdNdR.cfg", "aqRLPmIkSreTmwGAQgJGzqaIveIIVUeFjqpkOcK"},
        {"EA/jpyLhbgpyRUtIgl.bin", "ybwYKcVEaGvpscZpUdvcXjmSYBMNd"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(394u),
      static_cast<std::int64_t>(226),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_005",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"GOWjUCRHIfkZYJBpMedoqCBpTHBmNjkhPIS/xYTmL.cfg", "siSfiHLxfFkKlUayixFvDOdwRrvqbnJwoIVatF"},
        {"NvqonwCYuQeytpxrlRJrWfNc/kynHjcXbatiMWMxehpcUDglvYrGCSxyil/SVZENJReFH.bin", "amVyJnaUoIdxHwZwmReAlKYWJBQgFjNaHrIv"}
      },
      {},
      {
        {"GOWjUCRHIfkZYJBpMedoqCBpTHBmNjkhPIS/xYTmL.cfg", "siSfiHLxfFkKlUayixFvDOdwRrvqbnJwoIVatF"},
        {"NvqonwCYuQeytpxrlRJrWfNc/kynHjcXbatiMWMxehpcUDglvYrGCSxyil/SVZENJReFH.bin", "amVyJnaUoIdxHwZwmReAlKYWJBQgFjNaHrIv"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(179u),
      static_cast<std::int64_t>(91),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_006",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"RfkSByVvBNCVUzfucxGvcOWjlxCvIZ/XBalNQcd.cfg", "QQdUgKUVpqiwxJvu"},
        {"Sd/NCMj.dat", "oXeytXEcxHZyFcbZpVgMNeSbonrBL"},
        {"WXkrGxyftvujPADBpBXfxzJgIqWUueN/QE/mMHnehkzwFvddsMBx.md", "OnRsUfRyKZdfuieRQpNbJmhUHbujhbnuhgyJHHM"}
      },
      {},
      {
        {"RfkSByVvBNCVUzfucxGvcOWjlxCvIZ/XBalNQcd.cfg", "QQdUgKUVpqiwxJvu"},
        {"Sd/NCMj.dat", "oXeytXEcxHZyFcbZpVgMNeSbonrBL"},
        {"WXkrGxyftvujPADBpBXfxzJgIqWUueN/QE/mMHnehkzwFvddsMBx.md", "OnRsUfRyKZdfuieRQpNbJmhUHbujhbnuhgyJHHM"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(219u),
      static_cast<std::int64_t>(115),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_007",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"glOfMDsSHuiEkgvZLNBpRLRXL.dat", "BxRusngJZjtLnlKtaoOPIk"}
      },
      {},
      {
        {"glOfMDsSHuiEkgvZLNBpRLRXL.dat", "BxRusngJZjtLnlKtaoOPIk"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_008",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"KXusROcASpDXcVahxnxnAd.txt", "MEwrPksMhuTeLHCKVqzgvhSSlhHAuLorYoTlfFdgmaFga"}
      },
      {},
      {
        {"KXusROcASpDXcVahxnxnAd.txt", "MEwrPksMhuTeLHCKVqzgvhSSlhHAuLorYoTlfFdgmaFga"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_009",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"BkstXaBRjfzdIyyz.cfg", "TaHUlavfozKEXpCfOHbuauIMvluF"},
        {"HIuGkvXFxPMCAvNapIvnkn/iwPIFbRaySbIHwvVB/aTvHuRoXebexnX.txt", "iIqFLep"},
        {"IQsWsbNOBETLZDz/nGVZQKoysddj/fbVIHRXaW.dat", "AixAbKltARccBmjvpFVArR"},
        {"oHBh.bin", "tTYkAwSmevLYNLfBWTmXGLHChUeHdlYJscbjglNOkkgYJU"}
      },
      {},
      {
        {"BkstXaBRjfzdIyyz.cfg", "TaHUlavfozKEXpCfOHbuauIMvluF"},
        {"HIuGkvXFxPMCAvNapIvnkn/iwPIFbRaySbIHwvVB/aTvHuRoXebexnX.txt", "iIqFLep"},
        {"IQsWsbNOBETLZDz/nGVZQKoysddj/fbVIHRXaW.dat", "AixAbKltARccBmjvpFVArR"},
        {"oHBh.bin", "tTYkAwSmevLYNLfBWTmXGLHChUeHdlYJscbjglNOkkgYJU"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(354u),
      static_cast<std::int64_t>(202),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_010",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"DswBMjJTT.bin", "BsvrbdippuOZMnNffeTMGatywjZIwabYohGNkpLivhTdHwsfKkSL"}
      },
      {},
      {
        {"DswBMjJTT.bin", "BsvrbdippuOZMnNffeTMGatywjZIwabYohGNkpLivhTdHwsfKkSL"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_011",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"enDebSnVQtkOYEsXo.md", "hYyPmFXMFxawULmxfAiNnaudfIyZXFHMHdvSPREvqJbpsmJxscSEyZomxBPmxMTSVUbpaDl"},
        {"tJeZmNKfBKFQlcjlUOfQH/mKtkYmAgdXD.md", "EzINrQCDmHZhXIkrovBcxBiSNbs"},
        {"tNlgiogrZyniwil/DqYpCMzWVshBfKkFeHwTiGicvsy/UVnYotJYemQnA.cfg", "yoOFuvnLTMJuxZCfFiCoPTxNhdbEDOQjTObh"},
        {"uxch.dat", "fzpqkaZJNlljrjxNmwtBwPS"},
        {"z/IleglkgCojknIOrHUMYnQ.md", "dfpvxLNRTZlZlYpaxfOHbSrBJrZpCKjOlNOOhZaHuYlfG"}
      },
      {},
      {
        {"enDebSnVQtkOYEsXo.md", "hYyPmFXMFxawULmxfAiNnaudfIyZXFHMHdvSPREvqJbpsmJxscSEyZomxBPmxMTSVUbpaDl"},
        {"tJeZmNKfBKFQlcjlUOfQH/mKtkYmAgdXD.md", "EzINrQCDmHZhXIkrovBcxBiSNbs"},
        {"tNlgiogrZyniwil/DqYpCMzWVshBfKkFeHwTiGicvsy/UVnYotJYemQnA.cfg", "yoOFuvnLTMJuxZCfFiCoPTxNhdbEDOQjTObh"},
        {"uxch.dat", "fzpqkaZJNlljrjxNmwtBwPS"},
        {"z/IleglkgCojknIOrHUMYnQ.md", "dfpvxLNRTZlZlYpaxfOHbSrBJrZpCKjOlNOOhZaHuYlfG"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(514u),
      static_cast<std::int64_t>(314),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    }
};

bool ValidateCaseOutcome(const GeneratedFenceCaseData& pCase,
                         const FenceRoundTripOutcome& pOutcome,
                         std::string& pError) {
  if (!pOutcome.mSucceeded) {
    pError = pOutcome.mFailureMessage;
    return false;
  }

  if (!pCase.mExpectedErrorCode.empty()) {
    const bool aHasExpectedError =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, pCase.mExpectedErrorCode) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, pCase.mExpectedErrorCode) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, pCase.mExpectedErrorCode);
    if (!aHasExpectedError) {
      pError = "missing expected error code: " + pCase.mExpectedErrorCode;
      return false;
    }
  }

  if (!pCase.mExpectedFenceFlag.empty()) {
    const bool aHasFenceFlag =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, pCase.mExpectedFenceFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, pCase.mExpectedFenceFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, pCase.mExpectedFenceFlag);
    if (!aHasFenceFlag) {
      pError = "missing expected fence flag: " + pCase.mExpectedFenceFlag;
      return false;
    }
  }

  for (const std::string& aForbiddenFlag : pCase.mForbiddenFenceFlags) {
    const bool aHasForbiddenFlag =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, aForbiddenFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, aForbiddenFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, aForbiddenFlag);
    if (aHasForbiddenFlag) {
      pError = "encountered forbidden fence flag: " + aForbiddenFlag;
      return false;
    }
  }

  return true;
}

}  // namespace

int main() {
  for (const GeneratedFenceCaseData& aCase : kCases) {
    FenceRoundTripSpec aSpec;
    aSpec.mCaseName = aCase.mCaseId;
    aSpec.mOriginalFiles = aCase.mInputFiles;
    aSpec.mOriginalEmptyDirectories = aCase.mInputEmptyDirs;
    aSpec.mRecoverableFiles = aCase.mRecoverableFiles;
    aSpec.mArchiveBlockCount = aCase.mArchiveBlockCount;
    aSpec.mExpectMutatedUnbundleFailure = (aCase.mFlow == "unbundle");
    aSpec.mExpectedUnbundleErrorCode = (aCase.mFlow == "unbundle") ? aCase.mExpectedErrorCode : "";
    aSpec.mRunRecoverAfterMutation = (aCase.mFlow == "recover");
    aSpec.mRequireRecoverTreeMatch = false;

    const bool aSupportsPayloadMutation =
        (aCase.mFieldKind == "file_name_length") ||
        (aCase.mFieldKind == "file_content_length") ||
        (aCase.mFieldKind == "directory_name_length") ||
        (aCase.mFieldKind == "eof_gar");
    if (aSupportsPayloadMutation && aCase.mMutationPayloadLogicalOffset >= 0) {
      GenericArchiveDataMutation aMutation;
      aMutation.mArchiveIndex = aCase.mArchiveIndex;
      aMutation.mPayloadLogicalOffset = static_cast<std::size_t>(aCase.mMutationPayloadLogicalOffset);
      aMutation.mBytes = aCase.mMutationBytes;
      aSpec.mMutation.mArchiveDataMutations.push_back(aMutation);
    } else {
      GenericArchiveByteMutation aMutation;
      aMutation.mArchiveIndex = aCase.mArchiveIndex;
      aMutation.mFileOffset = aCase.mMutationFileOffset;
      aMutation.mBytes = aCase.mMutationBytes;
      aSpec.mMutation.mArchiveByteMutations.push_back(aMutation);
    }
    aSpec.mMutation.mArchiveSetMutation.mCreateArchiveIndices = aCase.mCreateArchiveIndices;
    aSpec.mMutation.mArchiveSetMutation.mRemoveArchiveIndices = aCase.mRemoveArchiveIndices;

    const FenceRoundTripOutcome aOutcome = peanutbutter::testing::ExecuteFenceTestRoundTrip(aSpec);
    std::string aError;
    if (!ValidateCaseOutcome(aCase, aOutcome, aError)) {
      std::cerr << "[FAIL] " << aCase.mCaseId << " failed: " << aError << "\n";
      if (!aCase.mFailurePointComment.empty()) {
        std::cerr << "[INFO] " << aCase.mFailurePointComment << "\n";
      }
      std::cerr << aOutcome.mCollectedLogs;
      return 1;
    }
  }

  std::cout << "[PASS] generated fence suite passed for " << kCases.size() << " case(s).\n";
  return 0;
}
