// Generated by test_case_gen_executor_cpp_code.py from test_cases_all.json
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <string>
#include <vector>

#include "FormatConstants.hpp"
#include "Test_Execute_FenceRoundTrip.hpp"
#include "Test_GeneratedFenceCaseData.hpp"
#include "Test_Utils.hpp"

namespace {

using peanutbutter::testing::FenceRoundTripOutcome;
using peanutbutter::testing::FenceRoundTripSpec;
using peanutbutter::testing::GeneratedFenceCaseData;
using peanutbutter::testing::GenericArchiveDataMutation;
using peanutbutter::testing::GenericArchiveByteMutation;

const std::vector<GeneratedFenceCaseData> kCases = {
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_000",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"K.txt", "TQUmOfBFqYXYURo"},
        {"LVK/CVh/Y.dat", "sauottBJkLJMF"},
        {"gyJT/ONN/w.bin", "L"},
        {"ymrz/Vil/y.txt", "uHP"}
      },
      {},
      {
        {"K.txt", "TQUmOfBFqYXYURo"},
        {"LVK/CVh/Y.dat", "sauottBJkLJMF"},
        {"gyJT/ONN/w.bin", "L"},
        {"ymrz/Vil/y.txt", "uHP"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(173u),
      static_cast<std::int64_t>(85),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_001",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"jU/IZSs/b.cfg", "TSOSYrXcWxHaI"}
      },
      {},
      {
        {"jU/IZSs/b.cfg", "TSOSYrXcWxHaI"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_002",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"c.txt", "ItygWuxfgJYqxSS"}
      },
      {},
      {
        {"c.txt", "ItygWuxfgJYqxSS"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_003",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"G.cfg", "Ewd"},
        {"KTU/X.txt", "sKWYSmG"},
        {"m.cfg", "WhTQaNtbjxtryZB"}
      },
      {},
      {
        {"G.cfg", "Ewd"},
        {"KTU/X.txt", "sKWYSmG"},
        {"m.cfg", "WhTQaNtbjxtryZB"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(112u),
      static_cast<std::int64_t>(40),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_004",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"Ts/x.md", "DTOH"}
      },
      {},
      {
        {"Ts/x.md", "DTOH"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_005",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"N/j.md", "GF"},
        {"T/t.bin", "ICt"},
        {"lvu/SOI/z.txt", "dyNtybIVdQ"},
        {"qkRb/F/U.md", "kumXRLVC"}
      },
      {},
      {
        {"N/j.md", "GF"},
        {"T/t.bin", "ICt"},
        {"lvu/SOI/z.txt", "dyNtybIVdQ"},
        {"qkRb/F/U.md", "kumXRLVC"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(153u),
      static_cast<std::int64_t>(65),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_006",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"B.dat", "VvddZO"},
        {"QZtY/v.dat", "Dg"}
      },
      {},
      {
        {"B.dat", "VvddZO"},
        {"QZtY/v.dat", "Dg"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(75u),
      static_cast<std::int64_t>(19),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_007",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"d.md", "ozFyuYqneFKaL"},
        {"f.cfg", "RxxlXbnN"},
        {"f.dat", "YuKrAHxmJFBY"},
        {"qVax/y.txt", "SAN"},
        {"v/Y.md", "n"}
      },
      {},
      {
        {"d.md", "ozFyuYqneFKaL"},
        {"f.cfg", "RxxlXbnN"},
        {"f.dat", "YuKrAHxmJFBY"},
        {"qVax/y.txt", "SAN"},
        {"v/Y.md", "n"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(180u),
      static_cast<std::int64_t>(92),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_008",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"D/LI/Q.md", "jHubgzsrKLZbiJKd"},
        {"V.cfg", "yjOVyGTMOxCRDw"},
        {"n/O.txt", "fdJWc"},
        {"px/P.txt", "JC"},
        {"s/P.txt", "aAMEAuxueZdlm"}
      },
      {},
      {
        {"D/LI/Q.md", "jHubgzsrKLZbiJKd"},
        {"V.cfg", "yjOVyGTMOxCRDw"},
        {"n/O.txt", "fdJWc"},
        {"px/P.txt", "JC"},
        {"s/P.txt", "aAMEAuxueZdlm"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(202u),
      static_cast<std::int64_t>(98),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_009",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"Eng/mPJs/C.md", "GqTZWyFx"},
        {"ITN/GWF/m.txt", "gDKQyV"},
        {"luXs/bFS/Q.dat", "j"},
        {"um/bSU/x.cfg", "AOZZUOmoVJvr"}
      },
      {},
      {
        {"Eng/mPJs/C.md", "GqTZWyFx"},
        {"ITN/GWF/m.txt", "gDKQyV"},
        {"luXs/bFS/Q.dat", "j"},
        {"um/bSU/x.cfg", "AOZZUOmoVJvr"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(167u),
      static_cast<std::int64_t>(79),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_010",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"COB/AHQ/p.dat", "LRFQlbqjDGdEJi"},
        {"EIlo/gQa/a.md", "gl"},
        {"Kzw/I.md", "Gca"},
        {"LCE/g.txt", "h"},
        {"qS/wL/b.md", "OywLYTIwoWGzjqq"},
        {"tSHG/GhbA/N.dat", "b"}
      },
      {},
      {
        {"COB/AHQ/p.dat", "LRFQlbqjDGdEJi"},
        {"EIlo/gQa/a.md", "gl"},
        {"Kzw/I.md", "Gca"},
        {"LCE/g.txt", "h"},
        {"qS/wL/b.md", "OywLYTIwoWGzjqq"},
        {"tSHG/GhbA/N.dat", "b"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(248u),
      static_cast<std::int64_t>(128),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_011",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"ULE/G.dat", "BNM"},
        {"V/vru/k.txt", "DcUiEmSsH"},
        {"bDq/Kz/b.cfg", "VGHpApkX"},
        {"e.md", "OVcFqGAKI"},
        {"j.cfg", "jESA"}
      },
      {},
      {
        {"ULE/G.dat", "BNM"},
        {"V/vru/k.txt", "DcUiEmSsH"},
        {"bDq/Kz/b.cfg", "VGHpApkX"},
        {"e.md", "OVcFqGAKI"},
        {"j.cfg", "jESA"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(201u),
      static_cast<std::int64_t>(97),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_012",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"b/IN/K.dat", "zerzrfXHqWK"}
      },
      {},
      {
        {"b/IN/K.dat", "zerzrfXHqWK"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_013",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"HTV/u.dat", "g"},
        {"W.bin", "PfGiVlTRNrJbBAIh"},
        {"w.cfg", "dCnhTwuJ"}
      },
      {},
      {
        {"HTV/u.dat", "g"},
        {"W.bin", "PfGiVlTRNrJbBAIh"},
        {"w.cfg", "dCnhTwuJ"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(119u),
      static_cast<std::int64_t>(47),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_014",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"b/g/o.txt", "QSteq"},
        {"i/x.bin", "TrBBkMWlb"},
        {"pUM/P.bin", "KUWstDxumRsO"},
        {"qEt/c.dat", "pybfYkNzdeIJV"},
        {"t.dat", "zHfKfcXZpgqL"},
        {"u/c.dat", "NphoowsE"}
      },
      {},
      {
        {"b/g/o.txt", "QSteq"},
        {"i/x.bin", "TrBBkMWlb"},
        {"pUM/P.bin", "KUWstDxumRsO"},
        {"qEt/c.dat", "pybfYkNzdeIJV"},
        {"t.dat", "zHfKfcXZpgqL"},
        {"u/c.dat", "NphoowsE"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(250u),
      static_cast<std::int64_t>(130),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_015",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"P.dat", "LPxwHLZYIqbvXadS"},
        {"o.txt", "SJNAZb"}
      },
      {},
      {
        {"P.dat", "LPxwHLZYIqbvXadS"},
        {"o.txt", "SJNAZb"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(85u),
      static_cast<std::int64_t>(29),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_016",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"r.cfg", "GXQHqVJjWbrLA"}
      },
      {},
      {
        {"r.cfg", "GXQHqVJjWbrLA"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_017",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"GBD/e.md", "sr"},
        {"Jt/B.cfg", "Bn"},
        {"eDjY/PNaY/l.txt", "JRjZaBWTWcV"},
        {"lTi/PbBw/x.md", "q"},
        {"rfM/d.dat", "VpTeBzZhhdfaAm"}
      },
      {},
      {
        {"GBD/e.md", "sr"},
        {"Jt/B.cfg", "Bn"},
        {"eDjY/PNaY/l.txt", "JRjZaBWTWcV"},
        {"lTi/PbBw/x.md", "q"},
        {"rfM/d.dat", "VpTeBzZhhdfaAm"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(180u),
      static_cast<std::int64_t>(92),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_018",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"G/io/f.cfg", "tWNzcvvRGJUQC"},
        {"U/y.txt", "RQZex"}
      },
      {},
      {
        {"G/io/f.cfg", "tWNzcvvRGJUQC"},
        {"U/y.txt", "RQZex"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_019",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"Hx/e/V.dat", "IVDigJm"},
        {"K.dat", "r"},
        {"Z.bin", "qkcNW"},
        {"l/y.bin", "wpLRAotvrqeX"},
        {"u.txt", "Y"}
      },
      {},
      {
        {"Hx/e/V.dat", "IVDigJm"},
        {"K.dat", "r"},
        {"Z.bin", "qkcNW"},
        {"l/y.bin", "wpLRAotvrqeX"},
        {"u.txt", "Y"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(172u),
      static_cast<std::int64_t>(84),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_020",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"p/vTn/P.md", "lnyKQlq"}
      },
      {},
      {
        {"p/vTn/P.md", "lnyKQlq"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_021",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"KJXJ/dooo/G.dat", "goeRm"},
        {"P.bin", "mSVweUZLYr"},
        {"e/o.cfg", "mQhKb"},
        {"w.md", "LfGIoqdavMvvtYl"}
      },
      {},
      {
        {"KJXJ/dooo/G.dat", "goeRm"},
        {"P.bin", "mSVweUZLYr"},
        {"e/o.cfg", "mQhKb"},
        {"w.md", "LfGIoqdavMvvtYl"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(159u),
      static_cast<std::int64_t>(71),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_022",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"XpIN/r.bin", "GvIFlyzFwkELUWU"},
        {"v.bin", "sfhjQDpCXLYB"},
        {"wLl/q.md", "quQoFZgbOZNKcpZX"}
      },
      {},
      {
        {"XpIN/r.bin", "GvIFlyzFwkELUWU"},
        {"v.bin", "sfhjQDpCXLYB"},
        {"wLl/q.md", "quQoFZgbOZNKcpZX"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(130u),
      static_cast<std::int64_t>(58),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_023",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"R.bin", "UJPHOKLroqxcad"},
        {"T.bin", "lYvBCdMeZjfRi"},
        {"T/c.cfg", "kAMPJDYYxIpL"}
      },
      {},
      {
        {"R.bin", "UJPHOKLroqxcad"},
        {"T.bin", "lYvBCdMeZjfRi"},
        {"T/c.cfg", "kAMPJDYYxIpL"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(125u),
      static_cast<std::int64_t>(53),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_024",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"Toh/h.dat", "QEPYKrvjJ"}
      },
      {},
      {
        {"Toh/h.dat", "QEPYKrvjJ"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_025",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"Pl/ZYt/t.bin", "EQBnb"},
        {"f.dat", "DwJSaCwK"},
        {"k.bin", "BVof"},
        {"l.bin", "JLgEmaeTAO"}
      },
      {},
      {
        {"Pl/ZYt/t.bin", "EQBnb"},
        {"f.dat", "DwJSaCwK"},
        {"k.bin", "BVof"},
        {"l.bin", "JLgEmaeTAO"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(118u),
      static_cast<std::int64_t>(46),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_026",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"w.md", "kpArpFVcevvNM"}
      },
      {},
      {
        {"w.md", "kpArpFVcevvNM"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_027",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"kU/Zh/L.txt", "sukPiD"}
      },
      {},
      {
        {"kU/Zh/L.txt", "sukPiD"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_028",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"FUwi/V.md", "sXNNvRdI"},
        {"Ubry/au/T.cfg", "pypDZlhkEj"},
        {"Ui/B.dat", "PAujxjjkQszQQmca"},
        {"UpwO/GMN/E.cfg", "zpBKUGturZIY"},
        {"nvZS/JY/z.txt", "gxDPj"},
        {"yi/Jbz/t.md", "ybhKM"}
      },
      {},
      {
        {"FUwi/V.md", "sXNNvRdI"},
        {"Ubry/au/T.cfg", "pypDZlhkEj"},
        {"Ui/B.dat", "PAujxjjkQszQQmca"},
        {"UpwO/GMN/E.cfg", "zpBKUGturZIY"},
        {"nvZS/JY/z.txt", "gxDPj"},
        {"yi/Jbz/t.md", "ybhKM"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(268u),
      static_cast<std::int64_t>(148),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_029",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"Ad/sP/v.bin", "nTtlmd"},
        {"FlMw/y.txt", "gsIMdejEyN"},
        {"GZK/HMI/r.cfg", "LWjpStNWuMnzsnw"},
        {"VIhL/G.dat", "N"},
        {"s/t.md", "LwfryGZmTcp"}
      },
      {},
      {
        {"Ad/sP/v.bin", "nTtlmd"},
        {"FlMw/y.txt", "gsIMdejEyN"},
        {"GZK/HMI/r.cfg", "LWjpStNWuMnzsnw"},
        {"VIhL/G.dat", "N"},
        {"s/t.md", "LwfryGZmTcp"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(212u),
      static_cast<std::int64_t>(108),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_030",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"Hdj/pEr/y.cfg", "iDHGVLOUJConJEU"},
        {"j.dat", "tWFHZquCeJkD"},
        {"pXY/S/S.dat", "t"}
      },
      {},
      {
        {"Hdj/pEr/y.cfg", "iDHGVLOUJConJEU"},
        {"j.dat", "tWFHZquCeJkD"},
        {"pXY/S/S.dat", "t"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(133u),
      static_cast<std::int64_t>(61),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_SMALL_031",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"D/u.cfg", "wfO"},
        {"EdD/M/M.bin", "EnTE"},
        {"TJA/i.txt", "NaW"},
        {"U.dat", "bhFkTH"},
        {"W.txt", "BuDmQCI"}
      },
      {},
      {
        {"D/u.cfg", "wfO"},
        {"EdD/M/M.bin", "EnTE"},
        {"TJA/i.txt", "NaW"},
        {"U.dat", "bhFkTH"},
        {"W.txt", "BuDmQCI"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(168u),
      static_cast<std::int64_t>(80),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_000",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"DppgrQMdmuTdvRSlD.md", "dOyLeUOpPgNFrwOzbW"}
      },
      {},
      {
        {"DppgrQMdmuTdvRSlD.md", "dOyLeUOpPgNFrwOzbW"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_001",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"AhsiBMadaMuVamqdiXQtZqJio.bin", "aEWmIVbpYFOWurXnOgnrGLjNMYLmUbNoGMeBrMcMSUlalfxEghWjELuewZFhuDnnsNfIAnivT"},
        {"IzLYJwAnNnMQJWEBnGKNfGxWbhgaomcOkRs/ZNQejGYLyWiRkUfDQpHQGqtDsPYMRksVtb/HJLwYqnctcRphBiUAz.bin", "eWfuRWxautTQaHYIWXEbUtoTvBWeRwALSkqcoGyr"},
        {"JagvQSK.txt", "BBdHWaMEVMEtkOL"},
        {"LGjpbfTr/vSQbnFGjujECDoHavnqMPSIdgpTXyBQMAw/ZHrAZwkhBOKJjgNRjiTpDhpYsvXX.txt", "AvePBBcQktFvEJefLWbKKPDjOrkogfLmyy"},
        {"LipMchggYcMrCAwDH/gST.txt", "nkbAWLkYaMhIatZwLgqj"}
      },
      {},
      {
        {"AhsiBMadaMuVamqdiXQtZqJio.bin", "aEWmIVbpYFOWurXnOgnrGLjNMYLmUbNoGMeBrMcMSUlalfxEghWjELuewZFhuDnnsNfIAnivT"},
        {"IzLYJwAnNnMQJWEBnGKNfGxWbhgaomcOkRs/ZNQejGYLyWiRkUfDQpHQGqtDsPYMRksVtb/HJLwYqnctcRphBiUAz.bin", "eWfuRWxautTQaHYIWXEbUtoTvBWeRwALSkqcoGyr"},
        {"JagvQSK.txt", "BBdHWaMEVMEtkOL"},
        {"LGjpbfTr/vSQbnFGjujECDoHavnqMPSIdgpTXyBQMAw/ZHrAZwkhBOKJjgNRjiTpDhpYsvXX.txt", "AvePBBcQktFvEJefLWbKKPDjOrkogfLmyy"},
        {"LipMchggYcMrCAwDH/gST.txt", "nkbAWLkYaMhIatZwLgqj"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(651u),
      static_cast<std::int64_t>(403),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_002",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"JbEJUlzytyameYh/SFMazEmivzLpqXBBnKzG/wXcGHtSatrhQ.cfg", "dPYisBEBeTjwIdvDFujnvJcI"},
        {"LHfsKCrGcKdJMKqK.md", "ey"},
        {"NcUJppEamSBDzdLK/SDBhEiD/gCSjxFmwPhtywWYequQrbzHnEtyJYRtV.cfg", "oUbacKgUCQBmHNVeQTbiRHqxfJZwrvhtkqMCv"}
      },
      {},
      {
        {"JbEJUlzytyameYh/SFMazEmivzLpqXBBnKzG/wXcGHtSatrhQ.cfg", "dPYisBEBeTjwIdvDFujnvJcI"},
        {"LHfsKCrGcKdJMKqK.md", "ey"},
        {"NcUJppEamSBDzdLK/SDBhEiD/gCSjxFmwPhtywWYequQrbzHnEtyJYRtV.cfg", "oUbacKgUCQBmHNVeQTbiRHqxfJZwrvhtkqMCv"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(218u),
      static_cast<std::int64_t>(114),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_003",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"AdNyMAttuhOWcEKOGJHiW/FCmUvn.bin", "IxOZYsOsTfhbQjCkblFWrtoFIyMuscSflrWbUydjEAbXiKbqjPCkb"},
        {"AwRDMLXZpJSOExFoTHurdzrVeHQB.cfg", "qZWdAonJNiMZ"},
        {"CUNfabJXpSBBLNNQCbRsjNlFYfEnNXlBEcPn/YeogeJgkhErqQEvRFurcKAZXBjwnNGXK.cfg", "vXEhigQGHcRcSwtlCvUSinmEYBkhhKOebXwblENmWdeoiLVw"},
        {"Ciino.md", "jQHwkOIoqPzlsRugsTYX"},
        {"LgyTXyrkwvEKmdQxPJn/Xf/iAhZXKYmniiVyQZLnt.txt", "aBXvQWplaeNLzxqqYxPUckzISLaYpiocKJK"},
        {"UHewozOAKONKKwRPpYBW/ahiPTqwkJVzYE.txt", "fDOqXujBvWLjPJSXdp"}
      },
      {},
      {
        {"AdNyMAttuhOWcEKOGJHiW/FCmUvn.bin", "IxOZYsOsTfhbQjCkblFWrtoFIyMuscSflrWbUydjEAbXiKbqjPCkb"},
        {"AwRDMLXZpJSOExFoTHurdzrVeHQB.cfg", "qZWdAonJNiMZ"},
        {"CUNfabJXpSBBLNNQCbRsjNlFYfEnNXlBEcPn/YeogeJgkhErqQEvRFurcKAZXBjwnNGXK.cfg", "vXEhigQGHcRcSwtlCvUSinmEYBkhhKOebXwblENmWdeoiLVw"},
        {"Ciino.md", "jQHwkOIoqPzlsRugsTYX"},
        {"LgyTXyrkwvEKmdQxPJn/Xf/iAhZXKYmniiVyQZLnt.txt", "aBXvQWplaeNLzxqqYxPUckzISLaYpiocKJK"},
        {"UHewozOAKONKKwRPpYBW/ahiPTqwkJVzYE.txt", "fDOqXujBvWLjPJSXdp"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(646u),
      static_cast<std::int64_t>(398),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_004",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"ckTIODBeyRDUPfDaoueDwzNwPCgZS/lmUzxUCaSuuUUuMDGGrcUOXYmNh.txt", "aPdbgiIsPwLVSznZLSvYLywGiFolQFVVWpvJbQRRiDBgKVMyqQhqEU"},
        {"eXeXi/dRwpVzRoeAwuwdMmGZM.bin", "MFIgStIeqTaFOqzMemukomtJCDJmDGdvkxgDRneFipYiZYNqPQKPcIjnhkuzpf"}
      },
      {},
      {
        {"ckTIODBeyRDUPfDaoueDwzNwPCgZS/lmUzxUCaSuuUUuMDGGrcUOXYmNh.txt", "aPdbgiIsPwLVSznZLSvYLywGiFolQFVVWpvJbQRRiDBgKVMyqQhqEU"},
        {"eXeXi/dRwpVzRoeAwuwdMmGZM.bin", "MFIgStIeqTaFOqzMemukomtJCDJmDGdvkxgDRneFipYiZYNqPQKPcIjnhkuzpf"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(227u),
      static_cast<std::int64_t>(123),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_005",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"PesYJCQSh/zjbWTW/IeCwQaBTubGfyVl.txt", "rNSFEGuXOkdkBNzLcZysoucnRWhcanHmgzfCbRPV"}
      },
      {},
      {
        {"PesYJCQSh/zjbWTW/IeCwQaBTubGfyVl.txt", "rNSFEGuXOkdkBNzLcZysoucnRWhcanHmgzfCbRPV"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_006",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"OLqSQcaLGvZWDLJGtQkyyWNF/YPVrHAzVSXNcEpbimUrbMKweByFwVKI/DBIaMZXtKznGAGdIvdCIzoXLtMAgYxF.bin", "pbJKpXEtXSQSmvQh"},
        {"SxobIHOy/MdumhWDyWtkSgNtCSuZaxDheKILzznm/DNcEtXfgmYOJtpTsxbdieqCxJM.md", "zbPbTfTbbgGBeIzEvYtrvqGPWnxNrkPPEEkckmGJNMdG"}
      },
      {},
      {
        {"OLqSQcaLGvZWDLJGtQkyyWNF/YPVrHAzVSXNcEpbimUrbMKweByFwVKI/DBIaMZXtKznGAGdIvdCIzoXLtMAgYxF.bin", "pbJKpXEtXSQSmvQh"},
        {"SxobIHOy/MdumhWDyWtkSgNtCSuZaxDheKILzznm/DNcEtXfgmYOJtpTsxbdieqCxJM.md", "zbPbTfTbbgGBeIzEvYtrvqGPWnxNrkPPEEkckmGJNMdG"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(220u),
      static_cast<std::int64_t>(116),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_007",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"AItAYNncTRUECSQHNLePCfTpfFnWJ/aNVbQVZKNDhFfhVfiybDScF.md", "ftTDOkUzIzMXgcJxlLhZvrDbMhGMfkUsfIpE"}
      },
      {},
      {
        {"AItAYNncTRUECSQHNLePCfTpfFnWJ/aNVbQVZKNDhFfhVfiybDScF.md", "ftTDOkUzIzMXgcJxlLhZvrDbMhGMfkUsfIpE"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(56u),
      static_cast<std::int64_t>(0),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_008",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"IlAPuwMoARQdJlItN.dat", "Atw"},
        {"OILBTEmwYwkHsJdFAnEr.bin", "oAPwcaZhSZpCGVBZWSFXjIUfTo"},
        {"WJFrBSZWTwTRhdnTMT.bin", "abJPxNGBahHvGWfShiACwsgfBwwqibD"},
        {"XMKvtORwzkVDyWyQDs/gWVLoGAKOEpXxTn.dat", "nHsTkXrxlatWXuO"}
      },
      {},
      {
        {"IlAPuwMoARQdJlItN.dat", "Atw"},
        {"OILBTEmwYwkHsJdFAnEr.bin", "oAPwcaZhSZpCGVBZWSFXjIUfTo"},
        {"WJFrBSZWTwTRhdnTMT.bin", "abJPxNGBahHvGWfShiACwsgfBwwqibD"},
        {"XMKvtORwzkVDyWyQDs/gWVLoGAKOEpXxTn.dat", "nHsTkXrxlatWXuO"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(271u),
      static_cast<std::int64_t>(151),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_009",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"COugefKliWgayqz/ZyxvboUzdYWzkIiNZAwh.md", "qHLvqQzAMeyFUCfaDiHyjsHBADKGfwmOZmobmUIFhHOxpqJiUGZLojViTMFtpNANfqDyRbftZvGF"},
        {"CtjbKGLuPbaLjOPTsmqo.cfg", "MusjVYyODHxcmJY"},
        {"GNFdzJIjhzQxyBvHogytXVXVdKE/kXO.md", "GxPvFpSLlV"},
        {"LRbcmuMWURaOZpHuWDIFUg.txt", "ETTcUvfVDuBoBNWbLWxoJoxdGV"},
        {"OCJGD/JpOm.cfg", "AURLGlnWsyROzRncMYmhWfDHnSEtqTyVXdSucMPEsNHNpJxOfwMfdbIPJgjMiXRPSaSNwMoRUH"},
        {"OZdtzpbxVn.dat", "DuNMsgkedAKxxILWGzYBqzVyBbXaZOzSWhfdgraLYjMHTA"}
      },
      {},
      {
        {"COugefKliWgayqz/ZyxvboUzdYWzkIiNZAwh.md", "qHLvqQzAMeyFUCfaDiHyjsHBADKGfwmOZmobmUIFhHOxpqJiUGZLojViTMFtpNANfqDyRbftZvGF"},
        {"CtjbKGLuPbaLjOPTsmqo.cfg", "MusjVYyODHxcmJY"},
        {"GNFdzJIjhzQxyBvHogytXVXVdKE/kXO.md", "GxPvFpSLlV"},
        {"LRbcmuMWURaOZpHuWDIFUg.txt", "ETTcUvfVDuBoBNWbLWxoJoxdGV"},
        {"OCJGD/JpOm.cfg", "AURLGlnWsyROzRncMYmhWfDHnSEtqTyVXdSucMPEsNHNpJxOfwMfdbIPJgjMiXRPSaSNwMoRUH"},
        {"OZdtzpbxVn.dat", "DuNMsgkedAKxxILWGzYBqzVyBbXaZOzSWhfdgraLYjMHTA"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(610u),
      static_cast<std::int64_t>(378),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_010",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"IKWSriWXvJBJPHbvXw.txt", "kMqaCXjCQOhEyVoVHdkzwqbJLqnYoabFpMfbkjvukJoKFPcvUzBrZ"},
        {"RKOYPKpZvhjlEJAvdVgsktuQOgxPeuds/iUpevgxPFbeAdnpBztmQoXYYuJrT.cfg", "gqbsbCtbVOodCMdqvYuqeRMMABhiUhBNvYeYBS"},
        {"RpWYJFXYhCsO.bin", "pElKyVjyVhehIItrDcalYnSyapVxaPcrMgs"}
      },
      {},
      {
        {"IKWSriWXvJBJPHbvXw.txt", "kMqaCXjCQOhEyVoVHdkzwqbJLqnYoabFpMfbkjvukJoKFPcvUzBrZ"},
        {"RKOYPKpZvhjlEJAvdVgsktuQOgxPeuds/iUpevgxPFbeAdnpBztmQoXYYuJrT.cfg", "gqbsbCtbVOodCMdqvYuqeRMMABhiUhBNvYeYBS"},
        {"RpWYJFXYhCsO.bin", "pElKyVjyVhehIItrDcalYnSyapVxaPcrMgs"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(346u),
      static_cast<std::int64_t>(194),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_011",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"AarQcZcxivKSxCiaOToAsiY.txt", "ihVcPqSXuPjowperTfIRy"},
        {"KBJeB/oFqZNclRyXF.bin", "AVPOhRKhWeZvgCuncsZserBpjSekoiXVnMXieQddIVMoUIMwdh"},
        {"RNKuFjdJHpfRu.md", "krCwaJavAyiUERNlrkgbEsZTUwq"},
        {"UOxabIhCpbWEinyvFZgZ/VBCYNUIkLJCyCDMmQgptSvn/ovimmNVGBaOVyrlMwiyHicFvPcWg.dat", "aPHZCJIjYKNAzZPBrvlQMscqMp"},
        {"Wf.dat", "ruzRLYcSnBTthRrtXBSiZZbSsSjGdFoLAMDFduRgWttcteZWJrdTHqXPeUwCZH"}
      },
      {},
      {
        {"AarQcZcxivKSxCiaOToAsiY.txt", "ihVcPqSXuPjowperTfIRy"},
        {"KBJeB/oFqZNclRyXF.bin", "AVPOhRKhWeZvgCuncsZserBpjSekoiXVnMXieQddIVMoUIMwdh"},
        {"RNKuFjdJHpfRu.md", "krCwaJavAyiUERNlrkgbEsZTUwq"},
        {"UOxabIhCpbWEinyvFZgZ/VBCYNUIkLJCyCDMmQgptSvn/ovimmNVGBaOVyrlMwiyHicFvPcWg.dat", "aPHZCJIjYKNAzZPBrvlQMscqMp"},
        {"Wf.dat", "ruzRLYcSnBTthRrtXBSiZZbSsSjGdFoLAMDFduRgWttcteZWJrdTHqXPeUwCZH"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(497u),
      static_cast<std::int64_t>(297),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_012",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"IkCgrRsWBbyltC.md", "uBbrKXBctTxDLqCrZxuoTBLAPlffqreZSNNtTXZMisHmLXQHrILtGuwxCIdbIxlFqmAQMnaQRmof"},
        {"J/vWHmmyymeMEBc.cfg", "oYTLnAqrzgXYvCTHcLvANSxQnbWLFtgHGMOA"},
        {"LF.md", "nqrPmVHPgrxBNGTLJDiaunAhuHWjJJWhMOCHVRctqEhdSLDvPvMxkhIxeBUAVhdsUoxMYnL"},
        {"QhyulWkacvBsxYAxrO.txt", "IUjDtRmejegDRIMxDfJKwthGHJxBHBOehXurWpxomlgdoemJhBh"}
      },
      {},
      {
        {"IkCgrRsWBbyltC.md", "uBbrKXBctTxDLqCrZxuoTBLAPlffqreZSNNtTXZMisHmLXQHrILtGuwxCIdbIxlFqmAQMnaQRmof"},
        {"J/vWHmmyymeMEBc.cfg", "oYTLnAqrzgXYvCTHcLvANSxQnbWLFtgHGMOA"},
        {"LF.md", "nqrPmVHPgrxBNGTLJDiaunAhuHWjJJWhMOCHVRctqEhdSLDvPvMxkhIxeBUAVhdsUoxMYnL"},
        {"QhyulWkacvBsxYAxrO.txt", "IUjDtRmejegDRIMxDfJKwthGHJxBHBOehXurWpxomlgdoemJhBh"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(416u),
      static_cast<std::int64_t>(248),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_013",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"DmxCW/vqvRpcsrodGaBUpgHJYAhHKwSnPorlao.md", "KPSMABaBGVFwkICpiG"},
        {"GGpmVLJhhX/mLS.cfg", "kIbwtmvsmRCwPmEwpMKbnnHgNxwgssJWWQbaOmLVdQzjHRvBLl"},
        {"IpGmduNuuNxbcyvSkhSUOUQjUIqW/hqgp/zfkqNyifMwIHoHqiwajvoLVRlfGHH.cfg", "LsQTVcOvDWBIIXDKNKWDkPNemXAkFIszBLkWRvEiklo"},
        {"QbQ/XjeiMcXBWcMLOxvOn.dat", "RcVzBWOZgLEgDqBFShQcevRM"},
        {"RluHzTDQahBYmPaFSSuIZ.bin", "oVFtBhatmH"},
        {"VOdRiCGrEkAACjRVhxNpackQiFSJdAPB.md", "dzXQhAsSsjMWhYVbSWrBplZTGDVOJGMlZWTLUlVHKCZDYnIOMWSGlC"}
      },
      {},
      {
        {"DmxCW/vqvRpcsrodGaBUpgHJYAhHKwSnPorlao.md", "KPSMABaBGVFwkICpiG"},
        {"GGpmVLJhhX/mLS.cfg", "kIbwtmvsmRCwPmEwpMKbnnHgNxwgssJWWQbaOmLVdQzjHRvBLl"},
        {"IpGmduNuuNxbcyvSkhSUOUQjUIqW/hqgp/zfkqNyifMwIHoHqiwajvoLVRlfGHH.cfg", "LsQTVcOvDWBIIXDKNKWDkPNemXAkFIszBLkWRvEiklo"},
        {"QbQ/XjeiMcXBWcMLOxvOn.dat", "RcVzBWOZgLEgDqBFShQcevRM"},
        {"RluHzTDQahBYmPaFSSuIZ.bin", "oVFtBhatmH"},
        {"VOdRiCGrEkAACjRVhxNpackQiFSJdAPB.md", "dzXQhAsSsjMWhYVbSWrBplZTGDVOJGMlZWTLUlVHKCZDYnIOMWSGlC"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(593u),
      static_cast<std::int64_t>(361),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_014",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"IxULVOfOvZuyHOZcAmsHBOYu/pe.md", "uHhNSVcTRYarXTCIGohJDBO"},
        {"LyZojHcGQXuTNqhdSBhxiHAtoRVXekOfTZk/SUIMOPxQoFyjubSwn.cfg", "OzytOpHkGcGxehYxhPTbAEQhGOOBQIkxtmJjPiDQMNrheZGSFiRkqlzOMckcfKzOnKrQjay"},
        {"S.txt", "HSCtwxhDppFSEccLlWXeDBeZCdBuWSswtwj"}
      },
      {},
      {
        {"IxULVOfOvZuyHOZcAmsHBOYu/pe.md", "uHhNSVcTRYarXTCIGohJDBO"},
        {"LyZojHcGQXuTNqhdSBhxiHAtoRVXekOfTZk/SUIMOPxQoFyjubSwn.cfg", "OzytOpHkGcGxehYxhPTbAEQhGOOBQIkxtmJjPiDQMNrheZGSFiRkqlzOMckcfKzOnKrQjay"},
        {"S.txt", "HSCtwxhDppFSEccLlWXeDBeZCdBuWSswtwj"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(349u),
      static_cast<std::int64_t>(197),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingArchives_MEDIUM_015",
      "unbundle",
      "eof_oob",
      "UNP_EOF_001",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"AirdBMBPaVgWAXQavB.bin", "hcBuclWKqx"},
        {"EvAcsOaQyQsxWhadelAMq/sJSqKnZ/Mi.bin", "ECirJXtHJEuObORebDGFQlgQ"},
        {"FXPQfImeIrBrlBbDI/pMgWlgT.md", "XoPgykaqQsVFhdvwhuFcoK"},
        {"FhbtxsfjUyiCfjsQUXqsmUie/jBfXVLIhKYGuOaflwuRiNdNYa.bin", "gBQZaEKTvKdGEKBusxRsLjlQl"}
      },
      {},
      {
        {"AirdBMBPaVgWAXQavB.bin", "hcBuclWKqx"},
        {"EvAcsOaQyQsxWhadelAMq/sJSqKnZ/Mi.bin", "ECirJXtHJEuObORebDGFQlgQ"},
        {"FXPQfImeIrBrlBbDI/pMgWlgT.md", "XoPgykaqQsVFhdvwhuFcoK"},
        {"FhbtxsfjUyiCfjsQUXqsmUie/jBfXVLIhKYGuOaflwuRiNdNYa.bin", "gBQZaEKTvKdGEKBusxRsLjlQl"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(302u),
      static_cast<std::int64_t>(166),
      { 0x00, 0x00 },
      { static_cast<std::uint32_t>(1u) },
      {},
      "EOF out-of-bounds archive tail case, target type ignored for EOF source mode."
    }
};

bool ValidateCaseOutcome(const GeneratedFenceCaseData& pCase,
                         const FenceRoundTripOutcome& pOutcome,
                         std::string& pError) {
  if (!pOutcome.mSucceeded) {
    pError = pOutcome.mFailureMessage;
    return false;
  }

  if (!pCase.mExpectedErrorCode.empty()) {
    const bool aHasExpectedError =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, pCase.mExpectedErrorCode) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, pCase.mExpectedErrorCode) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, pCase.mExpectedErrorCode);
    if (!aHasExpectedError) {
      pError = "missing expected error code: " + pCase.mExpectedErrorCode;
      return false;
    }
  }

  if (!pCase.mExpectedFenceFlag.empty()) {
    const bool aHasFenceFlag =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, pCase.mExpectedFenceFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, pCase.mExpectedFenceFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, pCase.mExpectedFenceFlag);
    if (!aHasFenceFlag) {
      pError = "missing expected fence flag: " + pCase.mExpectedFenceFlag;
      return false;
    }
  }

  for (const std::string& aForbiddenFlag : pCase.mForbiddenFenceFlags) {
    const bool aHasForbiddenFlag =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, aForbiddenFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, aForbiddenFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, aForbiddenFlag);
    if (aHasForbiddenFlag) {
      pError = "encountered forbidden fence flag: " + aForbiddenFlag;
      return false;
    }
  }

  return true;
}

}  // namespace

int main() {
  for (const GeneratedFenceCaseData& aCase : kCases) {
    FenceRoundTripSpec aSpec;
    aSpec.mCaseName = aCase.mCaseId;
    aSpec.mOriginalFiles = aCase.mInputFiles;
    aSpec.mOriginalEmptyDirectories = aCase.mInputEmptyDirs;
    aSpec.mRecoverableFiles = aCase.mRecoverableFiles;
    aSpec.mArchiveBlockCount = aCase.mArchiveBlockCount;
    aSpec.mExpectMutatedUnbundleFailure = (aCase.mFlow == "unbundle");
    aSpec.mExpectedUnbundleErrorCode = (aCase.mFlow == "unbundle") ? aCase.mExpectedErrorCode : "";
    aSpec.mRunRecoverAfterMutation = (aCase.mFlow == "recover");
    aSpec.mRequireRecoverTreeMatch = false;

    const bool aSupportsPayloadMutation =
        (aCase.mFieldKind == "file_name_length") ||
        (aCase.mFieldKind == "file_content_length") ||
        (aCase.mFieldKind == "directory_name_length") ||
        (aCase.mFieldKind == "eof_gar");
    if (aSupportsPayloadMutation && aCase.mMutationPayloadLogicalOffset >= 0) {
      GenericArchiveDataMutation aMutation;
      aMutation.mArchiveIndex = aCase.mArchiveIndex;
      aMutation.mPayloadLogicalOffset = static_cast<std::size_t>(aCase.mMutationPayloadLogicalOffset);
      aMutation.mBytes = aCase.mMutationBytes;
      aSpec.mMutation.mArchiveDataMutations.push_back(aMutation);
    } else {
      GenericArchiveByteMutation aMutation;
      aMutation.mArchiveIndex = aCase.mArchiveIndex;
      aMutation.mFileOffset = aCase.mMutationFileOffset;
      aMutation.mBytes = aCase.mMutationBytes;
      aSpec.mMutation.mArchiveByteMutations.push_back(aMutation);
    }
    aSpec.mMutation.mArchiveSetMutation.mCreateArchiveIndices = aCase.mCreateArchiveIndices;
    aSpec.mMutation.mArchiveSetMutation.mRemoveArchiveIndices = aCase.mRemoveArchiveIndices;

    const FenceRoundTripOutcome aOutcome = peanutbutter::testing::ExecuteFenceTestRoundTrip(aSpec);
    std::string aError;
    if (!ValidateCaseOutcome(aCase, aOutcome, aError)) {
      std::cerr << "[FAIL] " << aCase.mCaseId << " failed: " << aError << "\n";
      if (!aCase.mFailurePointComment.empty()) {
        std::cerr << "[INFO] " << aCase.mFailurePointComment << "\n";
      }
      std::cerr << aOutcome.mCollectedLogs;
      return 1;
    }
  }

  std::cout << "[PASS] generated fence suite passed for " << kCases.size() << " case(s).\n";
  return 0;
}
