// Generated by test_case_gen_executor_cpp_code.py from test_cases_all.json
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <string>
#include <vector>

#include "FormatConstants.hpp"
#include "Test_Execute_FenceRoundTrip.hpp"
#include "Test_GeneratedFenceCaseData.hpp"
#include "Test_Utils.hpp"

namespace {

using peanutbutter::testing::FenceRoundTripOutcome;
using peanutbutter::testing::FenceRoundTripSpec;
using peanutbutter::testing::GeneratedFenceCaseData;
using peanutbutter::testing::GenericArchiveDataMutation;
using peanutbutter::testing::GenericArchiveByteMutation;

const std::vector<GeneratedFenceCaseData> kCases = {
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_000",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"D.txt", "alZEDsM"},
        {"P.md", "ziBoaxHykyXPqKk"},
        {"XDhS/H.md", "tWow"},
        {"Z.dat", "uijdkujcm"},
        {"f.md", "tGlXFKrnwuaYacUQ"},
        {"o.dat", "BwJPuV"}
      },
      {},
      {
        {"D.txt", "alZEDsM"},
        {"P.md", "ziBoaxHykyXPqKk"},
        {"XDhS/H.md", "tWow"},
        {"Z.dat", "uijdkujcm"},
        {"f.md", "tGlXFKrnwuaYacUQ"},
        {"o.dat", "BwJPuV"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(259u),
      static_cast<std::int64_t>(139),
      { 0x5e, 0x1c, 0x58, 0x9d, 0x37, 0x75, 0xe2, 0xc0, 0x05, 0x38, 0x1b, 0x5c, 0xab, 0x4f, 0x80, 0xdb, 0x98, 0x5f, 0x0d, 0x53, 0xbf },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_001",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"SVtS/dyG/o.txt", "RsfFoniuYTchf"},
        {"Wvgv/V.dat", "sX"},
        {"m/e.md", "sk"},
        {"q.txt", "CMKhxojUXIyTlpYg"}
      },
      {},
      {
        {"SVtS/dyG/o.txt", "RsfFoniuYTchf"},
        {"Wvgv/V.dat", "sX"},
        {"m/e.md", "sk"},
        {"q.txt", "CMKhxojUXIyTlpYg"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(206u),
      static_cast<std::int64_t>(102),
      { 0x6c, 0x63, 0x43, 0x6d, 0x9c, 0xf2, 0x73, 0xf8, 0x31, 0xc3, 0x5f, 0x67, 0x30, 0x41, 0xc0, 0x65, 0xb0, 0x9e, 0x87, 0x45, 0x61, 0x6e, 0xf3, 0x3c, 0xe0, 0x89 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_002",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"O.cfg", "RjKxJ"},
        {"pJp/N.dat", "Gipva"},
        {"qG/e.txt", "hpPRrkUzIrrBugv"},
        {"wjSs/z.md", "SFQXYFQZdrDAcop"}
      },
      {},
      {
        {"O.cfg", "RjKxJ"},
        {"pJp/N.dat", "Gipva"},
        {"qG/e.txt", "hpPRrkUzIrrBugv"},
        {"wjSs/z.md", "SFQXYFQZdrDAcop"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(209u),
      static_cast<std::int64_t>(105),
      { 0xce, 0x80, 0xcb, 0x7f, 0x3a, 0x37, 0xb1, 0xfb, 0x84, 0x99, 0xa5, 0x17, 0x72, 0x0e, 0x2f, 0xfd, 0x6d, 0x2b, 0x31, 0xfa, 0xc0, 0xd7, 0x19 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_003",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"M.md", "gyRWLp"}
      },
      {},
      {
        {"M.md", "gyRWLp"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(76u),
      static_cast<std::int64_t>(20),
      { 0x18, 0x97, 0xc9, 0x1b, 0x2a, 0xac, 0x3f, 0x81, 0x9f, 0xba, 0xe0, 0xfa },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_004",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"I.md", "uMFBFDUBvcqek"},
        {"T.txt", "ApfPL"},
        {"r.txt", "mkQiGTMUDgNZpI"},
        {"xCu/ZxSD/f.bin", "HDsiwTUovFCiAM"}
      },
      {},
      {
        {"I.md", "uMFBFDUBvcqek"},
        {"T.txt", "ApfPL"},
        {"r.txt", "mkQiGTMUDgNZpI"},
        {"xCu/ZxSD/f.bin", "HDsiwTUovFCiAM"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(212u),
      static_cast<std::int64_t>(108),
      { 0xfb, 0x39, 0x20, 0x9c, 0x9a, 0xc3, 0x38, 0x1e, 0x13, 0x75, 0x2e, 0x56, 0xc3, 0x1c, 0x35, 0xa1, 0xcd, 0x05, 0xb2, 0xbc },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_005",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"mk/d.txt", "mhsKf"}
      },
      {},
      {
        {"mk/d.txt", "mhsKf"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(79u),
      static_cast<std::int64_t>(23),
      { 0x1c, 0x72, 0xa2, 0xd0, 0xf4, 0xab, 0x05, 0xbb, 0x4e },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_006",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"B.cfg", "ucRSw"},
        {"J.bin", "KNSuhQcG"},
        {"l/d.txt", "wiSWXZIvnFmePU"}
      },
      {},
      {
        {"B.cfg", "ucRSw"},
        {"J.bin", "KNSuhQcG"},
        {"l/d.txt", "wiSWXZIvnFmePU"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(158u),
      static_cast<std::int64_t>(70),
      { 0xa9, 0xee, 0xeb, 0x49, 0xe0, 0x76, 0x65, 0xe7, 0x30, 0x8b, 0x3b, 0x7a, 0x91, 0x57, 0x5b, 0xbf, 0x97, 0x4d, 0x9b, 0x5b, 0x11, 0x8a, 0xe4, 0x30, 0xcd, 0xcb },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_007",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"BUt/k.bin", "vqhFiN"}
      },
      {},
      {
        {"BUt/k.bin", "vqhFiN"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(81u),
      static_cast<std::int64_t>(25),
      { 0xf2, 0xc4, 0x4e, 0xb2, 0x9e, 0xfe, 0x1c },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_008",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"AU/wNFr/T.md", "lbhGzfTBSNhSL"},
        {"CfCM/R.dat", "rymVMcwf"},
        {"HlRr/u.cfg", "r"},
        {"P.bin", "ArZGFPy"},
        {"aoZ/E/O.dat", "sL"}
      },
      {},
      {
        {"AU/wNFr/T.md", "lbhGzfTBSNhSL"},
        {"CfCM/R.dat", "rymVMcwf"},
        {"HlRr/u.cfg", "r"},
        {"P.bin", "ArZGFPy"},
        {"aoZ/E/O.dat", "sL"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(225u),
      static_cast<std::int64_t>(121),
      { 0xc5, 0x72, 0x07, 0xf3, 0x52, 0x2d, 0xdc },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_009",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"Ex/C.dat", "F"},
        {"YE/Q.bin", "bWYVnWH"},
        {"YfzT/y.cfg", "lQrwwaVxQz"},
        {"a.md", "xqW"},
        {"g.cfg", "R"},
        {"nQwz/cywL/K.bin", "lIVxyUDpjBc"}
      },
      {},
      {
        {"Ex/C.dat", "F"},
        {"YE/Q.bin", "bWYVnWH"},
        {"YfzT/y.cfg", "lQrwwaVxQz"},
        {"a.md", "xqW"},
        {"g.cfg", "R"},
        {"nQwz/cywL/K.bin", "lIVxyUDpjBc"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(253u),
      static_cast<std::int64_t>(133),
      { 0xed, 0x4a, 0xac, 0xce, 0xd2, 0xef, 0x23, 0x18, 0xc6, 0x93, 0x10, 0x23, 0xda, 0xd3, 0x81, 0xd4, 0x4d, 0xab, 0x44, 0x88, 0x24, 0x08, 0x10, 0x22, 0x75, 0x27, 0x30 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_010",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"AAUS/YZ/h.dat", "GckSlpGiJgwbwr"},
        {"B.dat", "gFFpaQTnOnibZeZb"},
        {"avx/mZ/X.txt", "XOCjhMXKvMTyKK"},
        {"d.dat", "DgSJAkngJhpsCTV"},
        {"h/p.dat", "uuShQqhir"}
      },
      {},
      {
        {"AAUS/YZ/h.dat", "GckSlpGiJgwbwr"},
        {"B.dat", "gFFpaQTnOnibZeZb"},
        {"avx/mZ/X.txt", "XOCjhMXKvMTyKK"},
        {"d.dat", "DgSJAkngJhpsCTV"},
        {"h/p.dat", "uuShQqhir"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(272u),
      static_cast<std::int64_t>(152),
      { 0xfb, 0xed, 0xe0, 0x84, 0x97, 0xfe, 0x3c, 0x25 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_011",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"C/y.txt", "Tpucm"},
        {"P.txt", "XZIyQTBy"},
        {"z.dat", "xTqNc"}
      },
      {},
      {
        {"C/y.txt", "Tpucm"},
        {"P.txt", "XZIyQTBy"},
        {"z.dat", "xTqNc"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(133u),
      static_cast<std::int64_t>(61),
      { 0x5b, 0xc0, 0x34 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_012",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"e/Vip/O.bin", "LPML"}
      },
      {},
      {
        {"e/Vip/O.bin", "LPML"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(81u),
      static_cast<std::int64_t>(25),
      { 0xb0, 0xae, 0xe7, 0x60, 0x38, 0x68, 0xb0 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_013",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"J.cfg", "GKjFIVDSwCHrUPPm"},
        {"jI/M.bin", "LBEHp"},
        {"uyd/Np/S.md", "BoJS"}
      },
      {},
      {
        {"J.cfg", "GKjFIVDSwCHrUPPm"},
        {"jI/M.bin", "LBEHp"},
        {"uyd/Np/S.md", "BoJS"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(163u),
      static_cast<std::int64_t>(75),
      { 0xaa, 0xd9, 0xc3, 0xb5, 0x86, 0xa3, 0x1e, 0xca, 0x76, 0x41, 0x80, 0xa7, 0x51, 0x85, 0xa1, 0xfb, 0xcc, 0xf9, 0x64, 0x3d, 0x39 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_014",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"ke/N/j.txt", "GOKMLHMfonJh"}
      },
      {},
      {
        {"ke/N/j.txt", "GOKMLHMfonJh"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(104u),
      static_cast<std::int64_t>(32),
      { 0xd4, 0x27, 0xd8, 0x85, 0x83, 0x13, 0x5b, 0x9a, 0xcf, 0xf0, 0x04, 0x8a, 0x3a, 0x49, 0x0d, 0x88, 0x20, 0x83, 0xd8, 0xa2, 0x7d, 0x2b, 0xce, 0x8a, 0x8f, 0xec, 0x14, 0xe3, 0xd2, 0x4e, 0x8f, 0xeb },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_015",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"Q/hR/u.bin", "XBxpyI"}
      },
      {},
      {
        {"Q/hR/u.bin", "XBxpyI"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(82u),
      static_cast<std::int64_t>(26),
      { 0xc9, 0xdd, 0x67, 0x63, 0x2a, 0x0a },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_016",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"eex/u/a.dat", "UaaiJnESWudihGK"}
      },
      {},
      {
        {"eex/u/a.dat", "UaaiJnESWudihGK"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(108u),
      static_cast<std::int64_t>(36),
      { 0x78, 0xf4, 0x67, 0x5c, 0xf2, 0x70, 0x69, 0x89, 0x3a, 0x0d, 0xde, 0xcf, 0x1d, 0x41, 0xc6, 0x84, 0x03, 0x81, 0xdd, 0xd2, 0x95, 0x9e, 0xfb, 0x0f, 0xf6, 0x14, 0x29, 0xf6 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_017",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"L.bin", "PCGnOBwNKM"}
      },
      {},
      {
        {"L.bin", "PCGnOBwNKM"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(81u),
      static_cast<std::int64_t>(25),
      { 0xcf, 0x88, 0x05, 0x80, 0xe0, 0x9b, 0xb0 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_018",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"BNQ/R.dat", "GCdgIOKXOdusxoE"},
        {"Y.cfg", "huzjQWfrVX"},
        {"p.bin", "GkrKAZOJP"}
      },
      {},
      {
        {"BNQ/R.dat", "GCdgIOKXOdusxoE"},
        {"Y.cfg", "huzjQWfrVX"},
        {"p.bin", "GkrKAZOJP"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(167u),
      static_cast<std::int64_t>(79),
      { 0x15, 0x6a, 0xa2, 0x84, 0x42, 0x1c, 0x7e, 0xb3, 0x9d, 0xf1, 0xdf, 0x47, 0x71, 0xbe, 0x37, 0x23, 0x47 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_019",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"A.cfg", "QIDFQDBvsjOglJF"},
        {"DkbV/U.bin", "EVNzEwP"},
        {"T.txt", "brjGxtsaNmkPD"},
        {"Za/Vs/T.bin", "KamwMf"}
      },
      {},
      {
        {"A.cfg", "QIDFQDBvsjOglJF"},
        {"DkbV/U.bin", "EVNzEwP"},
        {"T.txt", "brjGxtsaNmkPD"},
        {"Za/Vs/T.bin", "KamwMf"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(210u),
      static_cast<std::int64_t>(106),
      { 0xc2, 0x55, 0x4b, 0x1b, 0x96, 0x91, 0x71, 0xa5, 0xb2, 0xf8, 0x74, 0xfa, 0x3c, 0xbf, 0xcf, 0xd5, 0xd4, 0x63, 0x5a, 0x6e, 0x31, 0xe7 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_020",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"QqA/T.cfg", "AClJpqeJJQVDT"}
      },
      {},
      {
        {"QqA/T.cfg", "AClJpqeJJQVDT"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(104u),
      static_cast<std::int64_t>(32),
      { 0xe8, 0xb3, 0xde, 0xce, 0x2b, 0x9f, 0xf2, 0xa2, 0x47, 0x3d, 0x6a, 0xef, 0x8e, 0xbf, 0xf1, 0x1d, 0xd4, 0x42, 0xb6, 0x35, 0x76, 0xf6, 0x2b, 0x72, 0x55, 0x79, 0x39, 0xa4, 0x73, 0x20, 0x4c, 0x43 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_021",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"ZPq/A.txt", "vOmTqJH"},
        {"fNls/N/v.txt", "fxcGaV"},
        {"w.md", "pWH"}
      },
      {},
      {
        {"ZPq/A.txt", "vOmTqJH"},
        {"fNls/N/v.txt", "fxcGaV"},
        {"w.md", "pWH"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(155u),
      static_cast<std::int64_t>(67),
      { 0x4a, 0xe9, 0xb9, 0x1a, 0x49, 0xe8, 0x42, 0x9a, 0x69, 0x99, 0xba, 0x8f, 0xf4, 0x49, 0xda, 0x04, 0x28, 0xfe, 0x35, 0xbb, 0x0d, 0x8f, 0x7e, 0xab, 0x5e, 0x82, 0xf9, 0x1b, 0x5b },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_022",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"Agi/H.dat", "AwgzUQEmdyhApOzT"},
        {"Eg/K.txt", "HpueVAxvXvBPbq"},
        {"H.dat", "YdRwSIydbeHhyj"},
        {"X.txt", "pjcBIkzgYTdAvh"},
        {"YFT/LTh/Y.txt", "dtWjucpMp"},
        {"uoB/P/m.bin", "RoF"}
      },
      {},
      {
        {"Agi/H.dat", "AwgzUQEmdyhApOzT"},
        {"Eg/K.txt", "HpueVAxvXvBPbq"},
        {"H.dat", "YdRwSIydbeHhyj"},
        {"X.txt", "pjcBIkzgYTdAvh"},
        {"YFT/LTh/Y.txt", "dtWjucpMp"},
        {"uoB/P/m.bin", "RoF"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(307u),
      static_cast<std::int64_t>(171),
      { 0x1f, 0x8a, 0xb5, 0x8b, 0xa0, 0xf9, 0xe0, 0x75, 0xee, 0xc9, 0xeb, 0x1d, 0x40, 0x39, 0x64, 0x82, 0x77, 0x1f, 0xe6, 0xa7, 0xa5 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_SMALL_023",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"D.cfg", "lRuMexoxZWMHNPTT"},
        {"puhx/Qhx/u.bin", "HGmIzMMABoyu"},
        {"q.bin", "HHKHmRXycV"},
        {"s.md", "gqBd"}
      },
      {},
      {
        {"D.cfg", "lRuMexoxZWMHNPTT"},
        {"puhx/Qhx/u.bin", "HGmIzMMABoyu"},
        {"q.bin", "HHKHmRXycV"},
        {"s.md", "gqBd"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(208u),
      static_cast<std::int64_t>(104),
      { 0x0c, 0x17, 0xbe, 0x77, 0x83, 0xec, 0x3a, 0xdc, 0xc7, 0x80, 0xf7, 0x43, 0xcf, 0xc8, 0xc5, 0x73, 0xdb, 0x82, 0xb6, 0x7f, 0x4d, 0xb1, 0xc6, 0x55 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_000",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"AsqIWhupRvFAHDyabHDbGw/jXfDmIULIDs.cfg", "iOYRLNXpvgdiNWFVrapRLxUkFYpUfTGmclcOAqhpYdYCZCqyyXdhTgFEjVYbAAix"},
        {"FbVGhHfMkRUdhXDGcvcDcQhDMipDlkh/YFZRTLqQFLcNyXeO.bin", "gZEAwkhtwSgJeCQWIHYAvrkEAmmbBVhcHnGQwkeeWihYOloXJMTYCDrZWXLnGfPHojHQInvzY"},
        {"QAqgekGrlTOaGfVJsBpntaunUVEtHbEd/YxCmNckjMTsUJgiywZiIYEzuOeNQ/HSOUBbCQjdFMqNQisSbhQwMg.bin", "PynuCeYVWXWTfJvPlnIbeAwIGihOyYGHJQWsraWVaZMeaBPQeoQDBZ"},
        {"QtoOMDfYrNtalgOVaphBXQqpgjXRtUK/KbVqsPJtPDkEvXrAiUtd.dat", "hxrmXmtQRFThFzqGOVnTuftwH"},
        {"TujWRMcj.cfg", "MbfoEqkvVQSAifaauGInaeLqdDRsuxabwiVbHQJjHfBylSYiPpeRPaApyNY"},
        {"WTzIgJQRgyCsWmn/LOkdUTAqSlRL/CfPbUSYYPve.txt", "HSxkAFlbZkosMGsfAZrjALvBnOlsupqHQWYqdXPqriLQYcIgiqjeYrfQYztAT"},
        {"iVSXNATAVwjwEyCHWQgSMsgPjEQ/BlVzpVBavWcaUyy/CaAFRSLqMlbMdLocuzWLtPrw.md", "KENxXsZgoqtRdXnbRPHyoYfdwJHlPERGavOgXwQRJNmXkylrcGacjsCGUHwYeLfJ"},
        {"mZ/mKpeuRqRtPM.txt", "dpRjdDGbJxPoYYpSiDfJl"},
        {"mtSgmGUWfUrgevJwDubdohIywOXTLOYsgy/SnIsizWDCgqroLMhnRwvqrXed.md", "qgbIeQdEhpUTAewoohqpkSiHsrxwTKsSfcINjrLFdWBJpVSdXkB"},
        {"zLOxzSZfqzfZjVLuqiELGoOXMqIX/MKacfeUKaFMOwdCWuEtnfPc/pxTkFOVavoQFDnMXsFkErCmUah.bin", "oxZzuuNrTbwgnBdlnmncYFfAMcTCssdKnIJsHGDzvDnlVISDaftEsMhbsSVNmAIDGFe"}
      },
      {},
      {
        {"AsqIWhupRvFAHDyabHDbGw/jXfDmIULIDs.cfg", "iOYRLNXpvgdiNWFVrapRLxUkFYpUfTGmclcOAqhpYdYCZCqyyXdhTgFEjVYbAAix"},
        {"FbVGhHfMkRUdhXDGcvcDcQhDMipDlkh/YFZRTLqQFLcNyXeO.bin", "gZEAwkhtwSgJeCQWIHYAvrkEAmmbBVhcHnGQwkeeWihYOloXJMTYCDrZWXLnGfPHojHQInvzY"},
        {"QAqgekGrlTOaGfVJsBpntaunUVEtHbEd/YxCmNckjMTsUJgiywZiIYEzuOeNQ/HSOUBbCQjdFMqNQisSbhQwMg.bin", "PynuCeYVWXWTfJvPlnIbeAwIGihOyYGHJQWsraWVaZMeaBPQeoQDBZ"},
        {"QtoOMDfYrNtalgOVaphBXQqpgjXRtUK/KbVqsPJtPDkEvXrAiUtd.dat", "hxrmXmtQRFThFzqGOVnTuftwH"},
        {"TujWRMcj.cfg", "MbfoEqkvVQSAifaauGInaeLqdDRsuxabwiVbHQJjHfBylSYiPpeRPaApyNY"},
        {"WTzIgJQRgyCsWmn/LOkdUTAqSlRL/CfPbUSYYPve.txt", "HSxkAFlbZkosMGsfAZrjALvBnOlsupqHQWYqdXPqriLQYcIgiqjeYrfQYztAT"},
        {"iVSXNATAVwjwEyCHWQgSMsgPjEQ/BlVzpVBavWcaUyy/CaAFRSLqMlbMdLocuzWLtPrw.md", "KENxXsZgoqtRdXnbRPHyoYfdwJHlPERGavOgXwQRJNmXkylrcGacjsCGUHwYeLfJ"},
        {"mZ/mKpeuRqRtPM.txt", "dpRjdDGbJxPoYYpSiDfJl"},
        {"mtSgmGUWfUrgevJwDubdohIywOXTLOYsgy/SnIsizWDCgqroLMhnRwvqrXed.md", "qgbIeQdEhpUTAewoohqpkSiHsrxwTKsSfcINjrLFdWBJpVSdXkB"},
        {"zLOxzSZfqzfZjVLuqiELGoOXMqIX/MKacfeUKaFMOwdCWuEtnfPc/pxTkFOVavoQFDnMXsFkErCmUah.bin", "oxZzuuNrTbwgnBdlnmncYFfAMcTCssdKnIJsHGDzvDnlVISDaftEsMhbsSVNmAIDGFe"}
      },
      static_cast<std::uint32_t>(8u),
      static_cast<std::size_t>(228u),
      static_cast<std::int64_t>(124),
      { 0x8e, 0x24, 0xfa, 0xf8 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_001",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"DFcOyUbAiFEWjgzJWmGGoDddIuopiq.bin", "chshnPdDZGRuucPKzvqvfKMoquvAYrSTjCdckstqCYv"},
        {"EWxoolnnlBKXceaVD/TNTXEvuKLXbarwdLbeuoavsW.bin", "vKjPnirZERkxFLKGRfNsrpYuzCiVdJUhKQkCqzdRWTAzHCCjHyZmeNIQfVfOkQfaeYEfXrF"},
        {"NcJZXOtqYib/vQAWQetIZwYGWejiepImuTpopUdNq.bin", "XEoCqMOaNIDyEHjWHRWrsSVh"},
        {"OoMJjXyarpOYTWtHofKapwdAJxDlTgfI.md", "UWd"},
        {"PhnnzRDTqJkLRIBxeyFiWMKMnXbaTY/FveliDSEIvcYdOAKdjknHiOMPJYcTt.cfg", "RejKTUuvtgZymDXUAHvwWHMrOjwKCySBnasCpbCl"},
        {"ZAFteERpxofYd.txt", "VvjwilTBUJVnLlrAfcbGsHKHCfLVlMbkUjkVNPWVBMMqeRmtjfAPvXFXd"},
        {"aGeFLHpFTFIMhieUYgLViMy/tL.cfg", "ZbixMoXlhicNJgFPzPSnnpOhBytAddIcexdDuYmbjwtnEDqkYiHXLhGpEyfxBABFNRhwXqsWpdAiRiaQ"},
        {"bTRcHlBuemMHAQQR.md", "tcEwkCsPRMafBVpiSgSBiodqhTQtzHpxwJCfGPudZTZhvpCdHYAqpHwyMZjLOVsyZBB"},
        {"fSE.dat", "kLRmEWjKJBffOzWbZfSTNvHEJoWJCIsYpIEAaKEJnCyQDDYKiWO"},
        {"kGjsRJWEaWKOgXchGPyGUxXyvLyBWGBu.dat", "irTEsKwoKGHSYhOrWHHAMXCYkmbwMHamRmIIdGnpujOumhLgg"},
        {"lWqsLOsrELWtDH/zgTRbbSMZeFqtHqpcuobsydDwp/GYs.cfg", "WR"},
        {"mhhEsGsxeMSBDYHVAsUtQVzTLwMytdRm/AuKrpzFJkwFc/skegefvPNBsHGsRkOqnf.cfg", "TyjSqhoGurZsorJfhtssNnUDuhskibWzTMJpaHVZHVsjklKvFHjXusofdSbpgEOfZmLcWSQRDOG"},
        {"mzCqMhyNVqiArhetgcjeNkAASEZQn/GklwN.txt", "SzJgAnCAuHlSFdoKIiVIQLPBxyARkcYJSUapOdHAinrtlZwtyBLrooQSFIDY"},
        {"sLQYihrDrFXcOH.cfg", "dHnvrQ"},
        {"slvEWngzEYahJvWQpWiebCAKDGTw/zWexwESOJl/tIx.txt", "RJiJfQqUyclifyIbvNoznBwByqkarSMwa"}
      },
      {},
      {
        {"DFcOyUbAiFEWjgzJWmGGoDddIuopiq.bin", "chshnPdDZGRuucPKzvqvfKMoquvAYrSTjCdckstqCYv"},
        {"EWxoolnnlBKXceaVD/TNTXEvuKLXbarwdLbeuoavsW.bin", "vKjPnirZERkxFLKGRfNsrpYuzCiVdJUhKQkCqzdRWTAzHCCjHyZmeNIQfVfOkQfaeYEfXrF"},
        {"NcJZXOtqYib/vQAWQetIZwYGWejiepImuTpopUdNq.bin", "XEoCqMOaNIDyEHjWHRWrsSVh"},
        {"OoMJjXyarpOYTWtHofKapwdAJxDlTgfI.md", "UWd"},
        {"PhnnzRDTqJkLRIBxeyFiWMKMnXbaTY/FveliDSEIvcYdOAKdjknHiOMPJYcTt.cfg", "RejKTUuvtgZymDXUAHvwWHMrOjwKCySBnasCpbCl"},
        {"ZAFteERpxofYd.txt", "VvjwilTBUJVnLlrAfcbGsHKHCfLVlMbkUjkVNPWVBMMqeRmtjfAPvXFXd"},
        {"aGeFLHpFTFIMhieUYgLViMy/tL.cfg", "ZbixMoXlhicNJgFPzPSnnpOhBytAddIcexdDuYmbjwtnEDqkYiHXLhGpEyfxBABFNRhwXqsWpdAiRiaQ"},
        {"bTRcHlBuemMHAQQR.md", "tcEwkCsPRMafBVpiSgSBiodqhTQtzHpxwJCfGPudZTZhvpCdHYAqpHwyMZjLOVsyZBB"},
        {"fSE.dat", "kLRmEWjKJBffOzWbZfSTNvHEJoWJCIsYpIEAaKEJnCyQDDYKiWO"},
        {"kGjsRJWEaWKOgXchGPyGUxXyvLyBWGBu.dat", "irTEsKwoKGHSYhOrWHHAMXCYkmbwMHamRmIIdGnpujOumhLgg"},
        {"lWqsLOsrELWtDH/zgTRbbSMZeFqtHqpcuobsydDwp/GYs.cfg", "WR"},
        {"mhhEsGsxeMSBDYHVAsUtQVzTLwMytdRm/AuKrpzFJkwFc/skegefvPNBsHGsRkOqnf.cfg", "TyjSqhoGurZsorJfhtssNnUDuhskibWzTMJpaHVZHVsjklKvFHjXusofdSbpgEOfZmLcWSQRDOG"},
        {"mzCqMhyNVqiArhetgcjeNkAASEZQn/GklwN.txt", "SzJgAnCAuHlSFdoKIiVIQLPBxyARkcYJSUapOdHAinrtlZwtyBLrooQSFIDY"},
        {"sLQYihrDrFXcOH.cfg", "dHnvrQ"},
        {"slvEWngzEYahJvWQpWiebCAKDGTw/zWexwESOJl/tIx.txt", "RJiJfQqUyclifyIbvNoznBwByqkarSMwa"}
      },
      static_cast<std::uint32_t>(2u),
      static_cast<std::size_t>(516u),
      static_cast<std::int64_t>(316),
      { 0xf4, 0x11, 0x6c, 0xa0 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_002",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"GfRMVCKVaXnksHVhE/BIhLpb.txt", "MoBzRMVptNraaqGMuzaylEClSInfQVLYIFtxhfErhkhAMqUUjKrHCCRYfJwSsOKBnsCNjghd"},
        {"NokmaviPeFEMBDphNZ.cfg", "LLfWlUCAILwgYvVcDHlEMVOnedRevvTsRKbWOUoKpthQnAGtphxotbCrLMuLlCkeyWzMkX"},
        {"cUqBOPOGAq.dat", "pSjPDOobUheUH"},
        {"ciXQWlehEziFfTR.txt", "DcQWGfuczaaVxGnGBpyH"},
        {"fjXrbWXfRIVuA.txt", "fffpUAGLsGeleHcapQpxORFdTd"},
        {"kL/axIUQskaRIpPlnJaFJSWh/htNSkKpRSPGuaOEKtZGxzC.bin", "eXwAsAtaWDmclbCbuNXBgblbalWUMUuiFPVkuVVepvkkMUuhYyMRNsUtmKwFMHyNyZEDVi"},
        {"yQgfNthnOqyAPVM/nqKjJPCszDLaSAXlJ/ySpZWkG.cfg", "vUiflXQmT"}
      },
      {},
      {
        {"GfRMVCKVaXnksHVhE/BIhLpb.txt", "MoBzRMVptNraaqGMuzaylEClSInfQVLYIFtxhfErhkhAMqUUjKrHCCRYfJwSsOKBnsCNjghd"},
        {"NokmaviPeFEMBDphNZ.cfg", "LLfWlUCAILwgYvVcDHlEMVOnedRevvTsRKbWOUoKpthQnAGtphxotbCrLMuLlCkeyWzMkX"},
        {"cUqBOPOGAq.dat", "pSjPDOobUheUH"},
        {"ciXQWlehEziFfTR.txt", "DcQWGfuczaaVxGnGBpyH"},
        {"fjXrbWXfRIVuA.txt", "fffpUAGLsGeleHcapQpxORFdTd"},
        {"kL/axIUQskaRIpPlnJaFJSWh/htNSkKpRSPGuaOEKtZGxzC.bin", "eXwAsAtaWDmclbCbuNXBgblbalWUMUuiFPVkuVVepvkkMUuhYyMRNsUtmKwFMHyNyZEDVi"},
        {"yQgfNthnOqyAPVM/nqKjJPCszDLaSAXlJ/ySpZWkG.cfg", "vUiflXQmT"}
      },
      static_cast<std::uint32_t>(4u),
      static_cast<std::size_t>(78u),
      static_cast<std::int64_t>(22),
      { 0x8f, 0x83, 0xc0, 0x3f, 0x6d, 0xd3, 0xe5, 0x89, 0xc1, 0xe8 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_003",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"EHUQtEQ/eXwkTEDolQfUasyjVo/qMHFOBJJEJN.cfg", "AiRbwyHjcEEOxugLV"},
        {"FlJCOBOTNPTvpDehTdQbfvydVjxhBaqD/xqUWiqCvqbBpRoIDFpxrkrUJKehqVt.dat", "XjeTvfCANXpcOhQuMcqhJEFGaRwSYngPbxtSlNQuwTZyDabmcavYxbCEKpfyr"},
        {"MzYBwzOWBXbZyexlZlLwWT/HbiDEelOnZJ/eQCLLMCrnUhZMNIJ.dat", "XtnulovkisDJNStfzqGCPuQIzBptnizBSruiQJsibfeMhDLuhTHxBE"},
        {"NBagsvZtdSOgvDDolTdozIKLYiXVokPZ/HlrZuOciDsbERHjtK.md", "RUnpxCqfhXeTMH"},
        {"QVfHjSqisPSlOjLfyOLqFTIHHJHmANZxqma/XlgpjcrKgoQgIiGeVZtddMwF/ssLLoTwiHfjMEJCBIqiT.bin", "JqKRjGgbNDNGvQkHkAfbhVCfuTRuGanQSSL"},
        {"RegXpZjusVyTkItSZI/GxySmlfz.cfg", "uODXZDoQiGNBDqaVnPmLyNhiOPplvHYOlSbajkpWcDnzvbeANVeyrnilfncTSMUoLPqupP"},
        {"SGV/DpwtGuEiLZoTNdCOirU/cWXtpJRQTNyeVd.txt", "PBVjJpLXYOeCMukAgXaLEtgmgRXOTmQmWmeVYfeabFWNSPdHIgKANbwaZgerjOsmLEvnuVFVm"},
        {"cCzFHZCuurRmwEg/MoUP/WAyXxmlYrCsTyJMROKxxMHMJHnxtXDB.bin", "IHNxoyuRJhamrahnHWMTnJYTVlzTwpkTqxFickeHuUofoKWURAQQxgFJ"},
        {"jPrHBnD.txt", "yjamyTxBzmdSCq"},
        {"mBopNRngmzrfRhL/zKtTCxwmbMWHHfUwXqujOnorDbUsWsN.txt", "uWnHm"},
        {"mxzKQJreBtDQRzKkaRMiXAsNekJozHVpk/yNadYHBMxscVZj.dat", "dWwBgCdoIG"},
        {"qSEaGEoYqxtneHaVHxIwego/WAFCUpnzctHTsCFpBqPBTsydYUFbFlkrqdSI/eMTDFhQv.txt", "laMSExpAnRdlfuazoOqSUDIspN"},
        {"qSgBlTyiZC/jltpAGaOgvikFQferYpjrcpuEtLO/aLKFhixYbCbBnXhM.dat", "XQkoZVPQhKGKxKCktIptNsHTNZleoEtskxzxDgfUDQUeKqhxHW"},
        {"qpoo.dat", "hmipqcnmPoVBSBXwaUpIwnnYjmSmwhEffGJuUNhApNKYIzXOutypJCqK"},
        {"rZKsXKoifYHJlXG/jpRRudsvmceFyxqTewboZDVEV.cfg", "pPjblpRvONJOLEhrIQjMwjg"},
        {"xRYmhAdemVwjLExIkjfWQqCOrSxnme.bin", "ERWmttsLehHbKWoGveuBjkJCUxyqFgmSNuyIWGFHXRdTCClpZklTIFpKtfNuiCLFYuCGPLbTS"},
        {"yQlZULsxFiVY/ZEYaXspIcUhE/vRDKnfFAbhcJNhAEGC.bin", "FDyqRMZ"}
      },
      {},
      {
        {"EHUQtEQ/eXwkTEDolQfUasyjVo/qMHFOBJJEJN.cfg", "AiRbwyHjcEEOxugLV"},
        {"FlJCOBOTNPTvpDehTdQbfvydVjxhBaqD/xqUWiqCvqbBpRoIDFpxrkrUJKehqVt.dat", "XjeTvfCANXpcOhQuMcqhJEFGaRwSYngPbxtSlNQuwTZyDabmcavYxbCEKpfyr"},
        {"MzYBwzOWBXbZyexlZlLwWT/HbiDEelOnZJ/eQCLLMCrnUhZMNIJ.dat", "XtnulovkisDJNStfzqGCPuQIzBptnizBSruiQJsibfeMhDLuhTHxBE"},
        {"NBagsvZtdSOgvDDolTdozIKLYiXVokPZ/HlrZuOciDsbERHjtK.md", "RUnpxCqfhXeTMH"},
        {"QVfHjSqisPSlOjLfyOLqFTIHHJHmANZxqma/XlgpjcrKgoQgIiGeVZtddMwF/ssLLoTwiHfjMEJCBIqiT.bin", "JqKRjGgbNDNGvQkHkAfbhVCfuTRuGanQSSL"},
        {"RegXpZjusVyTkItSZI/GxySmlfz.cfg", "uODXZDoQiGNBDqaVnPmLyNhiOPplvHYOlSbajkpWcDnzvbeANVeyrnilfncTSMUoLPqupP"},
        {"SGV/DpwtGuEiLZoTNdCOirU/cWXtpJRQTNyeVd.txt", "PBVjJpLXYOeCMukAgXaLEtgmgRXOTmQmWmeVYfeabFWNSPdHIgKANbwaZgerjOsmLEvnuVFVm"},
        {"cCzFHZCuurRmwEg/MoUP/WAyXxmlYrCsTyJMROKxxMHMJHnxtXDB.bin", "IHNxoyuRJhamrahnHWMTnJYTVlzTwpkTqxFickeHuUofoKWURAQQxgFJ"},
        {"jPrHBnD.txt", "yjamyTxBzmdSCq"},
        {"mBopNRngmzrfRhL/zKtTCxwmbMWHHfUwXqujOnorDbUsWsN.txt", "uWnHm"},
        {"mxzKQJreBtDQRzKkaRMiXAsNekJozHVpk/yNadYHBMxscVZj.dat", "dWwBgCdoIG"},
        {"qSEaGEoYqxtneHaVHxIwego/WAFCUpnzctHTsCFpBqPBTsydYUFbFlkrqdSI/eMTDFhQv.txt", "laMSExpAnRdlfuazoOqSUDIspN"},
        {"qSgBlTyiZC/jltpAGaOgvikFQferYpjrcpuEtLO/aLKFhixYbCbBnXhM.dat", "XQkoZVPQhKGKxKCktIptNsHTNZleoEtskxzxDgfUDQUeKqhxHW"},
        {"qpoo.dat", "hmipqcnmPoVBSBXwaUpIwnnYjmSmwhEffGJuUNhApNKYIzXOutypJCqK"},
        {"rZKsXKoifYHJlXG/jpRRudsvmceFyxqTewboZDVEV.cfg", "pPjblpRvONJOLEhrIQjMwjg"},
        {"xRYmhAdemVwjLExIkjfWQqCOrSxnme.bin", "ERWmttsLehHbKWoGveuBjkJCUxyqFgmSNuyIWGFHXRdTCClpZklTIFpKtfNuiCLFYuCGPLbTS"},
        {"yQlZULsxFiVY/ZEYaXspIcUhE/vRDKnfFAbhcJNhAEGC.bin", "FDyqRMZ"}
      },
      static_cast<std::uint32_t>(4u),
      static_cast<std::size_t>(131u),
      static_cast<std::int64_t>(59),
      { 0xc8, 0x99, 0x2b, 0x45, 0x7c },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_004",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"EPzYPfbpDfEsiJbkdwW.md", "WyzmZuojvbcsfIILdCAgnlMSfsbmynwpGdVrfiUClxrpla"},
        {"GsTcKasncTY.bin", "iiwtHwdjHcQxLcmKNXULXKwelgdxgdIlPVqdltYiDemfTsTVtgKpoOFWuyNATFLzougfH"},
        {"IWRKAplKnshttpxKYGhdh/xUB.bin", "QVfZumdxZZloB"},
        {"MfQSmjmn/NrAVJ/hy.bin", "PStyhjZLxwonXNINosFkflzBaJKAlZBKsrBSLLY"},
        {"OllkfQNFAfGXQbuanPAy.bin", "IeJlKkYxTlOhKzSoZyDeDMwaNMPZL"},
        {"PvYjTFzZoiQeOvRqy/YUyxvamiCQZbbAJPDaW.bin", "CsgWdeVbveZfUqCoW"},
        {"TG.txt", "uEAHwHebBtohXSqugiBbqNLeIQbftPVJcyKgtYQEjVjVoGFvjpJkQVjPDpiBjm"},
        {"V/XvaQXvrOYukjZwTRMQfCNMzStL.cfg", "WYyJkyxqotlVOgUxVKKmlHfjwSuNYdNUpSgRXjiQqnVMgaLYfWmqMdoPU"},
        {"YMGIUvshVHBnPQvVMkzwgWuUOLigylL.txt", "RzMLmfjEzcenMKiOixtCxoSEAKOeP"},
        {"bxebtMasUvKjW/snfTeGeETACSsGOgGQDHBRvrMMadothl.md", "imWwFgWkHTQkyuRTxZpjCaXclgKxRVERasWGHtfuKUirKPzDaoMJegygLzf"},
        {"iDK/TrzAFvkuqeOpziwvACkHIjgcgzGnMgqn/WBqDEZ.bin", "dXwKBstUJNGTWCUM"},
        {"iSXAe.md", "WxmJORcbnCwaUmHQNWloHKPxuOalHpUDiNnDfuolKxhvhgkqxEQNUuvlnT"},
        {"mAfgDqzYx.bin", "ubxwjzDHPMyxafXEsrKIJkzPfbfrQbzuDRJzgoWdJRwZHgSAbZFShmhNgEiPZ"},
        {"mJbbMTpUazlIOQhAliYvTmZlFykLdEOaTN/LFdVbyW.md", "sKouCjHuNefYWvFUzxKLatoHgicJNAdRjxiBhEtkMMTb"},
        {"mjyYDRnrXk/qIlDodBjoxTtutFPjuifJt.dat", "UUxMNQOSxVClQIylzPXkkOGRMCQkLJoiogUBPHHtjvWG"},
        {"tWcO/vlldzpooOYotsCNcu/CcZWuFFVBYbsExfOfUOIVGtqlBVGPpz.txt", "SQwyj"},
        {"twTZLT/jtkHJPvMsTpKPrlBQvrRpfBipnEqqf.bin", "YyqmCQnmXVkgyeRIQVlimGrFyNoQPDenmZezwHaRoixkVyIEMCxKFKcxNCeLXTtQTRkzULscpnM"}
      },
      {},
      {
        {"EPzYPfbpDfEsiJbkdwW.md", "WyzmZuojvbcsfIILdCAgnlMSfsbmynwpGdVrfiUClxrpla"},
        {"GsTcKasncTY.bin", "iiwtHwdjHcQxLcmKNXULXKwelgdxgdIlPVqdltYiDemfTsTVtgKpoOFWuyNATFLzougfH"},
        {"IWRKAplKnshttpxKYGhdh/xUB.bin", "QVfZumdxZZloB"},
        {"MfQSmjmn/NrAVJ/hy.bin", "PStyhjZLxwonXNINosFkflzBaJKAlZBKsrBSLLY"},
        {"OllkfQNFAfGXQbuanPAy.bin", "IeJlKkYxTlOhKzSoZyDeDMwaNMPZL"},
        {"PvYjTFzZoiQeOvRqy/YUyxvamiCQZbbAJPDaW.bin", "CsgWdeVbveZfUqCoW"},
        {"TG.txt", "uEAHwHebBtohXSqugiBbqNLeIQbftPVJcyKgtYQEjVjVoGFvjpJkQVjPDpiBjm"},
        {"V/XvaQXvrOYukjZwTRMQfCNMzStL.cfg", "WYyJkyxqotlVOgUxVKKmlHfjwSuNYdNUpSgRXjiQqnVMgaLYfWmqMdoPU"},
        {"YMGIUvshVHBnPQvVMkzwgWuUOLigylL.txt", "RzMLmfjEzcenMKiOixtCxoSEAKOeP"},
        {"bxebtMasUvKjW/snfTeGeETACSsGOgGQDHBRvrMMadothl.md", "imWwFgWkHTQkyuRTxZpjCaXclgKxRVERasWGHtfuKUirKPzDaoMJegygLzf"},
        {"iDK/TrzAFvkuqeOpziwvACkHIjgcgzGnMgqn/WBqDEZ.bin", "dXwKBstUJNGTWCUM"},
        {"iSXAe.md", "WxmJORcbnCwaUmHQNWloHKPxuOalHpUDiNnDfuolKxhvhgkqxEQNUuvlnT"},
        {"mAfgDqzYx.bin", "ubxwjzDHPMyxafXEsrKIJkzPfbfrQbzuDRJzgoWdJRwZHgSAbZFShmhNgEiPZ"},
        {"mJbbMTpUazlIOQhAliYvTmZlFykLdEOaTN/LFdVbyW.md", "sKouCjHuNefYWvFUzxKLatoHgicJNAdRjxiBhEtkMMTb"},
        {"mjyYDRnrXk/qIlDodBjoxTtutFPjuifJt.dat", "UUxMNQOSxVClQIylzPXkkOGRMCQkLJoiogUBPHHtjvWG"},
        {"tWcO/vlldzpooOYotsCNcu/CcZWuFFVBYbsExfOfUOIVGtqlBVGPpz.txt", "SQwyj"},
        {"twTZLT/jtkHJPvMsTpKPrlBQvrRpfBipnEqqf.bin", "YyqmCQnmXVkgyeRIQVlimGrFyNoQPDenmZezwHaRoixkVyIEMCxKFKcxNCeLXTtQTRkzULscpnM"}
      },
      static_cast<std::uint32_t>(3u),
      static_cast<std::size_t>(400u),
      static_cast<std::int64_t>(232),
      { 0xfd, 0x31, 0x57, 0x1a, 0xd4, 0x96, 0x8d, 0x7b, 0xe8, 0x22, 0x29, 0x9b, 0xc3, 0xa7, 0xeb, 0x73, 0x04, 0x08, 0xb8, 0xfc, 0x45, 0x10, 0xe0, 0xc5 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_005",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"CvPo/SKhXb/nRRmrOUTyYkANGvOyVvBFK.md", "pvIKSDziQeeAkSufWEyyrqrWVMygX"},
        {"DBQPxE/IvJGNEAVDFOXQqTxFYHGAK/aYUkZdjdyjUEvWqiUoFNsr.md", "ywIrZ"},
        {"DglY/XWmbDZEGWtmWKkHnNRxvYOIEy.md", "bcDkjOmCfApOkfDhvhZTvaBAmNbt"},
        {"EPZpjtRiiYqfyswlzM/RXXGIhFHmnx/HgpLuYM.md", "yJFnIFpyaeNqngTotmimbfiEiBvqxYEuytqGECVoOM"},
        {"IGKDAOkORAxWSBTMoQHjdXKMStDFnJWbaC/zMvufKrtnbZGHPkpNCGNpbBZIyFPucvT/nPgyBrkPFBhdIgvEORe.cfg", "EazqwzqMDPxyAYKHWxloteSuRuHgFTKvmgwKfkhTKlbBN"},
        {"MqVfQUrDnodNEINJuCzdvgx/ggfKoUOLvSZXqHRkhDtwgaaDL.cfg", "qWd"},
        {"ODlCHRbVvoHvtnHtuDQOSRkkBAMp.md", "zzvdlSMOdVCLdSgNVVFfIRx"},
        {"bScWIcWkpifHpdl.md", "PXRfzyFtsdmbclPNYeLeuDeqVDSpQbxpvSJsoSNQTnHSWuCeClMLyTUlnmv"},
        {"cPjJzrmHkryou/PUyIJqMoBxocPvkRyujRjPzCDHKGxIpfOkT/nEH.cfg", "VhSivWDlSbNXLHYCBVuuROQYetOKzlUvLISdIftc"},
        {"gIQcwoGcwP/PqowhHXwDSqAMrAwUWnile.cfg", "SJVBAsgveTkuXFFfHUrbkUuXZuDhdcrzakkimLliAESxhFHSaBzLHEsJCfNDcLRkWZLYxSGeatF"},
        {"jqWVURkmItBWvdpBgIvSvaPS/YTuMbpfHEmegVgUoqptmYFtzNoMCAQr/JVklGUzIT.md", "IfpVTrGWfJCmcyLgytxSvlDiRVoBiBbvENyGFCuDiVlthPeBFOJNxN"},
        {"somqUeEbF/hQdKLeRQJVEXVA/kZXSkK.cfg", "eUfvWdBX"},
        {"wIvq/gGWITW/SbeViLnHkIuMiPgTfYuMmGvzJoRI.dat", "eVYBGOncycoaZyuiUSds"}
      },
      {},
      {
        {"CvPo/SKhXb/nRRmrOUTyYkANGvOyVvBFK.md", "pvIKSDziQeeAkSufWEyyrqrWVMygX"},
        {"DBQPxE/IvJGNEAVDFOXQqTxFYHGAK/aYUkZdjdyjUEvWqiUoFNsr.md", "ywIrZ"},
        {"DglY/XWmbDZEGWtmWKkHnNRxvYOIEy.md", "bcDkjOmCfApOkfDhvhZTvaBAmNbt"},
        {"EPZpjtRiiYqfyswlzM/RXXGIhFHmnx/HgpLuYM.md", "yJFnIFpyaeNqngTotmimbfiEiBvqxYEuytqGECVoOM"},
        {"IGKDAOkORAxWSBTMoQHjdXKMStDFnJWbaC/zMvufKrtnbZGHPkpNCGNpbBZIyFPucvT/nPgyBrkPFBhdIgvEORe.cfg", "EazqwzqMDPxyAYKHWxloteSuRuHgFTKvmgwKfkhTKlbBN"},
        {"MqVfQUrDnodNEINJuCzdvgx/ggfKoUOLvSZXqHRkhDtwgaaDL.cfg", "qWd"},
        {"ODlCHRbVvoHvtnHtuDQOSRkkBAMp.md", "zzvdlSMOdVCLdSgNVVFfIRx"},
        {"bScWIcWkpifHpdl.md", "PXRfzyFtsdmbclPNYeLeuDeqVDSpQbxpvSJsoSNQTnHSWuCeClMLyTUlnmv"},
        {"cPjJzrmHkryou/PUyIJqMoBxocPvkRyujRjPzCDHKGxIpfOkT/nEH.cfg", "VhSivWDlSbNXLHYCBVuuROQYetOKzlUvLISdIftc"},
        {"gIQcwoGcwP/PqowhHXwDSqAMrAwUWnile.cfg", "SJVBAsgveTkuXFFfHUrbkUuXZuDhdcrzakkimLliAESxhFHSaBzLHEsJCfNDcLRkWZLYxSGeatF"},
        {"jqWVURkmItBWvdpBgIvSvaPS/YTuMbpfHEmegVgUoqptmYFtzNoMCAQr/JVklGUzIT.md", "IfpVTrGWfJCmcyLgytxSvlDiRVoBiBbvENyGFCuDiVlthPeBFOJNxN"},
        {"somqUeEbF/hQdKLeRQJVEXVA/kZXSkK.cfg", "eUfvWdBX"},
        {"wIvq/gGWITW/SbeViLnHkIuMiPgTfYuMmGvzJoRI.dat", "eVYBGOncycoaZyuiUSds"}
      },
      static_cast<std::uint32_t>(2u),
      static_cast<std::size_t>(217u),
      static_cast<std::int64_t>(113),
      { 0xd9, 0xe1, 0x94, 0x63, 0x66, 0xa4, 0xf0, 0xad, 0x7b, 0x3d, 0x61, 0x4f, 0x3e, 0xd2, 0x36 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_006",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"LKHMOsRyspWwal/uMnQbZ/YfhJF.txt", "SNFzREAkguPQvynqdiNiLjpFoqQuSUORxSHwyNQteZOInNkNnphoPoMorRGwrzQuxBMrQVqWETB"},
        {"XYDYODNUGtDGxaqXUJ/COYxNrRCoTrCgvpOOIkTNhvqkBlFGPqmWZso/KsnhVcoISxIgYYulgQsIfYwM.cfg", "QXvepujmKhpbqRxwmHQsoNFknNFDRFUhkGndAzlZzpTfmraklIpflc"},
        {"cLipEwONqxKKUVfHuqzcZJoWfsHlRxm/nfOOPGQfWMQyWUQTdNqurZNYVRxNVFy.txt", "GvYvPXJCyXTsDV"},
        {"eMKYQWQlPsSrwMCXtuwcnHK/gEagwKZbeddfmZRGAGMcJOTdXKJOofn.txt", "cioXHRnkRdUiJsuYfzPQAPanSo"},
        {"jFjOD.cfg", "jVGNwodTPXmIENcrUhclOhZYeFOEP"},
        {"kFFsZCkNMBJioOix/OqlAvI.cfg", "lMOXAHqETrrmeaiqmvvWSmkUUzMECfvIjdXpfoypNQEMBSsIlUjxSjoehSBvXCKPByvDrfBNaLrzyblG"},
        {"paPgxGRzslOcQimQEDvNTnYlNXQk/RYnZzNLXSDrnLExYHrBIfyLaysDCHjSwSeXO/OmoSAhIZEdorKlgmpTrLKdHRU.txt", "qRzvZwzvSyCKcUcziGlHAclgIllZyLuOfSEGZCvEumTKaGPMhbwCoHKRLWqHltyhbtdFd"},
        {"tzRODIhAIQSTWxojRHygRd.cfg", "pLtwNnBzQIDjjsmalzvpTfzAXMPLZUSVimTWGtWAoBVzbGHlrrXSJgOVQCwRiDuAIltP"},
        {"xLxhRyFHqPXQISSgOHmAjIWatC/vvYrNdrjWV.bin", "MMzYPNvMdW"},
        {"zlhDsuBDtAKB.md", "pDXhLaTOgJPbidxREHKjaVrLMqDqdDgQHqUIvrORPUCqQSdyFxozSBcfimLRPVjXOaqMKdRLJaPDbJ"}
      },
      {},
      {
        {"LKHMOsRyspWwal/uMnQbZ/YfhJF.txt", "SNFzREAkguPQvynqdiNiLjpFoqQuSUORxSHwyNQteZOInNkNnphoPoMorRGwrzQuxBMrQVqWETB"},
        {"XYDYODNUGtDGxaqXUJ/COYxNrRCoTrCgvpOOIkTNhvqkBlFGPqmWZso/KsnhVcoISxIgYYulgQsIfYwM.cfg", "QXvepujmKhpbqRxwmHQsoNFknNFDRFUhkGndAzlZzpTfmraklIpflc"},
        {"cLipEwONqxKKUVfHuqzcZJoWfsHlRxm/nfOOPGQfWMQyWUQTdNqurZNYVRxNVFy.txt", "GvYvPXJCyXTsDV"},
        {"eMKYQWQlPsSrwMCXtuwcnHK/gEagwKZbeddfmZRGAGMcJOTdXKJOofn.txt", "cioXHRnkRdUiJsuYfzPQAPanSo"},
        {"jFjOD.cfg", "jVGNwodTPXmIENcrUhclOhZYeFOEP"},
        {"kFFsZCkNMBJioOix/OqlAvI.cfg", "lMOXAHqETrrmeaiqmvvWSmkUUzMECfvIjdXpfoypNQEMBSsIlUjxSjoehSBvXCKPByvDrfBNaLrzyblG"},
        {"paPgxGRzslOcQimQEDvNTnYlNXQk/RYnZzNLXSDrnLExYHrBIfyLaysDCHjSwSeXO/OmoSAhIZEdorKlgmpTrLKdHRU.txt", "qRzvZwzvSyCKcUcziGlHAclgIllZyLuOfSEGZCvEumTKaGPMhbwCoHKRLWqHltyhbtdFd"},
        {"tzRODIhAIQSTWxojRHygRd.cfg", "pLtwNnBzQIDjjsmalzvpTfzAXMPLZUSVimTWGtWAoBVzbGHlrrXSJgOVQCwRiDuAIltP"},
        {"xLxhRyFHqPXQISSgOHmAjIWatC/vvYrNdrjWV.bin", "MMzYPNvMdW"},
        {"zlhDsuBDtAKB.md", "pDXhLaTOgJPbidxREHKjaVrLMqDqdDgQHqUIvrORPUCqQSdyFxozSBcfimLRPVjXOaqMKdRLJaPDbJ"}
      },
      static_cast<std::uint32_t>(8u),
      static_cast<std::size_t>(71u),
      static_cast<std::int64_t>(15),
      { 0x57, 0x03, 0x5c, 0x65, 0xb4, 0x30, 0x86, 0xdc, 0x28, 0x7e, 0x1c, 0x17, 0x3c, 0x42, 0xa8, 0x80, 0x18 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_007",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(4u),
      {
        {"LjROlgEpdBEGDFikeroRhcXNqHdNyTZciuFt/LAzNAjqpMsgPX.txt", "gsDdBafnBTTTQyGWIAkSEHGzbXhzVbRBjOBjpqGTbXw"}
      },
      {},
      {
        {"LjROlgEpdBEGDFikeroRhcXNqHdNyTZciuFt/LAzNAjqpMsgPX.txt", "gsDdBafnBTTTQyGWIAkSEHGzbXhzVbRBjOBjpqGTbXw"}
      },
      static_cast<std::uint32_t>(0u),
      static_cast<std::size_t>(211u),
      static_cast<std::int64_t>(107),
      { 0x3a, 0x6e, 0xa3, 0xcb, 0x06, 0xf8, 0x4c, 0x0d, 0xf0, 0xf8, 0x64, 0x04, 0x2d, 0x0d, 0x8d, 0xa1, 0xb9, 0xaa, 0xc6, 0xcf, 0x27 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_008",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(1u),
      {
        {"FeoNIajd/JLlPOjyRfQRwgwWpYGzcAmOe.bin", "NnNnNuUxcrsDezgeWqLKAijZyKWkaUbAZK"},
        {"GKRgpBuAKTlmxzJocqHAP/FkOjowg.md", "AgtHOjpcSnkKmbSyBUvqz"},
        {"JMDmKYqgXTsiTBmUyWJXjki/eOXRIuBiUxllmrVOtgl/BySeraqGUTAIIEDvXDlZsIbKuE.md", "sSPYnaEwGCQCdPJh"},
        {"RvQMlYlSUEmQDnESBCFtqh/HrLaGhFSAngjxbfxL.txt", "WAN"},
        {"gnGjmdoKuAUyyIIfIXWsYc.bin", "beFfGbpboccCoqrKXzpnUqQAokHOfafCSVlVNSwIsTrSFXLvtWAETbjvTfSEBDSFPnwMASkzbthMjWfE"},
        {"lsjfgztRpaLEt/ejFsxXWgMiPfYvymiDqRjASTKOEdsVfc/sVuwDrVgJsppTloBYh.bin", "xPwmLcwwqCVAsBycpfFegQscbzafhfHBGLyTiKoeHDWL"},
        {"luOinollAoEYXXfate.bin", "kcshlVtTyquMRZSlVcjuDguHWuCKmsHngBnXWuNh"},
        {"ozKRLBGCQvGfSvLfJBUsSeDzggcnlx/EzluqK.dat", "UOykCrqFiuAMmVGJWBiDJXuyoJPnVuGvtvLMRxpZ"}
      },
      {},
      {
        {"FeoNIajd/JLlPOjyRfQRwgwWpYGzcAmOe.bin", "NnNnNuUxcrsDezgeWqLKAijZyKWkaUbAZK"},
        {"GKRgpBuAKTlmxzJocqHAP/FkOjowg.md", "AgtHOjpcSnkKmbSyBUvqz"},
        {"JMDmKYqgXTsiTBmUyWJXjki/eOXRIuBiUxllmrVOtgl/BySeraqGUTAIIEDvXDlZsIbKuE.md", "sSPYnaEwGCQCdPJh"},
        {"RvQMlYlSUEmQDnESBCFtqh/HrLaGhFSAngjxbfxL.txt", "WAN"},
        {"gnGjmdoKuAUyyIIfIXWsYc.bin", "beFfGbpboccCoqrKXzpnUqQAokHOfafCSVlVNSwIsTrSFXLvtWAETbjvTfSEBDSFPnwMASkzbthMjWfE"},
        {"lsjfgztRpaLEt/ejFsxXWgMiPfYvymiDqRjASTKOEdsVfc/sVuwDrVgJsppTloBYh.bin", "xPwmLcwwqCVAsBycpfFegQscbzafhfHBGLyTiKoeHDWL"},
        {"luOinollAoEYXXfate.bin", "kcshlVtTyquMRZSlVcjuDguHWuCKmsHngBnXWuNh"},
        {"ozKRLBGCQvGfSvLfJBUsSeDzggcnlx/EzluqK.dat", "UOykCrqFiuAMmVGJWBiDJXuyoJPnVuGvtvLMRxpZ"}
      },
      static_cast<std::uint32_t>(5u),
      static_cast<std::size_t>(120u),
      static_cast<std::int64_t>(48),
      { 0xfe, 0x4d, 0xe8, 0x5c, 0xa2, 0x2c, 0xac, 0x31, 0xea, 0x5a, 0x52, 0xb4, 0xdf, 0x08, 0x8d, 0x49 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_009",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"KCEsrApgQmnWZGOaygkKUkqoCEsbJwwr/s/drpTsuaACGaSCS.cfg", "oKajtDbcJfOkcGPGQJFgHTEbXoijDnJxFkUOCpnCIwPaPYmfpqfZRtvBNpFdOpHdtuSyo"},
        {"UxBiOBWeTRDysaTTvIdmWMssMSyB.txt", "pXboQWNJRDuvfMFnlJSMDyxQvUidzEgUPwO"},
        {"XnzcyMXKNoPTKYNZXKWfVWfXohPz.md", "XiIxMhcbjvXQkEImvXBNMjAQXTTtfByUWKMxHrUhwtfVOgVIkoicaPrixf"},
        {"dMrbbb/TXkbWpVgYwHFhTDAjMonOQSmhxeEkFvvZgql/IkWxHNnYfCnYPaHWZJkSgdcwCiRlCpAe.md", "pOzmdmoiAoqhejEhjeOXOThcjxAeqNYFCdbVOc"},
        {"pK/sfPcVZTACNDIBMezEke/gCjKO.txt", "VbCozxtjfrtgWbkvxh"},
        {"ujIIjSO/nNwnuEoYTjYg/mRLCmElyNmHqzrZ.cfg", "hYXPJHJBnqPGdspLqXrtLzLWFClva"},
        {"zjkWIilibvaWzGkeoIVPAI/zKuxbIMlKQCeKHrrVqPjYdnBW/oOjrFxJyy.bin", "GxWrKldILPGohQQuPrmGCRYiLxABTDgdpAlPhEghngeoZNqxvgmpw"}
      },
      {},
      {
        {"KCEsrApgQmnWZGOaygkKUkqoCEsbJwwr/s/drpTsuaACGaSCS.cfg", "oKajtDbcJfOkcGPGQJFgHTEbXoijDnJxFkUOCpnCIwPaPYmfpqfZRtvBNpFdOpHdtuSyo"},
        {"UxBiOBWeTRDysaTTvIdmWMssMSyB.txt", "pXboQWNJRDuvfMFnlJSMDyxQvUidzEgUPwO"},
        {"XnzcyMXKNoPTKYNZXKWfVWfXohPz.md", "XiIxMhcbjvXQkEImvXBNMjAQXTTtfByUWKMxHrUhwtfVOgVIkoicaPrixf"},
        {"dMrbbb/TXkbWpVgYwHFhTDAjMonOQSmhxeEkFvvZgql/IkWxHNnYfCnYPaHWZJkSgdcwCiRlCpAe.md", "pOzmdmoiAoqhejEhjeOXOThcjxAeqNYFCdbVOc"},
        {"pK/sfPcVZTACNDIBMezEke/gCjKO.txt", "VbCozxtjfrtgWbkvxh"},
        {"ujIIjSO/nNwnuEoYTjYg/mRLCmElyNmHqzrZ.cfg", "hYXPJHJBnqPGdspLqXrtLzLWFClva"},
        {"zjkWIilibvaWzGkeoIVPAI/zKuxbIMlKQCeKHrrVqPjYdnBW/oOjrFxJyy.bin", "GxWrKldILPGohQQuPrmGCRYiLxABTDgdpAlPhEghngeoZNqxvgmpw"}
      },
      static_cast<std::uint32_t>(1u),
      static_cast<std::size_t>(503u),
      static_cast<std::int64_t>(303),
      { 0x17, 0x4a, 0x6f, 0xd0, 0xf7, 0x57, 0xa1, 0x2e, 0xb0, 0x26, 0xe0, 0x1d, 0x7a, 0xd8, 0x2a, 0xf6, 0xef },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_010",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(2u),
      {
        {"GUVRjtJvbHOBJMDynBhlBUtQgbRwPjQB/NVdohDXandvoIVkFETmH.md", "MICGxAYFmWrMrRWDccLzXgoVPUKERtdLWMnZWMloaojjcZoPGWIHuIJDVs"},
        {"XNLBRFITzmh/obBuUBFLfJtKlIDFjTPMJRFCezpqX.cfg", "JlToCdbEjgnQBBMKbxrLqWKDnQoAvEPSUdHLRCQprrszvFvsjjuEEVZko"},
        {"yOGZURrXAKEBXTUhUFyLoiRvgtLS/qhHQaAzNkNcOwfTYMCinYQNETjffdd.cfg", "uhcbGMRGeGhYsPnCxprdOqhhczyBAwcSnbfpozXePtcWlZefudPShlvICUyvEypQEXbqRwrLwIjbJ"}
      },
      {},
      {
        {"GUVRjtJvbHOBJMDynBhlBUtQgbRwPjQB/NVdohDXandvoIVkFETmH.md", "MICGxAYFmWrMrRWDccLzXgoVPUKERtdLWMnZWMloaojjcZoPGWIHuIJDVs"},
        {"XNLBRFITzmh/obBuUBFLfJtKlIDFjTPMJRFCezpqX.cfg", "JlToCdbEjgnQBBMKbxrLqWKDnQoAvEPSUdHLRCQprrszvFvsjjuEEVZko"},
        {"yOGZURrXAKEBXTUhUFyLoiRvgtLS/qhHQaAzNkNcOwfTYMCinYQNETjffdd.cfg", "uhcbGMRGeGhYsPnCxprdOqhhczyBAwcSnbfpozXePtcWlZefudPShlvICUyvEypQEXbqRwrLwIjbJ"}
      },
      static_cast<std::uint32_t>(1u),
      static_cast<std::size_t>(230u),
      static_cast<std::int64_t>(126),
      { 0x1f, 0x4c },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    },
    {
      "AUTO_EndOfFile_TrailingGarbage_MEDIUM_011",
      "unbundle",
      "eof_gar",
      "UNP_EOF_002",
      "",
      {},
      static_cast<std::size_t>(3u),
      {
        {"CuXrwReOGozBMu/TEtfbbmFtdbutqsXs.cfg", "bltNQjXisTdfWayOMcYIa"},
        {"FIVKoUZGWJzHCURttSXEpKu.txt", "CkVvyeED"},
        {"JuLpO/oBsECJBbRfCaZsHVFtAzwrPoOpHpnUtEBgaw/LxzvsgrtzetAMvMpJZmGYqGwLeeabqBHN.md", "LKmyLLQqcMqypCDzXSNz"},
        {"WFljcpmmnFNmHQNqDCWRUxiZKzjaRriCC/lu/jWfwflIOEqaggJ.bin", "EfNQmuOSjeMgRZBrkRlsPdMQiDsoqSQ"},
        {"hTpTxEScYvnTaqmcPGWrEiyhPQLWif/IxGwmuCUIDoZdyKiOy/PJmEojWxkhlSvPFeGgFxpPFP.cfg", "mpNIpbuJAiLupmjKpLVEJgyYgQeAFxoyvKLuKOwvKCjFXn"},
        {"jQHKPsPuYjvYaDPxxlSqilsdiCHaNNZ/YLqQadVtNjKtFCbFoYTnrfvurpW/VASXukbztMvuRaHEvTjNSo.cfg", "JBHRWXnrhrtNaZaFWzosqidUETLXldFKwqlU"},
        {"nEOmYMMVtHSIBcaWdbPWRuk.txt", "ePDiuLowMFZWnxhktsKtPZOPjahEHkteN"}
      },
      {},
      {
        {"CuXrwReOGozBMu/TEtfbbmFtdbutqsXs.cfg", "bltNQjXisTdfWayOMcYIa"},
        {"FIVKoUZGWJzHCURttSXEpKu.txt", "CkVvyeED"},
        {"JuLpO/oBsECJBbRfCaZsHVFtAzwrPoOpHpnUtEBgaw/LxzvsgrtzetAMvMpJZmGYqGwLeeabqBHN.md", "LKmyLLQqcMqypCDzXSNz"},
        {"WFljcpmmnFNmHQNqDCWRUxiZKzjaRriCC/lu/jWfwflIOEqaggJ.bin", "EfNQmuOSjeMgRZBrkRlsPdMQiDsoqSQ"},
        {"hTpTxEScYvnTaqmcPGWrEiyhPQLWif/IxGwmuCUIDoZdyKiOy/PJmEojWxkhlSvPFeGgFxpPFP.cfg", "mpNIpbuJAiLupmjKpLVEJgyYgQeAFxoyvKLuKOwvKCjFXn"},
        {"jQHKPsPuYjvYaDPxxlSqilsdiCHaNNZ/YLqQadVtNjKtFCbFoYTnrfvurpW/VASXukbztMvuRaHEvTjNSo.cfg", "JBHRWXnrhrtNaZaFWzosqidUETLXldFKwqlU"},
        {"nEOmYMMVtHSIBcaWdbPWRuk.txt", "ePDiuLowMFZWnxhktsKtPZOPjahEHkteN"}
      },
      static_cast<std::uint32_t>(1u),
      static_cast<std::size_t>(441u),
      static_cast<std::int64_t>(257),
      { 0xcd, 0x2c, 0x22, 0x69, 0x0f, 0x8e, 0x8f, 0x6c, 0x91, 0xdf, 0x68, 0x45, 0x13, 0xf6, 0x01, 0x83, 0xa9, 0xb6, 0xd6, 0xea, 0xf5, 0xc1, 0x35, 0x07, 0x8f, 0x6a, 0x9a, 0x2e, 0xf7, 0x64, 0xb3 },
      {},
      {},
      "EOF garbage case, target type ignored for EOF source mode."
    }
};

bool ValidateCaseOutcome(const GeneratedFenceCaseData& pCase,
                         const FenceRoundTripOutcome& pOutcome,
                         std::string& pError) {
  if (!pOutcome.mSucceeded) {
    pError = pOutcome.mFailureMessage;
    return false;
  }

  if (!pCase.mExpectedErrorCode.empty()) {
    const bool aHasExpectedError =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, pCase.mExpectedErrorCode) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, pCase.mExpectedErrorCode) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, pCase.mExpectedErrorCode);
    if (!aHasExpectedError) {
      pError = "missing expected error code: " + pCase.mExpectedErrorCode;
      return false;
    }
  }

  if (!pCase.mExpectedFenceFlag.empty()) {
    const bool aHasFenceFlag =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, pCase.mExpectedFenceFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, pCase.mExpectedFenceFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, pCase.mExpectedFenceFlag);
    if (!aHasFenceFlag) {
      pError = "missing expected fence flag: " + pCase.mExpectedFenceFlag;
      return false;
    }
  }

  for (const std::string& aForbiddenFlag : pCase.mForbiddenFenceFlags) {
    const bool aHasForbiddenFlag =
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedUnbundleMessage, aForbiddenFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mMutatedRecoverMessage, aForbiddenFlag) ||
        peanutbutter::testing::ContainsToken(pOutcome.mCollectedLogs, aForbiddenFlag);
    if (aHasForbiddenFlag) {
      pError = "encountered forbidden fence flag: " + aForbiddenFlag;
      return false;
    }
  }

  return true;
}

}  // namespace

int main() {
  if (peanutbutter::SB_PAYLOAD_SIZE <= (peanutbutter::SB_RECOVERY_HEADER_LENGTH + 1)) {
    std::cout << "[WARN] generated fence suite invalid L1 block size for " << kCases.size() << " case(s).\n";
    return 0;
  }

  for (const GeneratedFenceCaseData& aCase : kCases) {
    FenceRoundTripSpec aSpec;
    aSpec.mCaseName = aCase.mCaseId;
    aSpec.mOriginalFiles = aCase.mInputFiles;
    aSpec.mOriginalEmptyDirectories = aCase.mInputEmptyDirs;
    aSpec.mRecoverableFiles = aCase.mRecoverableFiles;
    aSpec.mArchiveBlockCount = aCase.mArchiveBlockCount;
    aSpec.mExpectMutatedUnbundleFailure = (aCase.mFlow == "unbundle");
    aSpec.mExpectedUnbundleErrorCode = (aCase.mFlow == "unbundle") ? aCase.mExpectedErrorCode : "";
    aSpec.mRunRecoverAfterMutation = (aCase.mFlow == "recover");
    aSpec.mRequireRecoverTreeMatch = false;

    const bool aSupportsPayloadMutation =
        (aCase.mFieldKind == "file_name_length") ||
        (aCase.mFieldKind == "file_content_length") ||
        (aCase.mFieldKind == "directory_name_length") ||
        (aCase.mFieldKind == "eof_gar");
    if (aSupportsPayloadMutation && aCase.mMutationPayloadLogicalOffset >= 0) {
      GenericArchiveDataMutation aMutation;
      aMutation.mArchiveIndex = aCase.mArchiveIndex;
      aMutation.mPayloadLogicalOffset = static_cast<std::size_t>(aCase.mMutationPayloadLogicalOffset);
      aMutation.mBytes = aCase.mMutationBytes;
      aSpec.mMutation.mArchiveDataMutations.push_back(aMutation);
    } else {
      GenericArchiveByteMutation aMutation;
      aMutation.mArchiveIndex = aCase.mArchiveIndex;
      aMutation.mFileOffset = aCase.mMutationFileOffset;
      aMutation.mBytes = aCase.mMutationBytes;
      aSpec.mMutation.mArchiveByteMutations.push_back(aMutation);
    }
    aSpec.mMutation.mArchiveSetMutation.mCreateArchiveIndices = aCase.mCreateArchiveIndices;
    aSpec.mMutation.mArchiveSetMutation.mRemoveArchiveIndices = aCase.mRemoveArchiveIndices;

    const FenceRoundTripOutcome aOutcome = peanutbutter::testing::ExecuteFenceTestRoundTrip(aSpec);
    std::string aError;
    if (!ValidateCaseOutcome(aCase, aOutcome, aError)) {
      std::cerr << "[FAIL] " << aCase.mCaseId << " failed: " << aError << "\n";
      if (!aCase.mFailurePointComment.empty()) {
        std::cerr << "[INFO] " << aCase.mFailurePointComment << "\n";
      }
      std::cerr << aOutcome.mCollectedLogs;
      return 1;
    }
  }

  std::cout << "[PASS] generated fence suite passed for " << kCases.size() << " case(s).\n";
  return 0;
}
